### ISSUE TITLE
sendTransaction returning wrong tx hash on testrpc

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-plugin#1023]
From denisgranha

web3.eth.sendTransaction({to: "0x5dcD834cf776F47F138943e3466440009a2F2B00", value: "0x10000000000000"}, console.log);

// This returns null "0x04070f9504c2752ee37b5dbf592c35edf9b2a8a5cfe8abb45713176e9e1ed5e1"

web3.eth.getTransactionReceipt("0x04070f9504c2752ee37b5dbf592c35edf9b2a8a5cfe8abb45713176e9e1ed5e1", console.log);

// This returns null null

**Comment by Zanibas** [comment]
This is because our web3.eth.sendTransaction is sending the incorrect hash.

**Comment by Zanibas** [comment]
May be related to ethereumjs-tx per @kumavis  suggestion.

**Comment by flyswatter** [comment]
I've replicated this on testrpc also, so this isn't just a ropsten bug.  The result of `sendTransaction` is never a valid tx receipt.

**Comment by kumavis** [comment]
yeah just confirmed ropsten hashes are working fine

**Comment by flyswatter** [comment]
So we're pretty sure this is TestRPC not implementing EIP 155 protections. @tcoulter.

Quick fix steps:
- We stop using EIP 155 protections on unknown networks.
- We open an issue on Truffle.

**Comment by kumavis** [comment]
another solution is to just return whatever hash the network suggests

**Comment by flyswatter** [comment]
That would be good too, because the TXs *do* seem to go through, they aren't outright rejected.
