### ISSUE TITLE
Private key import allows for duplicates

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-plugin#1032]
Although the UI side is fine, if users end up entering the same private key multiple times, the accounts list gets cluttered with duplicates and could be a cause for future bugs.

This can be replicated by importing the same private key several times and checking the output of logState.

**Comment by frankiebee** [comment]
this is not an import issue. it's a keyring migration issue

**Comment by flyswatter** [comment]
So what would you propose is a better UX here?  Just auto-detecting duplicates, and warning the user?

**Comment by Zanibas** [comment]
I think this would be good @flyswatter. I'll attempt work on this now.
