### ISSUE TITLE
3D logo is very CPU intensive

### ISSUE THREAD

**Issue by luisivan** [MetaMask/metamask-plugin#1035]
Hey guys,

Just wanted to say that the animated logo rocks, but it's very CPU intensive. Profiling my app (that has MetaMask embedded and always running) I figured out it took about 20% of all the CPU cycles while idle. Showing the image logo instead of the animated one looks kind of the same while greatly improving performance.

What do you guys think about it?
Thanks

**Comment by flyswatter** [comment]
Hey @luisivan!

When you say while idle, do you mean you're leaving the popup open, and measuring performance?  The logo should only be using any resources while on the locked screen. Any other performance hits are not related to it.  We're not too concerned about the lock screen's performance, since it's only used so briefly.

If you're seeing performance hits in the background, that's not the logo, it's probably the block polling, or some of the logic to stay in sync with the blockchain.

Could you clarify how you're measuring this?

**Comment by luisivan** [comment]
Thanks for replying @flyswatter! I guess it depends on the use case. On our use case, we keep MetaMask's UI always open so it responds faster, so the lock screen can actually be eating valuable resources.

Regarding the measurement method, I just did a CPU profile using Blink's inspector. Block polling also ate a lot of resources, but the logo was like 20%.

**Comment by flyswatter** [comment]
Oh, that's interesting. Still curious what you're up to!

This raises a good question, about how we should proceed when one platform could use a compromise that is pretty acceptable on other platforms. Anyone else have an opinion?

Couldn't you just swap out the logo in your branch? Maybe we could add a conditional build step?

**Comment by luisivan** [comment]
Sure thing! I already replaced the logo in my own fork, so zero problems on my side if you decide to keep it. I just wanted to point out that it really takes system resources that some constrained systems may need for polling etc.

**Comment by flyswatter** [comment]
I wish there was a good way to detect how casual the user might want to be with resources, like detecting CPU power...

Ultimately I feel like I do agree with this, a program's first job is to run well.  I just hate removing things people like.

**Comment by kumavis** [comment]
> This raises a good question, about how we should proceed when one platform could use a compromise that is pretty acceptable on other platforms. Anyone else have an opinion?

Like  with `background,js` `popup.js` can be the platform specific setup
we could add an option in the app constructor about whether or not to disable the 3d fox

**Comment by flyswatter** [comment]
I agree, popup.js is itself an very platform specific file. Hopefully some parts of it like components could be re used, but it could be good to do for the UI what we did for the background, and really split apart the platform from the interface.

- Dan
