### ISSUE TITLE
callback not called when sending transaction without enough ether

### ISSUE THREAD

**Issue by nbremond** [MetaMask/metamask-plugin#1047]
I have an account with 1 ETH and a contract with a payable method.
If I tried to send 10 000 ETHER to my contract, the confirmation window tell me that I don't have enough ether and I can buy or reject. When I reject, the callback is called with err set apropriately.
The problem is if I try to send 1, 10, 100 or 1 000 ETH. The confirmation window do not tell me that I need ether and if I click on the «accept» button, I get an other window which says "MetaMask Insufficient funds for gas * price + value" and the callback method is not called.

The transaction is sent with the code 

    var wei=…//get value from a form
    myContract.myMethod(params, {value : wei}, myCallback);

**Comment by frankiebee** [comment]
So @nbremond i just want to clarify some details. you are seeing 2 issues here?
1. The confirmation window does not tell you that you need ether and their for lets you approve 
2. approval of a transaction when their are not enough funds does not call the cb

Just clarify, when you approve a transaction that have enough funds for does the cb get called?

**Comment by nbremond** [comment]
Yes and no. There is two issues but if the first is corrected, the second will not appear anymore. 
I didn't look in the architecture of the project so I don't know if the second issue can be reached by another way.

If I have enough ether, the callback is called with no error and the transaction hash.
