### ISSUE TITLE
Unable To Install Via Chrome Web Store

### ISSUE THREAD

**Issue by beppu** [MetaMask/metamask-plugin#1070]
When I try to install MetaMask from https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn I get this message.

```
Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'.
```

![Imgur](http://i.imgur.com/BgZ9d81.png)

**Comment by kumavis** [comment]
Weird! never seen that before. thank you for filing the issue. @beppu can you provide more info like OS and Chrome version?

**Comment by kumavis** [comment]
I just tried it on a fresh chrome user, it installs fine for me.

**Comment by kumavis** [comment]
This chrome bug thread has a few references to the error message but no clear advice. https://bugs.chromium.org/p/chromium/issues/detail?id=57370

but form reading that I'm going to guess that you are on Windows with non-english locale set.

**Comment by beppu** [comment]
### OS

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

### Locale

```
LANGUAGE=en_US
LANG=en_US.UTF-8
```

Curiously, this problem has been around since 2010 without proper resolution.

https://bugs.chromium.org/p/chromium/issues/detail?id=57370

I'm going to try the workaround in comment 18 to see if that works for me.

**Comment by beppu** [comment]
Actually, I restarted Chrome and tried to install it again, and now it installed cleanly.  That's good enough for me.

Thank you for your help, and thank you for writing this Chrome extension and saving me from having to download the entire Ethereum blockchain.
