### ISSUE TITLE
Attempts to retrieve currency pair with undefined

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#1072]
https://www.cryptonator.com/api/ticker/eth-undefined

**Comment by flyswatter** [comment]
But how did you get here?

**Comment by kumavis** [comment]
idk, app started that way
strange as i dont think i touched any relevant code

**Comment by Zanibas** [comment]
Re-open this if this behavior appears again, it doesn't look like we've run into this one in awhile.
