### ISSUE TITLE
metamask transaction stuck on pending-- link to "Ethereum Tx Replay" does nothing?

### ISSUE THREAD

**Issue by ColinLeath** [MetaMask/metamask-plugin#1080]
bug report at MakerDAO:
https://waffle.io/MakerDAO/maker-market/cards/5892a433ac7ef028002a261d

there's a "..." next to the transaction. Clicking that links here:
https://metamask.github.io/eth-tx-viz/?tx=0x4081b5e25c176442dceaffd0e1718ef53a79e57718003a2f42ddb7db47af7ef0

which just says:
loading. . .

**Comment by kumavis** [comment]
Theres an error "no transaction found". We don't render this error to the screen yet.
I don't see your tx on ropsten or mainnet
https://ropsten.io/tx/0x4081b5e25c176442dceaffd0e1718ef53a79e57718003a2f42ddb7db47af7ef0
https://etherscan.io/tx/0x4081b5e25c176442dceaffd0e1718ef53a79e57718003a2f42ddb7db47af7ef0

did you sign this tx with metamask?
what is your network / rpc provider?
do you use the same address from multiple clients?

**Comment by kumavis** [comment]
related to https://github.com/makerdao/maker-market/issues/161

**Comment by ColinLeath** [comment]
I imported my account into a new browser this morning and was able to set the allowance.
I initially wasn't able to set the allowance because I didn't have ether in the account to pay for the transaction. After adding more ether, I tried to set the allowance again and that was when it got stuck on pending.
