### ISSUE TITLE
You should not have to login to change the network id

### ISSUE THREAD

**Issue by rolandkofler** [MetaMask/metamask-plugin#1089]
Example given:
- User deploys contract in Remix
- Metamask opens
- User discovers he is on mainnet but wants to use testnet.
- User has to login to mainnet 
- then change to testnet
- then deploy contract
- then login on testnet

Should:

- User changes nets, without first login ( changing a net doesn't require login)

Rationale: while converting the transaction pending to suite another net is certainly asking too much, loggin-in to only changing the net is asking too much to the poor developer.   
I understand that the normal user doesn't need this feature, but a good part currently must be developers...

**Comment by flyswatter** [comment]
Could be solved in two ways:
1. (short term) Add the network menu to the locked screen.
2. (long term) We are going to have log-in per-domain, so users will be forced to choose a network when connecting to a site. (Still in progress on what that will look like)

**Comment by Zanibas** [comment]
@flyswatter do you want to be able to change networks from the unlock screen, or just check what network you're on?

**Comment by kumavis** [comment]
@Zanibas change networks. Should just show the normal app bar but without the sandwhich menu on the right
