### ISSUE TITLE
MetaMask cant calculate gas when calling "Suicide"

### ISSUE THREAD

**Issue by Shultzi** [MetaMask/metamask-plugin#1095]
Well, it's quite straightforward.  When using suicide, metamask can't calculate gas and fees.
I can still use metamask to kill a contract by manually declaring gas price.

Edit: Manually declaring gas price using web3.js.

**Comment by flyswatter** [comment]
Are you using testrpc by any chance?  We just pass estimateGas through to the underlying RPC, usually Parity.
