### ISSUE TITLE
web3.network.getVersion returns '' when on bad RPC

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1096]
Probably because it hits a cache we have?  It should just return an error.

**Comment by flyswatter** [comment]
This happens when you point at a non-RPC endpoint.

**Comment by Zanibas** [comment]
Attempting to reproduce, but it seems that I'm stuck on loading, thus I never get a response back to my callback.

**Comment by Zanibas** [comment]
May I ask how you'd point at a port without a server and the app resolving to not be "loading"?
