### ISSUE TITLE
eth.sign shows useless hex data instead of message

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1100]
Should at least show the data to be signed, before it's been hashed & prefixed.

**Comment by Manidos** [comment]
Just to be clear, does `eth.sign()` work or it's just me who experiences some problems?

**Comment by chafey** [comment]
In many cases, the actual message being signed will not be understandable by the user.  There should be an option for the user to view the message "Details" if they want, but the main message displayed to the user should be supplied by the app when signing is requested.  My logic here is that the end user needs to "trust" the app they are using in the first place, if they don't, they should not sign.  The app should be able to have some control over the signing UI thought to ensure a good UX.  There should be a portion of the signing UI that is app controlled and another which is metamask controlled (e.g. sign, cancel buttons, a warning message).  Having the app supply a string would be a good first step, supplying HTML would be even better!

**Comment by chafey** [comment]
Can you provide more info about this being closed?  Is it closed "never going to fix", "not a bug" or "another solution pending"?

**Comment by kumavis** [comment]
@chafey the arguments for `eth_sign` as we implement are `[address, hash]` and there is no human meaningful way to display a hash, so there is no solution here. We are deprecating `eth_sign` in favor of `personal_sign` as `[address, msgHex]` which will allow us to display a human readable version.

https://github.com/MetaMask/metamask-plugin/pull/1177
https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_sign
https://github.com/ethereum/web3.js/issues/562

**Comment by chafey** [comment]
Displaying a hash is nonsensical.  As an app developer, I would really like to have the ability to customize the confirmation windows in some way to help users through the process.  I hope this can be considered

**Comment by chafey** [comment]
ignore this, I'll chime in on #1177

**Comment by flyswatter** [comment]
@chafey I'm not sure you looked at the linked info:

https://github.com/MetaMask/metamask-plugin/pull/1177

**Comment by flyswatter** [comment]
@chafey you should also be interested in:
https://github.com/MetaMask/metamask-plugin/issues/925
