### ISSUE TITLE
Some users reporting suddenly mis-generated accounts after 3.2.0

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1103]
> Is anyone experiencing the latest MetaMask losing accounts? I’m running 3.2.1 in Chrome stable. It’s like it ‘forgets’ my seed words and then switches to another set.

**Comment by danielnovy** [comment]
Just happened to me as well! Also, Gabriel Barros reported it happened to him. My version is 3.2.2.

**Comment by gbarros** [comment]
yup.

**Comment by flyswatter** [comment]
Open question to those who have experienced this:

How long have you been using MetaMask?
If you have experienced this with a set of test seed words, and could donate those seed words to us, we might be able to replicate more easily.

We haven't internally reproduced this issue, so right now the recommendation is to reinstall, and I hope you kept your seed words safe!

**Comment by flyswatter** [comment]
@danielnovy @gbarros is this still an issue?

**Comment by flyswatter** [comment]
May be fixed when we complete #1181

**Comment by flyswatter** [comment]
Closing for now, let us know if this returns!
