### ISSUE TITLE
Review & harden gas buffering code

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1118]
The melonport ICO seemed to suggest that our gas estimation buffer is maybe inadequate.

While we also need to add manual gas controls to the tx approval screen, it's also strange that our estimates seemed to be so close to the final cost, leading to a lot of "barely OOG" errors.

**Comment by kumavis** [comment]
Its important to note that **gas requirements may be higher in the middle** of processing transaction than the total gas used at the end of the transaction. This is because **large chunks of gas can be reserved** when making calls to other contracts, **the unused portion of which is returned** after the call completes.

**Comment by kumavis** [comment]
parity's`eth_estimateGas` seems to just return the gas used at the end

**Comment by flyswatter** [comment]
Ahh, but we really want `eth_estimateMaxGasMoment`!

**Comment by flyswatter** [comment]
We could aim for "would have succeeded during the melonport crowdsale", since that was a high-gas-bid-war.

[a successful tx](https://etherscan.io/tx/0x94f257d09ccda669ad7466a3abd6c63ee57a4b6b7b577b523d45223bfda9c2f2) cost `4031568` gas.
[a failed tx](https://etherscan.io/tx/0x9cfa0fa57817c19dbcac3ce3aabd1ac57cda82a8d219425898c91f2b3276aa8b) tried to only pay `79034` gas.

The difference is 3,952,534, which is a lot of gas, worth about `$0.18` today.

**Comment by kumavis** [comment]
bad:    `079034`
good:  `100000`

thats 26.5% over the reported `eth_estimateGas`
so i would just buffer @ 1.5x
then make sure we dont hit the block gas limit

**Comment by kumavis** [comment]
I think `4031568` is the current block gas limit
