### ISSUE TITLE
Account not listed as "loose"

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#1122]
![image](https://cloud.githubusercontent.com/assets/1474978/23000626/3a62af82-f396-11e6-9ba7-310b4baeb94b.png)

**Comment by kumavis** [comment]
not in list either
![image](https://cloud.githubusercontent.com/assets/1474978/23000770/da64a3dc-f396-11e6-8fb3-41700d00a8ec.png)

**Comment by Zanibas** [comment]
Fixed
