### ISSUE TITLE
ERR_FILE_NOT_FOUND when clicking on extension.

### ISSUE THREAD

**Issue by Idealist42** [MetaMask/metamask-plugin#1141]
The icon has turned into a generic "puzzle piece", and when clicked, it says "your file was not found.  it may have been moved or deleted.  ERR_FILE_NOT_FOUND"

I do have a utility called "Cookie" installed that deletes cookies when I quit my browser, so maybe that deleted something?

![screen shot 2017-02-20 at 2 56 53 pm](https://cloud.githubusercontent.com/assets/6912719/23144778/d5627c56-f77e-11e6-86f3-4952369e5bfd.png)

**Comment by flyswatter** [comment]
We also just published an update for MetaMask, so my first concern is that we published a mistake.

Could you right-click the puzzle icon, and check what version metamask is listed as?

**Comment by Idealist42** [comment]
It says 3.2.2 in the extensions list in chrome.

**Comment by flyswatter** [comment]
Ok phew, that relieves my initial fear.

This looks a lot like something deleted a chrome extension file.  You might have to remove & reinstall metamask to fix it.  I haven't seen this before, and would be surprised if metamask did this to itself.

**Comment by Idealist42** [comment]
I have a feeling it was the Cookie utility(https://cookie5app.com/) that deleted the file.  None of my other browser extensions are affected by it though.  Is there a way to protect the files from utilities like these?

**Comment by flyswatter** [comment]
I don't know anything about that utility, so I can't say.  The best solution would be to report it to them.  If you're giving them root access, they will be able to delete whatever files they want to.  I'd be concerned about messing with internal chrome permissions though, seems like it could break parts of Chrome.

Closing for now, let us know if this seems to be our fault for some reason.
