### ISSUE TITLE
Accept/Reject dialog should not go full screen in MacOS Fullscreen Chrome Tab

### ISSUE THREAD

**Issue by drcode** [MetaMask/metamask-plugin#1145]
Current Behavior:

When using chrome full screen & executing web3 transaction trigger a MetaMask accept/reject dialog by creating a transaction. On MacOS, the accept/reject dialog will be full screen, forcing MacOS to switch "workspaces" by sliding the entire screen to the left. The entire screen slides back after the transaction is accepted/rejected. This is disorienting and slow, due to the animations involved, and causes a CPU spike due to triggering the MacOS workspace switching mechanism.

Desired Behavior:

The accept/reject dialog should appear as some incarnation of "popup" style window that does not affect the main browser tab. (At the very minimum, you could probably commandeer the MetaMask address bar popup window as a makeshift dialog, as this already operates in the desired "pop-up" fashion)

Software used:
MacOS 10.12.2
Chrome 56.0.2924.76 (64-bit)

**Comment by drcode** [comment]
Duplicate of #634

**Comment by Zanibas** [comment]
Yeah, we just showed some people this quirk today! Sucks because you can't "close" out of that window

**Comment by flyswatter** [comment]
Unfortunately we can't open the normal popup programmatically, so our current projected solution is to probably move the confirmation view from any kind of popup to a simple new tab that navigates back when complete.

**Comment by drcode** [comment]
@flyswatter Annoying they don't let you do that- I guess the same thing that makes extensions so great (i.e. aggressive sandboxing) also makes it inconvenient for some UI scenarios.

**Comment by flyswatter** [comment]
Yes, some parts of the extension API are more reliable than others, and we've been learning a lot about which ones ;)
