### ISSUE TITLE
Metamask cannot unlock

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-plugin#1151]
I came back from a 20 days trip and on my return today, I cannot unlock metamask with the correct password, I get the following error : 
```Cannot unlock without a previous vault.```

Before that I had to accept some new policy or something (did not have time to read it).

**Comment by flyswatter** [comment]
Hi @wighawag, looks like you've found a pretty rare bug, sorry about that!

While you were away, we've changed our vault storage format.

We successfully migrated most of our users to the new format, but it seems like over the last 20 days, some part of that process has broken.

If you have your seed phrase backed up, you should find that uninstalling & reinstalling solves your issue.

If you do not have your seed phrase backed up, I'm willing to go to some special lengths for you, but I'll need you to be slightly patient, I won't be able to give it good focus until tomorrow afternoon (in about 20 hours).

Sorry again for the trouble.

**Comment by wighawag** [comment]
Hi @flyswatter 
I am not sure it is that rare. I have 2 chrome instance (canary and normal) and both had the issue.

For both case I had the backup key so no worries on my end.

**Comment by flyswatter** [comment]
It's as rare as your vacation, so it makes sense both of your computers would be affected. Most of our users have signed in more recently. It seems the migration bug was recently introduced.

**Comment by wighawag** [comment]
ok

**Comment by kumavis** [comment]
The fix was a reinstall. This issue was bc of a faulty migration. sorry 😿

**Comment by ncoonrod** [comment]
Unfortunately I seem to be having this same issue as well, and I did not back up my seed phrase. What would you suggest?

**Comment by ncoonrod** [comment]
@flyswatter

**Comment by flyswatter** [comment]
@ncoonrod I recommend opening a ticket on our new support system, so we can help you privately:
https://consensyssupport.happyfox.com/home

**Comment by ncoonrod** [comment]
@flyswatter I can't submit tickets there. It won't let me :(

**Comment by flyswatter** [comment]
Sorry, maybe try support.metamask.io the `Submit Ticket` button in the top right?
