### ISSUE TITLE
Switching between custom RPCs not working properly

### ISSUE THREAD

**Issue by arkoe** [MetaMask/metamask-plugin#1153]
I have been using MetaMask to test my dApp on a Ubuntu VPS (Custom RPC). Now I have set up a new VPS and I changed the Custom RPC IP address in my Metamask to the new IP and port. However, it lists my old wallets I had on the previous VPS. Whenever I create a new wallet, and I list the accounts on my geth console (web3.eth.accounts) it tells me 'null'.

What am I missing?

**Comment by flyswatter** [comment]
MetaMask does not create accounts on your geth instance, it holds private keys in its own process.  It creates a geth-like `web3` object in your Chrome browser context.
