### ISSUE TITLE
personal_ecRecover not recovering correctly

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1159]
My computer isn't even getting it to call back right now, so that's one bug, but another is that @kumavis and @Zanibas have reported it calling back, but not recovering correctly.

This issue represents fixing that, so the output of `personal_sign` can produce the signer's address by using `personal_ecRecover` with the original message.

**Comment by flyswatter** [comment]
We should try to match geth.

We're using: https://github.com/flyswatter/eth-sig-util/

You can validate in browser here:
https://github.com/flyswatter/js-eth-personal-sign-examples

**Comment by kumavis** [comment]
This works for me on master after web3-provider-engine@10 : )
