### ISSUE TITLE
Personal_sign functionality not working for loose accounts

### ISSUE THREAD

**Issue by blmalone** [MetaMask/metamask-plugin#1162]
This issue is in relation to the functionality added in [this](https://github.com/MetaMask/metamask-plugin/pull/1149) merge. 

This was performed on the Ropsten Test Net.

### *Steps to recreate*
* Create an account, this will be the 'loose' account, (I used [myetherwallet](https://www.myetherwallet.com/))
* I imported the JSON file that was generated to my vault and selected this account to use.
* Opened the live [demo](https://flyswatter.github.io/js-eth-personal-sign-examples/) for the js-eth-personal-sign-examples.
* Clicked on the `personal_sign` button and a window appeared like so...
![screen shot 2017-03-02 at 01 11 53](https://cloud.githubusercontent.com/assets/15608778/23488551/44506304-fee5-11e6-8e37-b22292852d72.png)
* Clicked `sign`, only to be shown a permanent blank screen. I inspected the console to see what had been logged. The following was shown: 

![screen shot 2017-03-02 at 00 27 08](https://cloud.githubusercontent.com/assets/15608778/23488596/9aef1cdc-fee5-11e6-9f60-dd0bf36e7a2e.png)

Runtime variables where error is shown : 
![screen shot 2017-03-02 at 01 19 15](https://cloud.githubusercontent.com/assets/15608778/23488737/69923f2e-fee6-11e6-822b-36044900f13e.png)

* Clicking the `person_sign` button a second time while the blank screen is still open will show:
`< div class="error" style="margin: auto;">keyring.signPersonalMessage is not a function</div >`
in the new window.

**Comment by flyswatter** [comment]
Thanks for the great screenshot of logs, I was able to find the problem very quickly. If you run this command, it should fix your local signing:
`rm -rf node_modules/eth_simple_keyring && npm i`
