### ISSUE TITLE
getTransactionReceipt does not seem to return an object with the blockhash/blockNumber set anymore even if the tx has been mined

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-plugin#1163]
getTransactionReceipt does not seem to return an object with the blockhash/blockNumber set anymore even if the tx has been mined (according to etherscan)

I use this method to check whether the tx has been mined by repetitively calling it.

This call always return an object but that object never have its blockhas/blocknumber set even if I can see the tx mined in etherscan

**Comment by wighawag** [comment]
This was on the testnet,

on the mainnet this seems different, I get a null receipt here instead but did not see yet whether when it is not null I get a receipt without blochash/blocknumber

There is a disparity on geth/parity in regard to the value returned by both. geth return a null receipt until the transaction is mined. while parity always return a receipt but the blochash/blocknumber are undefined until the tx is mined

Do you different client for testnet/mainnet ?

Any related change in the last 20 days or maybe beyond?

**Comment by wighawag** [comment]
I just realized that on the testnet case I had an adblocker running (uBlock origin) Could this be an issue ?

**Comment by kumavis** [comment]
I use uBlock origin as well - shouldn't be an issue. additionally, we make our http requests from the extension and uBlock does not have access there.

**Comment by wighawag** [comment]
Yes, makes sense. I actually still get the issue without uBlock. 
We also had at least one player (on the mainnet) reporting an issue whose cause is likely this issue.

Myself I can see it on the testnet almost all the time

**Comment by kumavis** [comment]
we perma cache `getTransactionReceipt`, I think previously there was no result for `getTransactionReceipt` before it was mined, but now there is and we are caching it before it has the block reference
https://github.com/MetaMask/provider-engine/blob/master/subproviders/cache.js

**Comment by wighawag** [comment]
Ok, this is quite serious then, any ETA ?

As mentioned , there is disparity between parity and geth on that rpc method

see https://github.com/ethcore/parity/issues/3569 and https://github.com/ethereum/go-ethereum/issues/3323

**Comment by flyswatter** [comment]
These are the result of bugs we reported, I guess we could have foreseen.

https://github.com/ethcore/parity/issues/3939
https://github.com/ethereum/go-ethereum/issues/3483

I've opened [an issue on web3-provider-engine](https://github.com/MetaMask/provider-engine/issues/121) too, I think we can try to fix this in this week's release, or otherwise very soon.

**Comment by wighawag** [comment]
Thanks for the info and your quick response

**Comment by kumavis** [comment]
fixed in web3-provider-engine@10.0.1
