### ISSUE TITLE
add api to access the name of the current account

### ISSUE THREAD

**Issue by chafey** [MetaMask/metamask-plugin#1167]
It would be great if there was an api to access the name of the current metamask account so it could be displayed to the user in the Dapp.  I would be willing to submit a PR if the team approves this feature request and provides guidance about the api design.  Is there a metamask specific namespace yet?

**Comment by flyswatter** [comment]
Unless we make it very obvious to the user that their name is public (like registering a reverse-resolvable ENS name would be), this could violate privacy.

- Dan

**Comment by chafey** [comment]
Good point, didn't think of that.  If metamask could support opt-in integration with ENS and a user profile smart contract it would probably be better.  Closing
