### ISSUE TITLE
Custom chain not an option until after login.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-plugin#1206]
MetaMask 3.4.0, chrome latest stable.

When I open MetaMask plugin, I see a password prompt by default.  If I click on the network in the top left, it will show me 3 choices:
1. Main Ethereum Network
2. Ropsten Test Network
3. Localhost 8545

Once I have entered my password, clicking on the same area gives me 4 options:
1. Main Ethereum Network
2. Ropsten Test Network
3. Localhost 8545
4. Custom RPC

It doesn't make sense that I need to login before I can choose a custom network.  I suspect this is a bug?  If this is intentional the UI should be improved as I just spent the last week thinking `localhost 8545` was the only option until someone told me otherwise.

**Comment by flyswatter** [comment]
Thanks for the catch, will fix soon!
