### ISSUE TITLE
Currency settings are not retained

### ISSUE THREAD

**Issue by NicolasMassart** [MetaMask/metamask-plugin#1211]
When I change currencies settings to EUR 
![image](https://cloud.githubusercontent.com/assets/4677568/23926519/eb8bb126-0914-11e7-8f5d-317f1801d3fd.png)
and go back to my account screen, it shows ETH/EUR.
![image](https://cloud.githubusercontent.com/assets/4677568/23926539/0be3ed76-0915-11e7-819b-2e72d20015bd.png)
 But if I close the metamask window and open it again ETH/USD is back.
![image](https://cloud.githubusercontent.com/assets/4677568/23926528/fe616be2-0914-11e7-8a3e-840c77c32259.png)

Metamask 3.4.0 on OSX Chrome Version 56.0.2924.87 (64-bit)

**Comment by Zanibas** [comment]
Just a bad case of not renaming variables--fixed!

**Comment by Zanibas** [comment]
Verified that it's fixed in production.
