### ISSUE TITLE
Official 'Pay with MetaMask' button

### ISSUE THREAD

**Issue by morelazers** [MetaMask/metamask-plugin#1219]
Hey guys, a few friends and I created a WooCommerce plugin/extension for paying with Ether, I messaged @flyswatter about it and he mentioned to post here to get an official button.

Here's what we're currently using:
![image](https://cloud.githubusercontent.com/assets/2966123/24113813/e1ffc77a-0d95-11e7-98d8-7cacfafc11e5.png)

Cheers!

**Comment by flyswatter** [comment]
@VladTod could you design this?

**Comment by VladTod** [comment]
I'll get a few designs together tomorrow
