### ISSUE TITLE
Nonce / Gas price issue

### ISSUE THREAD

**Issue by traviagio** [MetaMask/metamask-plugin#1221]
I played around with WEI values while using Metamask in MKR.Market. Not I can't get any transaction across. I tried on a new browser with a fresh Metamask install. Still doesn't work.

I am getting: popup.js:84760 Transaction gas price is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.

**Comment by flyswatter** [comment]
Maybe related to #1127.

Could you send us some [UI state logs](https://github.com/MetaMask/faq/blob/master/LOGS.md#ui-state-logs-chrome)?

They have some info about your account, so you may want to send those logs in private.

**Comment by traviagio** [comment]
{
  "metamask": {
    "isInitialized": true,
    "isUnlocked": true,
    "rpcTarget": "https://rawtestrpc.metamask.io/",
    "identities": {
      "0x6595732468a241312bc307f327ba0d64f02b3c20": {
        "address": "0x6595732468a241312bc307f327ba0d64f02b3c20",
        "name": "Account 1"
      }
    },
    "unapprovedTxs": {},
    "currentFiat": "USD",
    "conversionRate": 43.33256249,
    "conversionDate": 1490036823,
    "noActiveNotices": true,
    "frequentRpcList": [],
    "network": "1",
    "accounts": {
      "0x6595732468a241312bc307f327ba0d64f02b3c20": {
        "code": "0x",
        "nonce": "0x3b",
        "balance": "0x1accc1f6598cbf58",
        "address": "0x6595732468a241312bc307f327ba0d64f02b3c20"
      }
    },
    "transactions": {},
    "selectedAddressTxList": [
      {
        "id": 1831620629568200,
        "time": 1490035808784,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde800000000000000000000000000000000000000000000000000000000000003550000000000000000000000000000000000000000000000000429d069189e0000",
          "gas": "0xf4240",
          "metamaskId": 1831620629568200,
          "metamaskNetworkId": "1",
          "gasPrice": "0x04a817c800",
          "nonce": "0x3d",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "470de4df820000",
        "txValue": "0",
        "maxCost": "470de4df820000",
        "gasPrice": "4a817c800"
      },
      {
        "id": 1831620629568201,
        "time": 1490035928391,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc66ea802717bfb9833400264dd12c2bceaa34a6d",
          "data": "0x095ea7b3000000000000000000000000c350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f00000000000000000000000000000000000000000000152cf4e72a974f1c0000",
          "gas": "0x249f0",
          "metamaskId": 1831620629568201,
          "metamaskNetworkId": "1",
          "gasPrice": "0x04a817c80c",
          "nonce": "0x3d",
          "gasLimit": "0x249f0"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0x249f0",
        "txFee": "0xaa87bee6ef740",
        "txValue": "0",
        "maxCost": "0xaa87bee6ef740",
        "gasPrice": "4a817c800"
      },
      {
        "id": 1831620629568202,
        "time": 1490035967509,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc66ea802717bfb9833400264dd12c2bceaa34a6d",
          "data": "0x095ea7b3000000000000000000000000c350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f00000000000000000000000000000000000000000000152cf4e72a974f1c0000",
          "gas": "0x249f0",
          "metamaskId": 1831620629568202,
          "metamaskNetworkId": "1",
          "gasPrice": "0x052c8c338e",
          "nonce": "0x3d",
          "gasLimit": "0x249f0"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0x249f0",
        "txFee": "0xbd7a6253fd320",
        "txValue": "0",
        "maxCost": "0xbd7a6253fd320",
        "gasPrice": "4a817c800"
      },
      {
        "id": 1831620629568203,
        "time": 1490036232838,
        "status": "rejected",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc66ea802717bfb9833400264dd12c2bceaa34a6d",
          "data": "0x095ea7b3000000000000000000000000c350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f00000000000000000000000000000000000000000000152cf4e72a974f1c0000",
          "gas": "0x249f0",
          "metamaskId": 1831620629568203,
          "metamaskNetworkId": "1"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0x249f0",
        "txFee": "aa87bee538000",
        "txValue": "0",
        "maxCost": "aa87bee538000",
        "gasPrice": "4a817c800"
      },
      {
        "id": 1831620629568204,
        "time": 1490037324293,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde8000000000000000000000000000000000000000000000000000000000000035500000000000000000000000000000000000000000000000002c68af0bb140000",
          "gas": "0xf4240",
          "metamaskId": 1831620629568204,
          "metamaskNetworkId": "1",
          "gasPrice": "0x48d9a18e",
          "nonce": "0x3d",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "0x4579ac960ff80",
        "txValue": "0",
        "maxCost": "0x4579ac960ff80",
        "gasPrice": "4a817c800"
      }
    ],
    "unapprovedMsgs": {},
    "unapprovedMsgCount": 0,
    "unapprovedPersonalMsgs": {},
    "unapprovedPersonalMsgCount": 0,
    "keyringTypes": [
      "Simple Key Pair",
      "HD Key Tree"
    ],
    "keyrings": [
      {
        "type": "HD Key Tree",
        "accounts": [
          "6595732468a241312bc307f327ba0d64f02b3c20"
        ]
      }
    ],
    "selectedAddress": "0x6595732468a241312bc307f327ba0d64f02b3c20",
    "currentCurrency": "USD",
    "provider": {
      "type": "mainnet"
    },
    "shapeShiftTxList": [],
    "lostAccounts": []
  },
  "appState": {
    "menuOpen": false,
    "currentView": {
      "name": "confTx",
      "errorMessage": "There was a problem submitting this transaction."
    },
    "accountDetail": {
      "subview": "transactions"
    },
    "transForward": true,
    "isLoading": false,
    "warning": null
  },
  "identities": {}
}
undefined

**Comment by flyswatter** [comment]
In that state, we can see your account nonce is `0x3b` (59) but all the transactions were attempted (and failed) at `0x3d` (61).

This suggests that somehow our nonce tracker is skipping the correct nonce, and getting stuck at once nonce over.

In the short term, I think you should be able to uninstall & reinstall metamask to get this working, @traviagio, but you also told me you installed MetaMask on a separate computer, and had the same problem, is that true?

If so, could you post the UI state from that computer too, so we could confirm the same nonce tracking problem is happening on a separate metamask installation?

**Comment by traviagio** [comment]
{
  "metamask": {
    "isInitialized": true,
    "isUnlocked": true,
    "rpcTarget": "https://rawtestrpc.metamask.io/",
    "identities": {
      "0x6595732468a241312bc307f327ba0d64f02b3c20": {
        "address": "0x6595732468a241312bc307f327ba0d64f02b3c20",
        "name": "Account 1"
      }
    },
    "unapprovedTxs": {},
    "currentFiat": "USD",
    "conversionRate": 42.72349306,
    "conversionDate": 1490050261,
    "noActiveNotices": true,
    "frequentRpcList": [],
    "network": "1",
    "accounts": {
      "0x6595732468a241312bc307f327ba0d64f02b3c20": {
        "code": "0x",
        "balance": "0x1accc1f6598cbf58",
        "nonce": "0x3b",
        "address": "0x6595732468a241312bc307f327ba0d64f02b3c20"
      }
    },
    "transactions": {},
    "selectedAddressTxList": [
      {
        "id": 878987126049382,
        "time": 1490049802725,
        "status": "submitted",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde80000000000000000000000000000000000000000000000000000000000000363000000000000000000000000000000000000000000000000016345785d8a0000",
          "gas": "0xf4240",
          "metamaskId": 878987126049382,
          "metamaskNetworkId": "1",
          "nonce": "0x3f",
          "gasPrice": "0x04a817c800",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "470de4df820000",
        "txValue": "0",
        "maxCost": "470de4df820000",
        "gasPrice": "4a817c800",
        "hash": "0xda2dc513c04fe4fe5d84e2a81fc0e7878c456ae2d3f70131c61038277dffbd86"
      },
      {
        "id": 878987126049383,
        "time": 1490050080932,
        "status": "submitted",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde80000000000000000000000000000000000000000000000000000000000000363000000000000000000000000000000000000000000000000016345785d8a0000",
          "gas": "0xf4240",
          "metamaskId": 878987126049383,
          "metamaskNetworkId": "1",
          "nonce": "0x40",
          "gasPrice": "0x04a817c800",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "470de4df820000",
        "txValue": "0",
        "maxCost": "470de4df820000",
        "gasPrice": "4a817c800",
        "hash": "0xab03e2cd3d153132d2bf8430834c13137c7af8d050b43725b48ff4bb44a2f8a5"
      },
      {
        "id": 878987126049384,
        "time": 1490050318637,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde80000000000000000000000000000000000000000000000000000000000000363000000000000000000000000000000000000000000000000016345785d8a0000",
          "gas": "0xf4240",
          "metamaskId": 878987126049384,
          "metamaskNetworkId": "1",
          "gasPrice": "0x77359400",
          "nonce": "0x41",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "0x71afd498d0000",
        "txValue": "0",
        "maxCost": "0x71afd498d0000",
        "gasPrice": "4a817c800"
      }
    ],
    "unapprovedMsgs": {},
    "unapprovedMsgCount": 0,
    "unapprovedPersonalMsgs": {},
    "unapprovedPersonalMsgCount": 0,
    "keyringTypes": [
      "Simple Key Pair",
      "HD Key Tree"
    ],
    "keyrings": [
      {
        "type": "HD Key Tree",
        "accounts": [
          "6595732468a241312bc307f327ba0d64f02b3c20"
        ]
      }
    ],
    "selectedAddress": "0x6595732468a241312bc307f327ba0d64f02b3c20",
    "currentCurrency": "USD",
    "provider": {
      "type": "mainnet"
    },
    "shapeShiftTxList": [],
    "lostAccounts": []
  },
  "appState": {
    "menuOpen": false,
    "currentView": {
      "name": "confTx",
      "errorMessage": "There was a problem submitting this transaction."
    },
    "accountDetail": {
      "subview": "transactions"
    },
    "transForward": true,
    "isLoading": false,
    "warning": null
  },
  "identities": {}
}
undefined

**Comment by traviagio** [comment]
This is the 2nd installation

**Comment by flyswatter** [comment]
Ok so I found what looks like the probable UI bug here (warning! dev notes!)

`state.appState.currentView.name === 'confTx'`, but that view requires at least one `state.metamask.unapprovedTx` to render.

It looks like the error made the `TransactionManger` put this into an error state, while our view was never transitioned.

On the UI dev mode, this looks like a permanent loading spinner, but I guess when the view was already loaded, it simply results in the tx details suddenly nullifying.

----------

All that said, this doesn't explain why a second computer, with a fresh installation, would get into this same failed tx state.

Since the 2nd installation only has one `failed` transaction, we can isolate it nicely:

```
{
        "id": 878987126049384,
        "time": 1490050318637,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde80000000000000000000000000000000000000000000000000000000000000363000000000000000000000000000000000000000000000000016345785d8a0000",
          "gas": "0xf4240",
          "metamaskId": 878987126049384,
          "metamaskNetworkId": "1",
          "gasPrice": "0x77359400",
          "nonce": "0x41",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "0x71afd498d0000",
        "txValue": "0",
        "maxCost": "0x71afd498d0000",
        "gasPrice": "4a817c800"
}
```

The gas and gas prices seem to work fine, just verified on ropsten.

The nonces look funny again though.

Oh, it's not the nonces.  None of those transactions are `confirmed`, they're only `submitted`.

The first installation does indeed have duplicate nonce transactions, so the error message makes sense.  I'm less able to make sense of the `unconfirmed` and `failed` transactions of the second installation.

It's late here, going to have to pick this up again tomorrow.

**Comment by flyswatter** [comment]
Ok @traviagio I think I’ve figured out a work-around for you, but to do it safely will take a couple more questions.

For some reason it seems metamask skipped a transaction nonce, and you submitted a bunch of transactions with higher nonces.  We believe by submitting a transaction with the correct (skipped) nonce, the other transactions will be mined, and your transaction counter will be corrected.  Are you familiar with the nonce in ethereum?

The simple question is:  What contract is `0xC350eBF34B6d83B64eA0ee4E39b6Ebe18F02aD2F` that all these transactions are being sent to?  Is this a token that you’re sending?

I can give you a transaction you could send from your terminal that would “unclog” all these transactions, but it looks like they may have been sent to the network, which means if we unclog them, they could all get mined in order, so if you tried to send some tokens over and over, you might end up sending those many times.

If that’s the kind of transaction you were sending, and you want to guard against that kind of replay problem, we need to construct you a transaction that will guard against those replays, which will require understanding the nature of the contract at `0xC350eBF34B6d83B64eA0ee4E39b6Ebe18F02aD2F`.

For example, if you were sending tokens over and over to someone, we are going to want you to send all those tokens to another account you control as your unclogging transaction, so that the other ones simply fail, because you have no tokens left to send.

If the transaction was simple, maybe just setting a data value, it may not matter that these transactions all get mined in order.

If you're not concerned with the repercussions of all of those failed transactions being mined, you should be able to open your chrome console and submit this transaction by pasting this code and hitting `Enter`:
```javascript
web3.eth.sendTransaction({
  "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "data": "",
  "gas": "0xf4240",
  "metamaskId": 1831620629568200,
  "metamaskNetworkId": "1",
  "gasPrice": "0x04a817c800",
  "nonce": "0x3c",
  "gasLimit": "0xf4240"
}, console.log)
```

We’re now looking a lot closer at how we manage transactions & nonces. We tried to make it easy, but while that works for 99.9% of people, it still allows some pretty awful bugs, like what you’re experiencing.

**Comment by traviagio** [comment]
As a follow up, I did the following:

1. open metamask
2. Open the provider menu in the top left
3. Go to “Custom RPC”
4. Enter `https://gmainnet.infura.io`
5. open a new browser tab at any site
6. Open the console
7. Enter that tx:

web3.eth.sendTransaction({
  "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "data": "",
  "gas": "0xf4240",
  "metamaskId": 1831620629568200,
  "metamaskNetworkId": "1",
  "gasPrice": "0x04a817c800",
  "nonce": "0x3c",
  "gasLimit": "0xf4240"
}, console.log) 


8. Approve it.

The result I got is:

null "0x736de72105df3b5a58c9208a5a3fa085fcae0f2c56f8a74ebc0dcdab553b42b1"

Then I went and did another UI state log:

{
  "metamask": {
    "isInitialized": true,
    "isUnlocked": true,
    "rpcTarget": "https://rawtestrpc.metamask.io/",
    "identities": {
      "0x6595732468a241312bc307f327ba0d64f02b3c20": {
        "address": "0x6595732468a241312bc307f327ba0d64f02b3c20",
        "name": "Account 1"
      }
    },
    "unapprovedTxs": {
      "1247716797847525": {
        "id": 1247716797847525,
        "time": 1490288590869,
        "status": "unapproved",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "data": "0x",
          "gas": "0xf4240",
          "gasPrice": "0x4a817c800",
          "nonce": "0x3c",
          "metamaskId": 1247716797847525,
          "metamaskNetworkId": "1"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "470de4df820000",
        "txValue": "0",
        "maxCost": "470de4df820000",
        "gasPrice": "4a817c800"
      }
    },
    "currentFiat": "USD",
    "conversionRate": 41.39521284,
    "conversionDate": 1490288041,
    "noActiveNotices": true,
    "frequentRpcList": [
      "https://pmainnet.infura.io",
      "https://gmainnet.infura.io"
    ],
    "network": "1",
    "accounts": {
      "0x6595732468a241312bc307f327ba0d64f02b3c20": {
        "code": "0x",
        "nonce": "0x3b",
        "balance": "0x1accc1f6598cbf58",
        "address": "0x6595732468a241312bc307f327ba0d64f02b3c20"
      }
    },
    "transactions": {},
    "selectedAddressTxList": [
      {
        "id": 878987126049382,
        "time": 1490049802725,
        "status": "submitted",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde80000000000000000000000000000000000000000000000000000000000000363000000000000000000000000000000000000000000000000016345785d8a0000",
          "gas": "0xf4240",
          "metamaskId": 878987126049382,
          "metamaskNetworkId": "1",
          "nonce": "0x3f",
          "gasPrice": "0x04a817c800",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "470de4df820000",
        "txValue": "0",
        "maxCost": "470de4df820000",
        "gasPrice": "4a817c800",
        "hash": "0xda2dc513c04fe4fe5d84e2a81fc0e7878c456ae2d3f70131c61038277dffbd86"
      },
      {
        "id": 878987126049383,
        "time": 1490050080932,
        "status": "submitted",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde80000000000000000000000000000000000000000000000000000000000000363000000000000000000000000000000000000000000000000016345785d8a0000",
          "gas": "0xf4240",
          "metamaskId": 878987126049383,
          "metamaskNetworkId": "1",
          "nonce": "0x40",
          "gasPrice": "0x04a817c800",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "470de4df820000",
        "txValue": "0",
        "maxCost": "470de4df820000",
        "gasPrice": "4a817c800",
        "hash": "0xab03e2cd3d153132d2bf8430834c13137c7af8d050b43725b48ff4bb44a2f8a5"
      },
      {
        "id": 878987126049384,
        "time": 1490050318637,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde80000000000000000000000000000000000000000000000000000000000000363000000000000000000000000000000000000000000000000016345785d8a0000",
          "gas": "0xf4240",
          "metamaskId": 878987126049384,
          "metamaskNetworkId": "1",
          "gasPrice": "0x77359400",
          "nonce": "0x41",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "0x71afd498d0000",
        "txValue": "0",
        "maxCost": "0x71afd498d0000",
        "gasPrice": "4a817c800"
      },
      {
        "id": 878987126049385,
        "time": 1490085090004,
        "status": "submitted",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0xc350ebf34b6d83b64ea0ee4e39b6ebe18f02ad2f",
          "data": "0xd6febde8000000000000000000000000000000000000000000000000000000000000039000000000000000000000000000000000000000000000000002c68af0bb140000",
          "gas": "0xf4240",
          "metamaskId": 878987126049385,
          "metamaskNetworkId": "1",
          "gasPrice": "0x0575eba603",
          "nonce": "0x41",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "0x535292f5e346c0",
        "txValue": "0",
        "maxCost": "0x535292f5e346c0",
        "gasPrice": "4a817c800",
        "hash": "0xc0edcbed42e7d3dc4dba6db3136f98ab88342315d3dc1206e6fb497542cccb09"
      },
      {
        "id": 3924109857775216,
        "time": 1490175956155,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "data": "0x",
          "gas": "0xf4240",
          "gasPrice": "0x04a817c800",
          "nonce": "0x3c",
          "metamaskId": 3924109857775216,
          "metamaskNetworkId": "1",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "470de4df820000",
        "txValue": "0",
        "maxCost": "470de4df820000",
        "gasPrice": "4a817c800"
      },
      {
        "id": 5888757947891323,
        "time": 1490266627957,
        "status": "failed",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "data": "0x",
          "gas": "0xf4240",
          "gasPrice": "0x04a817c800",
          "nonce": "0x3c",
          "metamaskId": 5888757947891323,
          "metamaskNetworkId": "1",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "470de4df820000",
        "txValue": "0",
        "maxCost": "470de4df820000",
        "gasPrice": "4a817c800"
      },
      {
        "id": 1247716797847524,
        "time": 1490288143350,
        "status": "submitted",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "data": "0x",
          "gas": "0xf4240",
          "gasPrice": "0x014a77cbbe",
          "nonce": "0x3c",
          "metamaskId": 1247716797847524,
          "metamaskNetworkId": "1",
          "gasLimit": "0xf4240"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "0x13b28a709beb80",
        "txValue": "0",
        "maxCost": "0x13b28a709beb80",
        "gasPrice": "4a817c800",
        "hash": "0x736de72105df3b5a58c9208a5a3fa085fcae0f2c56f8a74ebc0dcdab553b42b1"
      },
      {
        "id": 1247716797847525,
        "time": 1490288590869,
        "status": "unapproved",
        "metamaskNetworkId": "1",
        "txParams": {
          "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
          "data": "0x",
          "gas": "0xf4240",
          "gasPrice": "0x4a817c800",
          "nonce": "0x3c",
          "metamaskId": 1247716797847525,
          "metamaskNetworkId": "1"
        },
        "gasLimitSpecified": true,
        "estimatedGas": "0xf4240",
        "txFee": "470de4df820000",
        "txValue": "0",
        "maxCost": "470de4df820000",
        "gasPrice": "4a817c800"
      }
    ],
    "unapprovedMsgs": {},
    "unapprovedMsgCount": 0,
    "unapprovedPersonalMsgs": {},
    "unapprovedPersonalMsgCount": 0,
    "keyringTypes": [
      "Simple Key Pair",
      "HD Key Tree"
    ],
    "keyrings": [
      {
        "type": "HD Key Tree",
        "accounts": [
          "6595732468a241312bc307f327ba0d64f02b3c20"
        ]
      }
    ],
    "selectedAddress": "0x6595732468a241312bc307f327ba0d64f02b3c20",
    "currentCurrency": "USD",
    "provider": {
      "type": "rpc",
      "rpcTarget": "https://gmainnet.infura.io"
    },
    "shapeShiftTxList": [],
    "lostAccounts": []
  },
  "appState": {
    "menuOpen": false,
    "currentView": {
      "name": "confTx",
      "context": 0
    },
    "accountDetail": {
      "subview": "transactions"
    },
    "transForward": true,
    "isLoading": false,
    "warning": null
  },
  "identities": {}
}

**Comment by flyswatter** [comment]
My bad, looks like I gave you a tx with a really low gas value, so it may have re-created the same problem.  We need to flush our tx queue and then you can try again, with a higher gas value, like:

```
web3.eth.sendTransaction({
  "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "data": "",
  "gas": "0x4a817c800",
  "metamaskId": 1831620629568200,
  "metamaskNetworkId": "1",
  "gasPrice": "0x04a817c800",
  "nonce": "0x3c",
  "gasLimit": "0xf4240"
}, console.log) 
```

**Comment by flyswatter** [comment]
Apparently [parity does permit resubmitting a tx with a higher gas price](https://github.com/paritytech/parity/issues/5010), we just need better tx managing UI to allow that.

In the meanwhile, @traviagio you should be able to connect to our `Main Network` provider menu item, and submit a tx with a higher gas, like:
```
web3.eth.sendTransaction({
  "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "data": "",
  "gas": "0x4a817c900",
  "metamaskId": 1831620629568200,
  "metamaskNetworkId": "1",
  "gasPrice": "0x04a817c800",
  "nonce": "0x3c",
  "gasLimit": "0xf4240"
}, console.log) 
```

**Comment by tomusdrw** [comment]
@flyswatter @traviagio it should actually be `gasPrice`, not `gas` (also note that `gasLimit` is ignored by `web3` afaik: https://github.com/ethereum/wiki/wiki/JavaScript-API#parameters-24
So the call should look like this:
```js
web3.eth.sendTransaction({
  "from": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "to": "0x6595732468a241312bc307f327ba0d64f02b3c20",
  "data": "",
  "gas": "0xf4240", // This can stay the same
  "metamaskId": 1831620629568200,
  "metamaskNetworkId": "1",
  "gasPrice": "0x04a817c801", // This is increased 
  "nonce": "0x3c",
//  "gasLimit": "0xf4240" // That's not needed
}, console.log) 
```

**Comment by flyswatter** [comment]
This ultimately worked (the general strategy of submitting a higher gas tx with the correct nonce), and unclogged the client.  All the pending txs then went through.

In the future, if we want to avoid "all the bad txs going through", we either:

- Need clients to add support for removing pending txs
- Compose txs with matching nonces for all the pending txs, and maybe actually submit them to the node in reverse order, so that none of them can run until the final (first) tx is corrected.
