### ISSUE TITLE
Make MetaMask inject in iFrames

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1223]
Is this possible?

**Comment by flyswatter** [comment]
Submitted by `@kflurkel` on our slack.

**Comment by kingflurkel** [comment]
thanks for looking into it!

**Comment by kingflurkel** [comment]
Could it be as simple as setting this to true?

https://github.com/MetaMask/metamask-plugin/blob/master/app/manifest.json#L54

**Comment by flyswatter** [comment]
Maybe...!

**Comment by kingflurkel** [comment]
Any news?

**Comment by frankiebee** [comment]
Just posted are first transaction yesterday!

**Comment by kumavis** [comment]
oh - i understand this issue now : )
https://github.com/MetaMask/metamask-plugin/pull/1259
