### ISSUE TITLE
Chrome crashes everytime I try to change the testnet

### ISSUE THREAD

**Issue by ratio91** [MetaMask/metamask-plugin#1224]
Once I click on a different testnet than the default one, Chrome instantly chrashes...
Using Version 57.0.2987.110 (64-bit)

**Comment by Zanibas** [comment]
Tested our current public build under:
```
Google Chrome	57.0.2987.110 (Official Build) (64-bit)
Revision	11f66db67ea1f20d200d6f9add50fc1c345d71f7-refs/branch-heads/2987@{#832}
OS	Linux 
JavaScript	V8 5.7.492.65
```
could not reproduce. Could someone using Mac or Windows please check on their end?
@ratio91 could you provide any other details concerning your MetaMask? Have you been using it for awhile or is it a fresh install?

**Comment by ratio91** [comment]
alrights, thanks for the answer.
issue solved after Metamask re-install (old version was from last week though)
