### ISSUE TITLE
Recalculate gas cost when manually adjusting

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/metamask-plugin#1230]
My initial gas cost was too high (I'm using browse solidity which auto sets it to the block limit). I tried manually adjusting downward, but the gas cost does not update.

https://ipfs.pics/QmayWCTeg6hRs19JESCmsZeTgBf23yFmds8MSkjDH5S4Z7

Max total is $0.98, and I have $2 in my account, but it won't let me submit the transaction

**Comment by flyswatter** [comment]
![](https://ipfs.pics/ipfs/QmayWCTeg6hRs19JESCmsZeTgBf23yFmds8MSkjDH5S4Z7)
