### ISSUE TITLE
Set hard lower limit for gas price

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1234]
The cause of #1229 was that an early tx had a very low gas price set, and infura accepted it, but no miners did, and then all subsequent transactions had nonces incremented behind that transaction, essentially being blocked by it.

Could be easily fixed by enforcing hard lower limits for gas price.  Investigating valid values now.

**Comment by flyswatter** [comment]
Sounds like this may also be the cause of #1221!

**Comment by flyswatter** [comment]
Our gas fields use html `input` elements of `number` type, which itself has `max` and `min` attributes, which *should* warn the user on form submission, like this:

![screen shot 2017-03-21 at 5 23 57 pm](https://cloud.githubusercontent.com/assets/542863/24176762/51914990-0e5b-11e7-8650-38911460ea2e.png)

Unfortunately, this doesn't seem to be working within react for some reason.

We might have to come up with some kind of custom solution to restricting the `input` range.

**Comment by flyswatter** [comment]
Some options for how to restrict the input range:

- Continue researching ways to get the correct default behavior to work.
- Force the value within the range when clicking outside of it (`onBlur`).
- Do some fancy user-input-manipulation code out from under their cursor (scary, annoying).
- Validate at another layer, display it as a normal tx submission error.

Other approaches?

**Comment by kumavis** [comment]
maybe try these ?
https://github.com/vlad-ignatov/react-numeric-input
https://github.com/hongymagic/react-number-input

**Comment by Zanibas** [comment]
I want to know how http://ethgasstation.info/index.php got their gas price estimates. This way, we can emulate their behavior and set an appropriate lower limit.

@flyswatter I'm fairly sure the reason why those validations don't work on our end is because those inputs are attached to a form element in that example.

**Comment by Zanibas** [comment]
@flyswatter http://stackoverflow.com/questions/31758303/html-5-form-validation-without-form

**Comment by flyswatter** [comment]
I got it working in UI dev mode, but looks like extension popups don't respect it.

![screen shot 2017-03-22 at 11 07 17 am](https://cloud.githubusercontent.com/assets/542863/24213503/e6a82ac8-0eef-11e7-892c-ce4f35b698b7.png)

**Comment by flyswatter** [comment]
If we got rid of our extension-weird-popup and just made it a normal popup, I bet this would work. Now related to #1240.

**Comment by kumavis** [comment]
try it by opening the extension popup.html url directly

**Comment by flyswatter** [comment]
Was able to get it to work on the `popup.html` directly, but still does not show on the extension-popup.  Trying out the `invalid` event on the form to trigger a warning indication.

**Comment by flyswatter** [comment]
Ah the `invalid` event is on the individual elements, good:
https://github.com/facebook/react/issues/5152

**Comment by Zanibas** [comment]
Check this out @flyswatter 

https://www.reddit.com/r/ethereum/comments/60ievn/eth_gas_station_consumer_oriented_metrics_for_the/dfa1elj/
