### ISSUE TITLE
Get working with Kovan

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1238]
In addition to adding Kovan as a menu option, we have reports that MetaMask currently fails signing kovan transactions.  This needs to be addressed.

**Comment by flyswatter** [comment]
User @crazyquark had this issue, wrote:

I tried to do this and transactions fail, I don't know why, I just get this error object:
`ZoneAwareError
__zone_symbol__error
:
Error: Transaction execution error. at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:27885) [<root>] at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:26989 [<root>] at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:179:7 [<root>] at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6682:5 [<root>] at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6570:47) [<root> => <root>] at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6820:38) [<root>] at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7931:25) [<root>]
message
:
"Transaction execution error."
originalStack
:
"Error: Transaction execution error.↵    at ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7362:33)↵    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:27885)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:26989↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:179:7↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6682:5↵    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6767:31)↵    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6570:47)↵    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6820:38)↵    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7931:25)"
stack
:
"Error: Transaction execution error.↵    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:27885) [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:26989 [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:179:7 [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6682:5 [<root>]↵    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6570:47) [<root> => <root>]↵    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6820:38) [<root>]↵    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7931:25) [<root>]"
zoneAwareStack
:
"Error: Transaction execution error.↵    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:27885) [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:26989 [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:179:7 [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6682:5 [<root>]↵    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6570:47) [<root> => <root>]↵    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6820:38) [<root>]↵    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7931:25) [<root>]"
__proto__
:
Object
message
:
"Transaction execution error."`

**Comment by kumavis** [comment]
@crazyquark provided is serialized tx, which is invalid RLP

I'll add a test in `ethereumjs-tx` for kovan and see if that reveals anything.
```
0x90c7635600000000000000000000000000000000000000000000000000000000000000608eeb8691e7abe1d9c38f0afd643f7b09b7824773a3cd78a46f726a500dcc368100000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000000034e434b0000000000000000000000000000000000000000000000000000000000
```

**Comment by Zanibas** [comment]
In addition, when Kovan is implemented, we should draft a notice to send out to our users.

**Comment by kumavis** [comment]
kovan seems to be working fine for me on the published version (basic txs + data txs)

**Comment by kumavis** [comment]
we'll need to add the network id name recognition
and also link to the block explorer ( `https://kovan.etherscan.io` )

![image](https://cloud.githubusercontent.com/assets/1474978/24215767/022d0898-0ef7-11e7-9b56-cef4595b07d3.png)

**Comment by crazyquark** [comment]
Humm, but the same TX is gets signed without an issue on the Ropsten network

**Comment by crazyquark** [comment]
Here is an example working TX that was successfully submitted on Ropsten but would fail to get signed with Metamask on Kovan & parity 1.6.3:
https://testnet.etherscan.io/tx/0xaeffe198c8d91b2d16fc205fa1655585545af583eb408a8540a0a65fbe376418

If you tell me how to debug metamask in Chrome I will get more info. I have it built but I am unable to set breakpoints, the source map does not load properly.

**Comment by kumavis** [comment]
@crazyquark how are you submitting the tx to metamask?

**Comment by crazyquark** [comment]
Code  Issues 0  Pull requests 1  Pulse
frontend/src/app/services/proxy-contract.service.ts

import {Injectable, ApplicationRef} from "@angular/core";
import {MetaMaskService} from "./metamask.service";
import {TransactionRequest} from "../types/transaction-request";
import {Observable} from "rxjs";
import {TxResourceService} from "./tx-resource.service";
import {TxInfo, TxType} from "../types/tx-info.model";
import {HashConfirmation} from "../types/hash-confirmation.model";
@Injectable()
export class ProxyContractService {


    constructor(private metaMaskService: MetaMaskService,
                private applicationRef: ApplicationRef,
                private hashResourceService: TxResourceService) {
    }

    forwardTransaction(contractDefinition: any, txType: TxType, forwardContractRequest: TransactionRequest, hashPath: string, pathParam: string): Observable<void> {
        const web3 = this.metaMaskService.getWeb3();
        const proxyContract = web3.eth.contract(contractDefinition);
        const proxy = proxyContract.at(forwardContractRequest.userProxyAddress)
        console.log("Contract definition", contractDefinition);
        console.log("Will forward contract ", forwardContractRequest);
        return Observable.create(observer => {
            //Forward to proxy contract
            proxy.forward(
                forwardContractRequest.destinationAddress,
                0,
                forwardContractRequest.rawData,
                {gas: forwardContractRequest.gasLimit},
                (error, transactionHash) => {
                    this.applicationRef.tick();
                    if (error) {
                        //There was an error forwarding the proxy contract
                        //TODO: let the backend know there was an error?
                        observer.error(error);
                    } else {
                        //Forwarding the proxy contract succeeded
                        this.hashResourceService.sendTransaction(new TxInfo(txType, hashPath, pathParam, new HashConfirmation(transactionHash,
                            forwardContractRequest.internalTxId))).subscribe(() => {
                                observer.next();
                                observer.complete();
                        }, error => {
                            //TODO: If we have a network error here, the backend will never know the hash. Is this a problem?
                            observer.error(error);
                        });
                    }
                }
            );
        });
    }


}
