### ISSUE TITLE
Enforce hard gas upper limits

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1274]
Total max tx cost should not be able to exceed the user's balance.
Total tx fee should not be able to exceed the block gas limit.

Any others?

**Comment by kumavis** [comment]
> Total max tx cost should not be able to exceed the user's balance.
I think this is actually fine, it should just disable the accept button and show the buy ether buttons like we normally do (used to do?)

**Comment by flyswatter** [comment]
We had some reports where the suggested `txLimit` (which [according to our code should be 1.5x the estimate](https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/lib/tx-utils.js#L65)) was way higher than it should be.

I think we should enforce some strong unit tests around this logic, in case it's wrong.

**Comment by flyswatter** [comment]
I've improved our gas logic a good bit [on this branch](https://github.com/MetaMask/metamask-plugin/tree/ImproveGasEstimates).  There's another change @kumavis is going to make.
