### ISSUE TITLE
Header Requirement in Remix?

### ISSUE THREAD

**Issue by zach-is-my-name** [MetaMask/metamask-plugin#1278]
Hi, wondering if the rollback referenced in https://github.com/ethereum/browser-solidity/issues/491 has taken place and if @chriseth must move as well to restore injected web 3 option?.  Thx!

**Comment by kumavis** [comment]
Yes this was published to the chrome store a few hours ago.
you can see the diff here: https://github.com/MetaMask/metamask-plugin/pull/1275/files
