### ISSUE TITLE
Web3 not available on load event

### ISSUE THREAD

**Issue by chejazi** [MetaMask/metamask-plugin#1279]
I have fallback code when the user is browsing without Metamask. It works basically as follows:

```
window.addEventListener('load', function () {
    if (!window.web3) {
        //load alternative to Metamask's web3...
    }
});

```

Starting today, March 28, Metamask isn't injecting Web3 for my app. I did some further digging and it seems to only affect my host - https://credsign.github.io. I created a blank page at https://credsign.github.io/testnet/test.html and it's clear that Web3 is not getting injected.

**Comment by chejazi** [comment]
Moments after publishing this issue it's getting injected again. Strange! I'll close this issue but I'm genuinely curious what was going on. Metamask wasn't injecting Web3 for the past several hours on Credsign - but I saw Web3 being injected elsewhere on the internet.

**Comment by chejazi** [comment]
I'll reopen this issue if the problem reappears.

**Comment by flyswatter** [comment]
I bet it's because your site doesn't have a proper `<!DOCTYPE html>` header tag.

We briefly changed our injection logic to look for that tag, but found many dapps didn't have correct HTML, so [we changed the logic again](https://github.com/MetaMask/metamask-plugin/pull/1275) to be more permissive.
