### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by ahmedcharef** [MetaMask/metamask-plugin#1280]
I have update MetaMask to version 3.5.2, in the web console,MetaMask is injected:
`MetaMask - injected web3`
But I got this error after :
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null') in the js file (contentscript.js:3364).

**Comment by flyswatter** [comment]
Are you working on a local dapp, served off your file system?  If so, you should be aware that [running off a server is required](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#globe_with_meridians-https---web-server-required) to use MetaMask.
