### ISSUE TITLE
Changes to Gas Limit don't happen upon clicking accept

### ISSUE THREAD

**Issue by GriffGreen** [MetaMask/metamask-plugin#1314]
Using Chrome Version 57.0.2987.133 (64-bit) on Mac OS 10.12.3

Using Metamask on https://wallet.ethereum.org/ I was interacting with a contract (https://etherscan.io/tx/0xe9ba82bb9a5926939dfa8717f38307a190716e312a27e25c19fa64d6fad0934f) and wanted to increase the gas limit just in case, so i changed the leading digt from a 3 to a 5 but the gas limit when transmitted didn't change. I think it would have changed IF i would have clicked anywhere before clicking accept... but i didn't.

Also, heading to seattle, Maybe i can deliver some thai food ;-) 

Much love,
Griff

**Comment by Zanibas** [comment]
Not able to replicate reliably @GriffGreen, can you provide more explicit steps?

Can you also see if you get this issue with a normal account-to-account transaction?

**Comment by GriffGreen** [comment]
I was not able to replicate. :-D

**Comment by GriffGreen** [comment]
I must have just clicked thru very quickly... or quick enough for my slow computer to have not updated metamask.
