### ISSUE TITLE
Metamask/infura stuck at block 3498081

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-plugin#1317]
It seems as of now Metamask is stuck at block 3498081 making our dapp unusable

**Comment by wighawag** [comment]
I created an issue on infura : https://github.com/INFURA/infura/issues/18

**Comment by flyswatter** [comment]
Infura reports this should be back to normal.  Sounds like they had a surprise very heavy load event.  Not sure if it was DDOS or what yet.

**Comment by flyswatter** [comment]
Can you confirm this is fixed?

**Comment by wighawag** [comment]
Yes this is resolved thanks
