### ISSUE TITLE
0 на балансе

### ISSUE THREAD

**Issue by yra310** [MetaMask/metamask-plugin#1318]
в блокчейне баланс 0.5 а в программе 0

**Comment by yra310** [comment]
0xA3bc6B0d2347F06253CB6ECce6bF65EED4d9da21

**Comment by flyswatter** [comment]
I believe this is a duplicate of #1317, and is fixed now.

Still a problem?

**Comment by frankiebee** [comment]
Я думаю что это исправлено. Если нет сообщите нам об этом.
