### ISSUE TITLE
Issue with Dropbox UI when MetaMask Chrome extension installed and active

### ISSUE THREAD

**Issue by ryancharleston** [MetaMask/metamask-plugin#1321]
I'm noticing an issue with the screen not refreshing and displaying the next page of content when clicking on links within Dropbox, when the MetaMask extension is installed in Chrome. I uninstalled MetaMask and Dropbox continues working normally.

**Comment by rideSpecialized** [comment]
I am also experiencing issues with the dropbox.com web UI with Metamask installed.  I have narrowed it down to that extension with several test iterations.  

I can reliably reproduce the issue in normal mode and incognito mode by enabling or disabling the Metamask extension.  

Chrome version: 57.0.2987.133 (64-bit)

**Comment by dmosites** [comment]
+1. The way web3 is being injected by MetaMask appears to be creating a conflict with Dropbox JavaScripts.

**Comment by flyswatter** [comment]
Thanks for the notice, we'll be looking into this soon.

In the meanwhile, you can work around the problem without uninstalling by disabling MetaMask.  This lets you keep your vault active.

To disable MetaMask, right-click the fox icon in the menu bar, and select `Manage Extensions`.  Then uncheck the `active` box next to the MetaMask item.

**Comment by tmashuang** [comment]
@ryancharleston have you seen improvements with Dropbox and Metamask?

**Comment by rideSpecialized** [comment]
Actually... just tested and it seems to be working.  Cool!

**Comment by ryancharleston** [comment]
Looks like it's working now. Thanks for fixing!
