### ISSUE TITLE
Reject tx during batch will cause "Lost connection"

### ISSUE THREAD

**Issue by dyzz** [MetaMask/metamask-plugin#1329]
**Environment**
MetaMask 3.5.2, Chrome 59 dev

**How to reproduce**

create an array of payloads, and using
```javascript
web3.currentProvider.sendAsync(payloads, (err, result) => {
      // callback
})
```
after metamask popup, reject any tx will trigger the error below, and metamask will never reconnect.

> inpage.js:252 MetamaskInpageProvider - lost connection to MetaMask
> TypeError: Cannot read property 'id' of null
>     at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6698:69
>     at Array.map (native)
>     at generateBatchId (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6698:32)
>     at StreamProvider._onResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6665:10)
>     at StreamProvider._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6691:8)
>     at doWrite (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:5189:64)
>     at writeOrBuffer (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:5178:5)
>     at StreamProvider.Writable.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:5116:11)
>     at DestroyableTransform.ondata (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4261:20)
>     at DestroyableTransform.EventEmitter.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:2880:17)
>

**Comment by flyswatter** [comment]
Short term workaround:

Use `async` or `Promise.all` to send multiple txs at once (not using the RPC batch API).  MetaMask actually un-batches these requests in the background anyway, so this would lose no performance.

Long term, MetaMask should adopt the proper batching method, and that would be the correct fix for this.
