### ISSUE TITLE
Every transaction sent through MetaMask plugin results in an error

### ISSUE THREAD

**Issue by wilfreddenton** [MetaMask/metamask-plugin#1353]
<img width="378" alt="screen shot 2017-04-27 at 6 37 57 pm" src="https://cloud.githubusercontent.com/assets/1426935/25507231/be05b842-2b78-11e7-9840-75d1a4727bb5.png">

This is the error I get when I try to send transactions that work properly when I go directly to testrpc or the test network.

I've been testing with the Truffle metacoin example Dapp and the `sendCoin` transaction results in this error every time.

**Comment by flyswatter** [comment]
Sorry, this is a known bug that was fixed in testrpc.  Run `npm install -g ethereumjs-testrpc`.

**Comment by wilfreddenton** [comment]
Yup that was the problem. Thanks for the quick response @flyswatter!

**Comment by wilfreddenton** [comment]
@flyswatter btw, these transactions would fail silently. The popup would just spin infinitely and the promise would never resolve. I have to refresh when this happens. Is this intended behavior? Since I updated testrpc I have received a few "Out of gas" errors and they failed silently as well.

**Comment by flyswatter** [comment]
Good call, that's worth an open issue.  I actually found we have two relevant open issues, and I'm going to just push them sooner, because silent failure is awful:

#1091
#1254
