### ISSUE TITLE
Total ETH doesnt update

### ISSUE THREAD

**Issue by markmcdonald51** [MetaMask/metamask-plugin#1354]
Hi,
Been using MetaMask for transferring Ether and after 6 or so transactions it doesn't update --even though I can see the transactions on Etherscan.io.

I use the same metamask account on multiple chrome browsers. Now they all are out of sync with the blockchain.  Has anyone else seen this problem?

**Comment by flyswatter** [comment]
Aha!  This is a known problem.  Right now it's very easy for multiple clients (of many sorts) to de-sync their nonces when running the same accounts.

To re-sync an instance of metamask, you can either:
- Change the network to another one and back again
- Restart your browser

Sorry about this, we're working on better long-term strategies.
