### ISSUE TITLE
No option to create new valult

### ISSUE THREAD

**Issue by susmit-git** [MetaMask/metamask-plugin#1366]
After a long time when i tried to use Metamask realized that have forgot my password and also cant find my seed. Now am not getting any option to create another vault rather it keeps asking to provide the password. Please help with the next steps to do it.

**Comment by tmashuang** [comment]
I believe in order to create a new vault Metamask has to be reinstalled.

**Comment by susmit-git** [comment]
Seems the feature to create a new vault once password is not recoverable, is not yet implemented.

Thanks a lot it worked!
