### ISSUE TITLE
account "freezes" after deploying a contract

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-plugin#1368]
reported on slack by eric:
After deploying a contract the account seems to get "frozen"

e.g. balance not updating 

Not sending a transaction

But the transactions are producing a hash

**Comment by kumavis** [comment]
do the tx hashes show up on etherscan?

**Comment by frankiebee** [comment]
some but not all

**Comment by tmashuang** [comment]
it took a while for my txs to show up. I still have one pending(not showing up in etherscan). One now that was pending just showed up.

**Comment by frankiebee** [comment]
Closing for now as it seems parity was choking across the board on ropsten and was the cause of this. Will reopen if not the case.
