### ISSUE TITLE
MetaMask doesn't fetch latest data

### ISSUE THREAD

**Issue by madvas** [MetaMask/metamask-plugin#1373]
Hi guys,
Me and other Ethlance users are hitting very unpleasant bug for something more than a week now maybe. When users on Ethlance submit new data, transaction goes through okay, but then MetaMask can't load these new data. Whether be it new job, user, job proposal. After disabling & enabling MetaMask again, it loads data just fine. As if MetaMask cached requests and didn't want to load latest data. It doesn't happen every single time, but it happens quite often. 

Sorry I don't have exact "steps to reproduce", but this has been reported by multiple Ethlance users. It's quite serious issue for our app. 

Thank you

**Comment by frankiebee** [comment]
I'm sorry to here this we will look into it.

**Comment by flyswatter** [comment]
Looks like this is fixed in our new block-tracker and will be fixed very soon! (later today!)

**Comment by Zanibas** [comment]
@flyswatter can we confirm this is fixed? If this is already in production, can @madvas confirm?

**Comment by flyswatter** [comment]
Yeah this should be fixed. Will reopen if observed again.

**Comment by madvas** [comment]
yep, haven't met this issue since latest release

**Comment by madvas** [comment]
Thank you for fast fix!
