### ISSUE TITLE
MetaMask doesn't work on Ubuntu

### ISSUE THREAD

**Issue by systemaddict** [MetaMask/metamask-plugin#1374]
Can't access oasisdex.com with MetaMask pm Ubuntu 16.04 and Chrome Version 57.0.2987.98 (64-bit)

Works on other platforms. Throws this error:

Uncaught Error: Wrong usage of the API. Read documentation
    at p (738e745….js:188)
    at i (738e745….js:188)
    at r (738e745….js:183)
    at Object.callback (738e745….js:183)
    at chrome-extension://nkbihfbeogaexxxxxxxxxxxgknn/scripts/inpage.js:6708
    at chrome-extension://nkbihfbeogaexxxxxxxxxxxgknn/scripts/inpage.js:6708
    at chrome-extension://nkbihfbeogaexxxxxxxxxxxgknn/scripts/inpage.js:179
    at chrome-extension://nkbihfbeogaexxxxxxxxxxxgknn/scripts/inpage.js:6684

**Comment by Zanibas** [comment]
I am able to get basic functionality on oasisdex right now with our latest install of MetaMask, on 16.04, with Chrome Version 57.0.2987.110 (64-bit)

What exactly isn't working? Are you unable to access the site completely?

**Comment by systemaddict** [comment]
I couldn't get that version installed but I did try with Chrome Beta Version 59.0.3071.36 and then it started working

Also tried uninstalling plugin and browser with the old version (Version 57.0.2987.98) but the javascript error is still thrown.

Since this error could be with opendex I close this issue.
