### ISSUE TITLE
Not recognizing oasisdex

### ISSUE THREAD

**Issue by ieatsleep** [MetaMask/metamask-plugin#1386]
Hello,
Metamask is not recognizing oasisdex anymore. I wouldn't say anything has changed in my system settings. Windows 8.1, latest Chrome version, already deleted and added Metamask plugin.
What could be the issue and what should I try to make it recognize it?
Thank you!

**Comment by niktrix** [comment]
Can you make sure you are in main net

**Comment by frankiebee** [comment]
just so i'm clear you are talking about MKR Market (https://oasisdex.com/#trade/W-ETH/MKR)? can you be a little more specific on not recognizing as in mkr does not think you are using MetaMask?

**Comment by ieatsleep** [comment]
Yes, it's on the main network.
Yes, I am talking about the MKR Market. The page just says: Not connected to Ethereum, as if I had no Metamask plugin at all.

**Comment by frankiebee** [comment]
could you open up the console and give me any errors you see? you can do this by right clicking and inspecting the page. @niktrix you shouldn't have to be on main net to see MKR

**Comment by ieatsleep** [comment]
I'll inform you as soon as I have the access to my personal computer.

**Comment by frankiebee** [comment]
@ieatsleep as well as any errors that are in the extension. to do this you will have to navigate to chrome://extensions and inspect the background page more info on how to do that: https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome

**Comment by ieatsleep** [comment]
I am sorry for making this an issue. I found the problem. I had a Parity plugin active as well, which in some way does not work together when using Metamask. I removed it and I can access Oasisdex now.

**Comment by Zanibas** [comment]
Interesting conflict though, we'll look into it further internally.
