### ISSUE TITLE
Metamask won't confirm the transactions

### ISSUE THREAD

**Issue by mariam-crissi** [MetaMask/metamask-plugin#1395]
I am using testrpc as client...I I can't accept the transactions to execute on the Metamask interface... But the dapp works successfully without using metamask....
Does anyone have the same issue???

**Comment by kumavis** [comment]
@tcoulter sounds like the same EIP155 issue

**Comment by mariam-crissi** [comment]
@kumavis I can't find that issue

**Comment by kumavis** [comment]
@mariam-crissi https://github.com/ethereumjs/testrpc/issues/297

**Comment by kumavis** [comment]
work around is to specify a low chainid <200

**Comment by mariam-crissi** [comment]
@kumavis @tcoulter I have tried the Metamask versions 3.6.2 & 3.6.1...These both versions have issues......But it perfectly works for the version 2.13.11 .......

**Comment by kumavis** [comment]
[EIP155](https://github.com/ethereum/eips/issues/155) support was introduced relatively recently

**Comment by kumavis** [comment]
@mariam-crissi this flag should help `testrpc --network-id 50`

**Comment by mariam-crissi** [comment]
@kumavis I have update testrpc..Now it works fine
