### ISSUE TITLE
Metamask won't confirm/accept transaction from yesterday

### ISSUE THREAD

**Issue by mariam-crissi** [MetaMask/metamask-plugin#1396]
I am using testrpc as client...I I can't accept the transactions to execute on the Metamask interface... But the dapp works successfully without using metamask....
Does anyone have the same issue???

**Comment by szerintedmi** [comment]
I had an issue like that. I removed the Metamask plugin and created a new account then it worked again. Not sure what was the cause neither if the new account or the plugin reinstall solved it.

**Comment by Zanibas** [comment]
Can you clarify the steps to reproduce?

**Comment by mariam-crissi** [comment]
@szerintedmi  I have updated testrpc and it worked...
