### ISSUE TITLE
ENS address not resolving

### ISSUE THREAD

**Issue by linagee** [MetaMask/metamask-plugin#1401]
Not sure if I'm doing this right with ENS, but it didn't seem to work.

![image](https://cloud.githubusercontent.com/assets/636551/25859271/42e6a366-349b-11e7-9bb9-de5847209207.png)

I've tried a few other combinations like "rilxxlir" and "rilxxlir.eth". Same response. The owner and resolver were defined for this. https://etherscan.io/enslookup?q=rilxxlir.eth

I am running MetaMask 3.6.3 in Chrome. It looks like ENS support was added in 3.5.0, but maybe not? Or maybe the ENS main resolver address isn't entered into the plugin yet?

**Comment by flyswatter** [comment]
This will need to be addressed in [ethjs-ens](https://github.com/ethjs/ethjs-ens), which we use for this (I made it).

My first knee-jerk is that the name is resolved, and has an owner, but doesn't resolve to a resolver? Writing a test to check this out now. Thanks for being the first person with a main-net address to try it!

**Comment by flyswatter** [comment]
Oh on trying it, this actually looks like our ens lookup isn't triggering, although this name `apt-get.eth` does not seem to have a resolver set yet.

**Comment by Zanibas** [comment]
Fixed by #1402
