### ISSUE TITLE
cannot call any functions while previous tx is pending (in Remix)

### ISSUE THREAD

**Issue by SCBuergel** [MetaMask/metamask-plugin#1406]
Due to [a previously reported issue](https://github.com/MetaMask/metamask-plugin/issues/1405) Metamask broadcasted a tx with a huge gas value which is slightly over the current block gas limit and hence my tx is pending for several minutes. I am attempting to now call another function (again via Remix). Even calling a constant function just returns `Waiting to be mined...` and hangs like that forever.

A temp work-around for me is to close Remix and open it again (not just pressing F5 for reload). This does not look like a Remix issue but rather like a Metamask issue but I'm not 100% sure.

**Comment by kumavis** [comment]
> A temp work-around for me is to close Remix and open it again

sounds like a remix issue, but i can take a look

**Comment by Zanibas** [comment]
Confirmed as remix issue, closing for now.

**Comment by SCBuergel** [comment]
[Here](https://github.com/ethereum/remix/issues/505) the link to the Remix issue to keep track for future users landing here.
