### ISSUE TITLE
Edited gas price sometimes still submits previous gas price

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1407]
Using windows 10

Reported by `robertheessels` on our slack.

I thought we fixed this, but worth trying again on Win 10.

**Comment by SCBuergel** [comment]
how likely is it that you report this 2min before me independently experiencing this?! ;)
but I have proof [here](https://etherscan.io/tx/0x20716fd38f84baa3820c82ec2a1bdd3292ee666e4984015c6008ee84c95bbc2e) and [here](https://etherscan.io/tx/0x3e32c8cd0fff492cb955ce84a6ff84399506d1d188741a8cc2d19cdf38afe683).
Anyway, hope this gets resolved ASAP - I wont touch Metamask unless I get certainty that it is...

**Comment by flyswatter** [comment]
@SCBuergel can you give specific reproduction steps? The order that you click, highlight, and type could be relevant.

**Comment by SCBuergel** [comment]
After running into https://github.com/MetaMask/metamask-plugin/issues/1409 it is now working. But the following is what failed before:
1. Quit Chrome and killed process from taskbar (I am on Ubuntu 16.04, latest Chrome)
2. Open Chrome again (some random landing page)
3. Click on Metamask and enter password (Metamask is connected directly to main net, not, e.g. via geth)
4. Open https://remix.ethereum.org/#version=soljson-v0.4.11+commit.68ef5810.js which already has the contract open that I [pasted before](https://github.com/MetaMask/metamask-plugin/issues/1405#issue-227767189)
5. Click on `Contract` tab in remix on the top right, then find the contract `Bounty2.sol:Bounty2` and click `At Address`, paste `0xb96e6185eBE5D83ee2cCE9502c8f717C35591276` into the popup
6. Paste `"0xf81b517a242b218999ec8eec0ea6e2ddbef2a367a14e93f4a32a39e260f686ad"` in the `bytes32` textbox and click the corresponding `addCode` button to trigger that function.
7. Wait for Metamask popup to appear - it shows some huge > 4M gas amount, click into it, highlight the number and replace with `200000`, then click on `Confirm`.
8. Open etherchain and check transaction

**Comment by flyswatter** [comment]
I currently strongly suspect that both this and #1408 were fixed in `3.6.2` by [this commit](https://github.com/MetaMask/metamask-plugin/commit/d61b587f3014823fcd23b1e5becce7949e88d952), which solved a problem where a form's value would be cached until an additional `render` call updated the cached form state.

Next time someone reproduces this, they should note their MetaMask version, if it's 3.6.2 or later, we really do have a problem, otherwise, this may be people opening MetaMask for the first time in a while, not having the latest update yet, and experiencing a fixed bug.  (I guess we're still learning about Chrome's rollout logic).

To get the MetaMask version:  Open MetaMask, open the top-right menu, click `? Info`.

**Comment by robertheessels** [comment]
I checked that I had 3.6.3. Then changed the gas (gwei?) form 20 to 2. The transactions gas costs were still about $1.
https://etherscan.io/tx/0xdc73cd36f2e845d57eb4897dab1709b5e8a377c406388378d38e79122a1940cf

**Comment by SCBuergel** [comment]
All my issues were reported for Metamask 3.6.4

**Comment by SCBuergel** [comment]
Another example of how hard it is to reproduce this:
I am submitting a bunch of different value to the very same function in Remix. I do not close my browser or change anything anywhere. I only copy-paste different values into the textbox of the function parameter. Every single transaction has a suggested gas limit over 4M, every one I change back to 200k. The first three worked well
https://etherscan.io/tx/0x181983e87a6a0751e4da8faf69b0dbf8033c9266c955395832dba46766bf598c
https://etherscan.io/tx/0xe5ae55b3f49f92a2f2bc3e6bfe256b7c6bb1a4f43ab8e64308629f1f3bbf6292
https://etherscan.io/tx/0x46c8e422ba466c5b0f9fecfe16af731bd421838a76fb842ca57a8acadd70bb2b
and then one failed to set the limit to 200k:
https://etherscan.io/tx/0xfb323a42080813f88fa18cd7cc7ad7357f39577c1ae1c7c958bd2382bbfc498f

**Comment by Zanibas** [comment]
Ran on Ubuntu 16.04, Chrome ver. 58.0.3029.96 (Official Build) (64-bit)

Reproduction steps done, except done on testnet (because I'm poor), was able to properly edit the gas value. But I'm sure it'd fail with a few more attempts.

However, this issue keeps popping up and it's not something that happens all the time. We are unsure why it works for some txs and not for others.

**Comment by kumavis** [comment]
> Every single transaction has a suggested gas limit over 4M
@SCBuergel yeah remix sets it to the block gas limit

**Comment by SCBuergel** [comment]
@kumavis Ok then lets report as issue to Remix.

**Comment by kumavis** [comment]
https://github.com/ethereum/remix/issues/506

**Comment by flyswatter** [comment]
I believe this is related to #1408 and if we could create a reliably reproducing test case for one, it would also fail for the other, and we could fix them together.

**Comment by flyswatter** [comment]
I think this may be the result of React's Component `setState()` method not making guarantees about how soon that "state" is updated.

The correct solution may be to go old school:  Cache the values ourselves, and/or on submit, grab the values from the form fields themselves.

Interesting article:
https://medium.com/@mweststrate/3-reasons-why-i-stopped-using-react-setstate-ab73fc67a42e

**Comment by kumavis** [comment]
lets vote the bums out

**Comment by kumavis** [comment]
reading the title from link i was pretty sure it was
> 3 Reasons why I stopped using React

and i liked the notion

**Comment by flyswatter** [comment]
Actually I'm not sure this describes our bug, although it sure seems similar.

**Comment by kumavis** [comment]
seems like its waiting for the next render/frame to call setState, meaning if there is nothing new to render (e.g. balance updated on new block) we might not get the setState value maybe

idk, certainly seems similar

**Comment by flyswatter** [comment]
I think it may have set me on the right path, though.  I thought I understood `setState`, but check this out from [the React Component docs](http://reactjs.cn/react/docs/component-api.html):

> when your component's state or props change, your component will re-render. However, if these change implicitly (eg: data deep within an object changes without changing the object itself) or if your render() method depends on some other data, you can tell React that it needs to re-run render() by calling forceUpdate().

Since the `pending-tx` component's state shape is a deep object, with `{ txData: { txParams: { gasPrice: "..." } } }`, it looks like `setState()` may not trigger a re-render....

Aw, but it's not the `render` we want, it's just updating the state before the `submit` event fires.  Still a bit puzzled.

**Comment by flyswatter** [comment]
I'm inclined to think the `setState()` may not be triggering an actual state update since the change is deep, so it's possible a `forceUpdate()` would fix this.

We have two users here who experience the problem regularly, maybe we could push them a build to test with, and reimburse them some testnet ether or something.

**Comment by bamos01** [comment]
Hi- i noticed the following behavior on mac chrome with v 3.6.4:  when i first log in - the first transaction I send after manually lowering the gas price still is recorded as 20 gwei.  but the next transaction I send with manually lowered gas price goes through as expected.  the problem seems to be with the first transaction for me and not for subsequent ones.

**Comment by robertheessels** [comment]
Just did a ENS reveal with MetaMask 3.6.4 on Win10 and change the gas from 20 to 2. It was still executed at 20.

**Comment by flyswatter** [comment]
That's a good lead, @bamos01, thanks!

**Comment by flyswatter** [comment]
Making a checklist of portions of the code that could cause this:

- [x] The UI (seems to be ruled out by [these tests](https://github.com/MetaMask/metamask-plugin/blob/master/test/unit/components/pending-tx-test.js)).
- [x] The transaction manager (seems to be ruled out by [these tests](https://github.com/MetaMask/metamask-plugin/pull/1441#partial-pull-merging).
- [ ] The tx-utils when preparing the transaction
- [ ] The provider-engine

Please help me notice any other spots, the remaining two seem like really unlikely places for this bug to reside, I'm getting pretty stumped.
