### ISSUE TITLE
Ignores manually overwritten gasLimit

### ISSUE THREAD

**Issue by SCBuergel** [MetaMask/metamask-plugin#1408]
As [reported before](https://github.com/MetaMask/metamask-plugin/issues/1405), Metamask sometimes inappropriately suggest huge gas limits. So far I have been successful in manually overwriting it before clicking "confirm". Now this procedure failed twice: despite me entering `200000` [this](https://etherscan.io/tx/0x20716fd38f84baa3820c82ec2a1bdd3292ee666e4984015c6008ee84c95bbc2e) and [this](https://etherscan.io/tx/0x3e32c8cd0fff492cb955ce84a6ff84399506d1d188741a8cc2d19cdf38afe683) transaction have been broadcasted with a gas limit of 4310430 and 4309906 respectively. [Yes, I am 100% certain that I did enter a gas limite of 200k myself, I repeated the second transaction just to be absolutely certain.]

I am done subsidizing the global mining economy for now.

**Comment by flyswatter** [comment]
Noting:

SCBuergel used:

Metamask 3.6.4
Ubuntu 16.04

**Comment by Zanibas** [comment]
Duplicate of #1407
