### ISSUE TITLE
Ability to delete / create new vault

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#141]
This is a more incremental version of #67.

Just a basic ability to clear + re-create a vault, instead of uninstalling/reinstalling the extension.

**Comment by flyswatter** [comment]
Closing in favor of #172

**Comment by tcoulter** [comment]
I'm finding I would really love this feature. The vault I have right now is only for testing, and now I need to use metamask for real transactions. The testing mnemonic has been compromised. Would love to delete and start over.

**Comment by fabienb4** [comment]
Agreed with @tcoulter.
Maybe by adding a setting to switch between `developer`/`user` modes, and only show the delete button in developer mode to keep it simpler for regular users?

In the meantime, you can delete the files manually in `~/.config/google-chrome/${profile}/Local Storage`.
Look for files with the extension's ID in the name: `nkbihfbeogaeaoehlefnkodbefgpgknn`
Should be:
`chrome-extension_nkbihfbeogaeaoehlefnkodbefgpgknn_0.localstorage`
`chrome-extension_nkbihfbeogaeaoehlefnkodbefgpgknn_0.localstorage-journal`

Open Chrome again, and you will be able to setup a new vault...

On Windows, the files should be in `${drive}:\Users\${accountName}\AppData\Local\Google\Chrome\User Data\Profile ${profileNum}\Local Storage\`

**Comment by ajsantander** [comment]
I didn't find the files at the specified path in mac, but I managed to reset my account by uninstalling the extension and re-installing it. It will start over, ask for a new pass, etc...
