### ISSUE TITLE
gasPrice does not allow numbers with decimals

### ISSUE THREAD

**Issue by alex-miller-0** [MetaMask/metamask-plugin#1412]
I tried to set several `gasPrice` values with decimals (e.g. 2.1) and, after adding the first digit after the decimal, my number was replaced with something seemingly random.

Three examples:
2.3 --> 183
2.5 --> 185
0.3 --> 4294967279

**Comment by Zanibas** [comment]
Connecting to #1411 

We have had this concern in the past, we weren't sure if users would be concerned if we locked them into integer gas prices. We will evaluate this problem within #1411.
