### ISSUE TITLE
Switch default testnet to Rinkeby

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1419]
Infura recommended. Ropsten keeps getting taken down.

We'll need to address our fauceting strategy.

**Comment by SCBuergel** [comment]
One great utility of the testnet in metamask right now is to get some testnet ether and be ready to play right away. If you switch over please keep this.

**Comment by SCBuergel** [comment]
This currently does not hand out testnet Ether. That is a big big minus for all those (many) people who download MetaMask to start playing right away without any further clicks.

**Comment by kumavis** [comment]
@SCBuergel thats true, but must also consider that most users expect the network to just work and with ropsten that has been a problem. we agree that the fauceting barrier is annoying. we are unable to auto faucet to rinkeby. we'll continue to monitor ropsten and determine if it is the better testnet.

for now you'll have to instruct users to change the network to ropsten (something they'll need to know when wanting to use mainnet)

additionally, infura is preparing a testnet that would allow us to autofaucet
