### ISSUE TITLE
Unclickable Continue Button.

### ISSUE THREAD

**Issue by Bryewalks** [MetaMask/metamask-plugin#1425]
When I click on the metamask icon  a Privacy Notice from May 8th shows up when I scroll down to the continue button I am unable to click continue.

**Comment by Zanibas** [comment]
Can you send screenshots, your chrome version, and your OS?

**Comment by Bryewalks** [comment]
Chrome Version 58.0.3029.110 (64-bit)
Windows 10 Pro Version 1607 OS Build 14393.1198
![screenshot 2017-05-15 11 46 53](https://cloud.githubusercontent.com/assets/25917358/26068892/b50181c8-3964-11e7-8615-09bed8b4d0f1.png)

**Comment by Bryewalks** [comment]
No idea what changed but it is working now. Thank you.
