### ISSUE TITLE
Metamask should not permit sending ether to ENS names when the resolver returns 0 from `addr`

### ISSUE THREAD

**Issue by Arachnid** [MetaMask/metamask-plugin#1427]
This was pointed out to me by Matt from etherscan earlier: It's important that clients treat a return value of 0 from the `addr` function the same as there being no name, or no resolver set, and refuse to send ether; otherwise, someone will try and send ether to an account that has a resolver set but no record, and accidentally send it to 0 instead.

**Comment by flyswatter** [comment]
Two assertions:

1. Resolve to 0 if resolver is set but addr isn't
2. resolve to owner if resolver isn't set.

Addressing in [ethjs-ens](https://github.com/ethjs/ethjs-ens).
