### ISSUE TITLE
Metamask doesn't detect events. 

### ISSUE THREAD

**Issue by win2win** [MetaMask/metamask-plugin#1429]
I'm connecting to ropsten on my local node. If I connect Metamask to my local node, events are firing as expected. Once I connect to ropsten directly from Metamask, events don't fire anymore. I have also connected to infura's ropsten the same problem. 

I run metamask inside Chrome. 
Metamask version 3.6.4
Operating system Ubuntu 16.04 LTS. 
geth version: 1.6.0-stabled

**Comment by kumavis** [comment]
> Once I connect to ropsten directly from Metamask

does this mean you are using a local ropsten node?

**Comment by kumavis** [comment]
can you provide an example tx that was mined that triggered events that metamask did not catch?

**Comment by win2win** [comment]
Yes, I'm running geth on my computer connecting to ropsten. 

Here is an example of transaction. https://ropsten.etherscan.io/tx/0x8ac0df072714a3111824a3aa4edc916b47f2339205784308440e46cdd691fff6

**Comment by kumavis** [comment]
ok that seems correct -- seems like you should be getting logs back

can you check for errors here
https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome

**Comment by win2win** [comment]
btw. the transactions on the Metamask transaction list appear as completed  soon after.

**Comment by win2win** [comment]
Not sure which errors are relevant in the background page.  I found these.

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.


InternalError {message: "invalid argument 0: hex number has leading zero digits after 0x", code: -32603}

**Comment by kumavis** [comment]
> invalid argument 0: hex number has leading zero digits after 0x
@win2win ok thats the problem - we'll need to fix the block ref in the filter subprovider
https://github.com/MetaMask/provider-engine/blob/master/subproviders/filters.js#L255

**Comment by win2win** [comment]
Would this error not affect all the clients?
When do you expect fix to be available?

**Comment by kumavis** [comment]
slightly older versions of geth dont enforce the hex block number so strictly
we'll likely publish the fix tomorrow

**Comment by flyswatter** [comment]
We fixed this zero-prefixing bug once already, for a different parameter.  We should get a list of the newly-strictly-enforced parameters so we don't keep getting issues like this.  Reaching out to the geth team now.

**Comment by win2win** [comment]
Will be enough to reinstall metamask to get the fix?

**Comment by kumavis** [comment]
metamask auto updates, you wont have to do anything
