### ISSUE TITLE
Metamask stuck on loading 

### ISSUE THREAD

**Issue by sumukhshetty** [MetaMask/metamask-plugin#1433]
<img width="354" alt="screen shot 2017-05-16 at 11 03 37 am" src="https://cloud.githubusercontent.com/assets/22879373/26091190/56c87f30-3a27-11e7-9406-22233fc7eca2.png">

**Comment by tmashuang** [comment]
Hey @sumukhshetty, please provide any information to help debug such as
- OS
- Chrome Version
- Metamask Version
- [Screen shots of logs](https://github.com/MetaMask/faq/blob/master/LOGS.md)

**Comment by kumavis** [comment]
also what rpc node / network you are using

**Comment by sumukhshetty** [comment]
OS: Mac
Chrome version : Version 58.0.3029.110 (64-bit)
Metamask Version : 3.6.4
Network : Kovan. But the drop down isnt working for me to switch networks either. It seems like its stuck there.
Logs:
Popup logs 
<img width="1265" alt="screen shot 2017-05-16 at 11 19 44 am" src="https://cloud.githubusercontent.com/assets/22879373/26091570/a7d0ab94-3a29-11e7-82dc-84db7101d31b.png">
Background logs
<img width="1266" alt="screen shot 2017-05-16 at 11 22 05 am" src="https://cloud.githubusercontent.com/assets/22879373/26091615/f9fae2fe-3a29-11e7-8a4d-a070a017e79d.png">

**Comment by sumukhshetty** [comment]
UI state logs
{
  "metamask": {
    "isInitialized": true,
    "isUnlocked": true,
    "rpcTarget": "https://rawtestrpc.metamask.io/",
    "identities": {
      "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a": {
        "address": "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a",
        "name": "Primary 1"
      },
      "0x0c0a328b858a4964cc7c69618e58e6758c1db2ca": {
        "address": "0x0c0a328b858a4964cc7c69618e58e6758c1db2ca",
        "name": "Account 2"
      }
    },
    "unapprovedTxs": {},
    "noActiveNotices": true,
    "frequentRpcList": [],
    "addressBook": [
      {
        "address": "0x4b23d0656f2CF0EdbB5490fab15Ea8e4611dA05d",
        "name": " "
      }
    ],
    "network": "loading",
    "accounts": {
      "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a": {},
      "0x0c0a328b858a4964cc7c69618e58e6758c1db2ca": {}
    },
    "transactions": {},
    "currentBlockNumber": "0",
    "currentBlockHash": "",
    "selectedAddressTxList": [],
    "unapprovedMsgs": {},
    "unapprovedMsgCount": 0,
    "unapprovedPersonalMsgs": {},
    "unapprovedPersonalMsgCount": 0,
    "keyringTypes": [
      "Simple Key Pair",
      "HD Key Tree"
    ],
    "keyrings": [
      {
        "type": "Simple Key Pair",
        "accounts": []
      },
      {
        "type": "HD Key Tree",
        "accounts": [
          "98be28cee0a578f647fee2e336c9eacb7dcdec9a",
          "0c0a328b858a4964cc7c69618e58e6758c1db2ca"
        ]
      }
    ],
    "selectedAddress": "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a",
    "currentCurrency": "USD",
    "conversionRate": 91.14189301,
    "conversionDate": 1494913921,
    "provider": {
      "type": "kovan"
    },
    "shapeShiftTxList": [],
    "lostAccounts": []
  },
  "appState": {
    "shouldClose": false,
    "menuOpen": false,
    "currentView": {
      "name": "accountDetail",
      "detailView": null,
      "context": "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a"
    },
    "accountDetail": {
      "subview": "transactions"
    },
    "transForward": true,
    "isLoading": false,
    "warning": null
  },
  "identities": {}
}
"{
  "metamask": {
    "isInitialized": true,
    "isUnlocked": true,
    "rpcTarget": "https://rawtestrpc.metamask.io/",
    "identities": {
      "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a": {
        "address": "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a",
        "name": "Primary 1"
      },
      "0x0c0a328b858a4964cc7c69618e58e6758c1db2ca": {
        "address": "0x0c0a328b858a4964cc7c69618e58e6758c1db2ca",
        "name": "Account 2"
      }
    },
    "unapprovedTxs": {},
    "noActiveNotices": true,
    "frequentRpcList": [],
    "addressBook": [
      {
        "address": "0x4b23d0656f2CF0EdbB5490fab15Ea8e4611dA05d",
        "name": " "
      }
    ],
    "network": "loading",
    "accounts": {
      "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a": {},
      "0x0c0a328b858a4964cc7c69618e58e6758c1db2ca": {}
    },
    "transactions": {},
    "currentBlockNumber": "0",
    "currentBlockHash": "",
    "selectedAddressTxList": [],
    "unapprovedMsgs": {},
    "unapprovedMsgCount": 0,
    "unapprovedPersonalMsgs": {},
    "unapprovedPersonalMsgCount": 0,
    "keyringTypes": [
      "Simple Key Pair",
      "HD Key Tree"
    ],
    "keyrings": [
      {
        "type": "Simple Key Pair",
        "accounts": []
      },
      {
        "type": "HD Key Tree",
        "accounts": [
          "98be28cee0a578f647fee2e336c9eacb7dcdec9a",
          "0c0a328b858a4964cc7c69618e58e6758c1db2ca"
        ]
      }
    ],
    "selectedAddress": "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a",
    "currentCurrency": "USD",
    "conversionRate": 91.14189301,
    "conversionDate": 1494913921,
    "provider": {
      "type": "kovan"
    },
    "shapeShiftTxList": [],
    "lostAccounts": []
  },
  "appState": {
    "shouldClose": false,
    "menuOpen": false,
    "currentView": {
      "name": "accountDetail",
      "detailView": null,
      "context": "0x98be28cee0a578f647fee2e336c9eacb7dcdec9a"
    },
    "accountDetail": {
      "subview": "transactions"
    },
    "transForward": true,
    "isLoading": false,
    "warning": null
  },
  "identities": {}
}"

**Comment by sumukhshetty** [comment]
Seems like it may be a infura problem, seems like its failing to fetch info from the blockchain.

**Comment by tmashuang** [comment]
I was able to reproduce this by disabling my internet access. When I turned it back on, it would not reconnect. To fix this I had to disable and enable Metamask from the extension manager.

**Comment by tmashuang** [comment]
Is this still a bug? We should have pushed a solution to this.

**Comment by tmashuang** [comment]
Closing. Will reopen if issue persists.per
