### ISSUE TITLE
`invalid sender` - when sending transactions to Private Network

### ISSUE THREAD

**Issue by illya13** [MetaMask/metamask-plugin#1444]
`Geth` based Private Network.
Versions:
- 1.5.9
- 1.6.1
- 1.6.2 (unstable / master)

started as
```
geth --datadir /data --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcapi "db,eth,net,web3,personal,admin,miner" --ipcdisable --mine --minerthreads 1 --nodiscover --maxpeers 0 --networkid 2017 --etherbase "0x8a31c26c8adb2bb0f45d70a635fcb0c4309c649b"
```
Please notice
```
--networkid 2017
```

MetaMask version:
- 3.6.4

Send any `tx` from MetaMask (including coins transfer from one MetaMask account to another) fails with `invalid sender`. I.e. RPC `eth_sendrawtransaction` fails with `invalid sender`

Downgrading MetaMask to 3.5.2 did help

Other RPC requests are working Ok:
- get Balance
- get Transactions Count

**Comment by tmashuang** [comment]
I think this problem is related to [Metamask/metamask-plugin/#1357](https://github.com/MetaMask/metamask-plugin/issues/1357)

**Comment by illya13** [comment]
yes, 
https://github.com/MetaMask/metamask-plugin/issues/1357#issuecomment-300541672
looks very similar

**Comment by illya13** [comment]
Sometimes have the same issue with Network ID = 17
Sometimes means - I have 2 computers, both with MetaMask 3.6.5 and connected to the same network
From 1 computer I can sign `tx` But from another - I can't

**Comment by flyswatter** [comment]
Are those two computers signing for the same account? That would be a different problem, and it's avoided by using different accounts from different browsers.

**Comment by illya13** [comment]
It might be the same coinbase imported. But what is the reason? You are cashing nonce? I saw `getTransactionsCount` So it looks like you are getting nonce just before sending.

**Comment by flyswatter** [comment]
We *are* caching nonce, and our nonce caching is currently having some issues, we're fixing it asap. #1127.

That usually just results in a tx not getting mined, which resembles your recent comment, but does not return an `invalid sender` error.

**Comment by kumavis** [comment]
@illya13 how did you resolve the issue? was it an EIP155 problem?

**Comment by illya13** [comment]
changed `--networkid 2017` to `--networkid 17`

**Comment by Kenmarts** [comment]
Errrmmm... Hi... I'm not a tech guru like y'all, I just need help, I keep getting invalid user on my Android trust app, I'm using the latest version. 
Justokez@gmail.com...
Please that's my mail...  Anyone with solutions can peep me there cos I don't know if I'll be able to get this thread again. 
Thanks and sorry if I'm breaking any rules

**Comment by illya13** [comment]
for private network ?

**Comment by Kenmarts** [comment]
Please explain private network, I was trying to send from one wallet to another on the TRUST WALLET app. 
Sometimes it says " unknown transaction error " then it says " invalid user or sender ".
The solution might be helpful to others encountering this problem, so please help try solve it as o may not follow up this thread again...  Thanks for Your help, God bless.

**Comment by Kenmarts** [comment]
Mind you I was using the android version not pc

**Comment by illya13** [comment]
I think your issue is not related to this one, so please stop it

**Comment by Kenmarts** [comment]
I should stop it?  Such insult... 
You can as well direct me to get a solution rather than saying I should stop... 
I thought this was a community of tech guys who were ready to help.

**Comment by illya13** [comment]
... stop commenting this one, as it seems not related to your problem
and open a new one here

https://github.com/MetaMask/metamask-extension/issues/new/choose
if you really have issues with MetaMask

**Comment by danfinlay** [comment]
Hi @Kenmarts, Illya is just pointing out that your question isn't related to his, this issue was opened by him.

It sounds like your question is related to Trust Wallet, so I would recommend asking questions from them:
https://trustwalletapp.com/
