### ISSUE TITLE
Etherscan say: Unable to locate Transaction entry

### ISSUE THREAD

**Issue by pbonandin** [MetaMask/metamask-plugin#1445]
during the Aragon ICO I try to send ETH but now my wallet is locked! 
Halp me pleas

**Comment by flyswatter** [comment]
Sorry, the Aragon sale is over. I recommend playing with [TokenFactory](http://tokenfactory.surge.sh/) on a test network to learn how to use MetaMask before the next time-sensitive thing you want to use MetaMask for!
