### ISSUE TITLE
Nonces not incrementing correctly

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1448]
Currently nonces seem to be based on current account transaction count.

This means that pending transactions aren't counted.

This means that if a new transaction is submitted while another is pending, it will be assigned the same nonce.

This means that if many txs are submitted before any of them are mined, only one of them will eventually be mined.

Parity added a method (`nextNonce`, noted [here](https://github.com/MetaMask/metamask-plugin/issues/1127#issuecomment-288868303)) for getting pending transaction count, but it isn't the same as geth's method for getting the pending transaction count.

We should maybe write an adapter for the two of them to replace our nonce tracker subprovider, and use it instead of the current cache strategy.

**Comment by kumavis** [comment]
might have been due to the lagging infura node, so our base nonce was too low and then when our pending nonces were calculated, it was still off

**Comment by flyswatter** [comment]
I don't know why I opened it, I think I had trouble finding the issue it's a duplicate of, #1127.
