### ISSUE TITLE
Bids on ENS Registrar not working properly

### ISSUE THREAD

**Issue by unilarry** [MetaMask/metamask-plugin#1457]
Hello,

   There has been issues with MetaMask regarding bidding on ENS registrar using my Chrome browser lately.  The symbol normally associated with proper transactions has changed from a circle colored symbol to three dots instead for the bad transactions.  The pop up window utilized for accepting transactions is disappearing before it confirms transactions as well.  I'm not sure why this is happening but the system is not allowing me to bid, reveal, or finalize any auctions currently.  Thanks!

Larry@LarryFenton.com

**Comment by flyswatter** [comment]
Sorry Larry, I think I've found a memory leak in MetaMask (#1458) that the ENS app really expresses to its max extent.

To clear MetaMask up, try switching your provider to a test network and back again, and then try sending your transaction again.

Use the provider menu displayed here:
![](https://github.com/MetaMask/faq/raw/master/images/click-the-test-network.png)

**Comment by unilarry** [comment]
Thanks!  Looks like it's working again.Appreciate your email.Larry


-------- Original Message --------
Subject: Re: [MetaMask/metamask-plugin] Bids on ENS Registrar not
working properly (#1457)

**Comment by flyswatter** [comment]
Glad to hear it!
