### ISSUE TITLE
Filter Subprovider Does Not Stop Polling When Page Is Closed

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1458]
When a site creates a `filter`, since Infura is stateless, we polyfill it client-side with [filter subprovider](https://github.com/MetaMask/provider-engine/blob/master/subproviders/filters.js), and poll for new logs on each new block.

However, when a site is closed, we should stop polling for those logs. Currently we seem to continue polling indefinitely.

This is especially noticeable when using the ENS registrar dapp, which adds a filter for each domain you visit and check out.

This may be a regression, or this may be a very old bug (it must be a regression, right???)

**Comment by flyswatter** [comment]
I can imagine two strategies to mitigate this initially:
- Track which browser window registers each filter, listen for that window to close, and clean up accordingly.
- Inject the filter subprovider as part of the in-page subprovider, so that the page itself has implicit ownership of the polling behavior.  The background caching will still optimize redundant requests across tabs.

**Comment by kumavis** [comment]
ive been seeing this as blocked by the provider-engine rewrite (mostly bc it removes polling) that would allow us to run a provider per page in background

moving in to the dapp is a novel idea, though we'd still have to deal with redundant block polling

**Comment by flyswatter** [comment]
What would the redundant block polling issue be? Couldn't we just force client-side block polling to our cache, and do our own unified block polling in the background?

**Comment by kumavis** [comment]
current, we explicitly skip block polling requests
https://github.com/MetaMask/provider-engine/blob/master/subproviders/cache.js#L59
we could remove that and instead expect the `skipCache` flag

**Comment by flyswatter** [comment]
Adding provider-engine middleware to the inpage streaming provider is turning out to be an interesting puzzle for my understanding of our `inpage-provider`.

Writing my general notes for how I'm thinking it would be organized here.

## First attempt:

My first attempt got a little confused on where the in stream should be, I think.  Really the provider engine already exposes the `sendAsync` method, and that should always be its input source, even if its final `end` provider is a duplex stream.

```
  // connect to async provider
  const engine = self.asyncProvider = new ProviderEngine()

  const streamIn = self.streamIn = new StreamInSubprovider()
  engine.addProvider(streamInSubprovider)

  const filterSubprovider = new FilterSubprovider()
  engine.addProvider(filterSubprovider)

  const streamOut = self.streamOut = new StreamOutSubprovider()
  engine.addProvider(streamOutSubprovider)

  // start polling
  engine.start()

  const asyncProvider = self.asyncProvider = engine
  pipe(
    streamOutSubprovider,
    multiStream.createStream('provider'),
    streamInSubprovider,
    (err) => logStreamDisconnectWarning('MetaMask RpcProvider', err)
  )
```

## Second Attempt: Triple Nested Providers?

If we want to expose a duplex stream for making requests to a provider-engine instance that itself makes requests over a duplex stream, then we may actually want something more like this:

```
  // connect to async provider
  const engine = self.asyncProvider = new ProviderEngine()

  const filterSubprovider = new FilterSubprovider()
  engine.addProvider(filterSubprovider)

  const streamOut = self.streamOut = new StreamOutSubprovider()
  engine.addProvider(streamOutSubprovider)

  const streamingProvider = new StreamProvider(engine)

  // start polling
  engine.start()

  const asyncProvider = self.asyncProvider = engine
  pipe(
    streamingProvider,
    multiStream.createStream('provider'),
    streamingProvider,
    (err) => logStreamDisconnectWarning('MetaMask StreamProvider', err)
  )
```

That last one actually looks about right to me, and the cool part is I think it nicely isolates the two portions of functionality:  Is the consumer of this provider connecting via streams, or is its data source, or (like here) are both?

Look about right?  Playing with this now.

**Comment by flyswatter** [comment]
Oh I think I noticed something that makes this much easier:  The `InpageProvider` is already exporting a basic provider, so it does not need streaming input, the streaming I noticed from the previous `StreamProvider` already only deals with outbound traffic, so I just need to replace the `asyncProvider` with a `ProviderEngine` instance that resolves with a `StreamingSubprovider` that is piped in and out of the provider multistream.

**Comment by flyswatter** [comment]
Okay so I broke up the StreamProvider into a provider-engine instance that imports a `StreamSubprovider` on [this experimental branch](https://github.com/flyswatter/web3-stream-provider/tree/StreamSubprovider).

I'm then using that subprovider to try composing existing functionality in MetaMask, but I'm getting an infinite pipe loop, wherein responses are getting sent back out as requests, working from this branch (requires the referenced dev branch above):
https://github.com/MetaMask/metamask-plugin/tree/i1458-StreamingSubprovider

**Comment by flyswatter** [comment]
For reference:

Looks like the correct solution is to create a normal web3-style provider object that only issues its *requests* via stream.  To compose this with a filter subprovider will look like this:

## Attempt 3: Streaming out requests Subprovider

```
  // connect to async provider
  const engine = self.asyncProvider = new ProviderEngine()

  const filterSubprovider = new FilterSubprovider()
  engine.addProvider(filterSubprovider)

  const stream = self.stream = new StreamSubprovider()
  engine.addProvider(stream)

  pipe(
    stream,
    multiStream.createStream('provider'),
    stream,
    (err) => logStreamDisconnectWarning('MetaMask RpcProvider', err)
  )
```
