### ISSUE TITLE
Usability problem. Cannot import private key using the "upload json file" option. The metamask window hides while selecting the file to upload.

### ISSUE THREAD

**Issue by kowalski** [MetaMask/metamask-plugin#1461]
Please see the video demonstrating this problem: https://drive.google.com/file/d/0BxHhqvqn6QSFSGVGZGFLd280Q0E/view

My at version 58.0.3029.110 (64-bit) of Chrome on Ubuntu.

**Comment by kowalski** [comment]
Also, for the record, I'm at version 3.6.5 of MetaMask plugin.

**Comment by Zanibas** [comment]
This is being addressed in #1136 and has been passed along to Chrome here:
https://bugs.chromium.org/p/chromium/issues/detail?id=721455

Being Ubuntu is suffering.
