### ISSUE TITLE
Metamask locked : no account behavior

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-plugin#1463]
Since a recent version of metamask, the behaviour changed in regard to locked/unlocked Metamask.

Now if Metamask is locked (password has not been entered) no account are shown.

Was it an intended change? In that case what is the rationale ?

Thanks

**Comment by Zanibas** [comment]
This is intended behavior--since we inject on every page and thereby expose user data potentially to any website, we give users the option to lock MetaMask to hide user information like accounts. Until we fix our injection logic to be on a per-approval basis, this is our solution to that problem.

**Comment by wighawag** [comment]
Thanks for the quick reply. It makes total sense

**Comment by flyswatter** [comment]
I would like to add a method for dapps to request user sign-in, though, still sorting out what the API should be.
