### ISSUE TITLE
Tx Approval Validation - Dynamic Gas Limit Ceiling

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#1472]
disallow txs with gas limit higher than 95% of the block gas limit

validation message should indicate current % of block gas limit and/or max gasLimit
validation message should indicate that its due to "fluctuating block gas limits"

**it should be easy to tell what you need to do to fix your gas limit**

**Comment by Zanibas** [comment]
Is this resolved with our hard gas limit of 95%, or do we need more UI on this than is already present?

**Comment by kumavis** [comment]
yeah this is covered
