### ISSUE TITLE
Allow Dapp Devs to choose the default gas price for the user

### ISSUE THREAD

**Issue by GriffGreen** [MetaMask/metamask-plugin#1473]
Fairly related to #1413, when we define a gas price, Metamask overrides our choice and makes it 20 Gwei. We would like to be able to define this for the user :-D

BACKGROUND

We have a donation button we would like to use for micro transactions and large transactions. 

One of our selling points for giveth is to lower the overhead of sending money around the world, so it is very important for us and our users to keep transaction costs down. :-D 

Often the donation button generates a token and does a few other calls so it will wind up having an estimated gas above 150,000  (great job with your `estimateGas()` buffer btw :-D!!! )

It would be very useful for us to be able to set the default gas price to 2 Gwei (or at least 5 Gwei ;-D) so that we can keep the idea of cheap microtransactions alive in these crazy times.

Much Love,
Griff

**Comment by flyswatter** [comment]
This sounds like a bug, MetaMask shouldn't be overwriting dapp parameters with its defaults.

**Comment by omnibusinc** [comment]
Is there anything that needs to be done besides specifying a `gasPrice` in the transaction?
```
web3.eth.sendTransaction({
      to: donationAddress,
      from: web3.eth.accounts[0],
      value: web3.toWei(<some amount>),
      gasPrice: web3.toWei('5', 'gwei')
    }, donationCallback);
```

**Comment by ligi** [comment]
I think I just stumbled into this one: https://www.reddit.com/r/ethereum/comments/6d3i9j/ens_bug_no_matter_where_i_slide_here_metamask/dhzk2la/
Fix would be nice ;-)

**Comment by GriffGreen** [comment]
:-D Any progress? I had a friend that paid >$20 on a failed tx :-(

**Comment by kumavis** [comment]
@GriffGreen higher priority bugs being fixed atm ("_higher than my bug??_ " yes)
this ticket will be labeled "in progress" when someone starts work on it

**Comment by GriffGreen** [comment]
Of course thank you :-D
