### ISSUE TITLE
Issue Syncing Balances, Event Change Accounts & Sends After Todays Update

### ISSUE THREAD

**Issue by 2point1creations** [MetaMask/metamask-plugin#1484]
Hi guys, 
Ever since the 5/23/2017 update our site has been having issues retreiving the balances of erc-20 tokens.  Our DApp no longer notices account changes and the sending function is now delayed and always fails.

If you have a moment I'd greatly appreciate you taking a look at it
Its the ND site Dan is aware of.

Thank you

**Comment by kumavis** [comment]
@2point1creations  do you see any error messages in the console? need to check two places
1. dapp
2. metamask background https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome

**Comment by kumavis** [comment]
additionally, reproduction instructions on the ND site would be helpful ( i have link from dan )

**Comment by flyswatter** [comment]
Observations:

Using Ropsten for test net might just be having its own bad ropsten problems, so we might want to try one without Ropsten (Getting gateway timeouts over simple blockByNumber requests).

The slowest interaction I'm seeing is when clicking `send`, the popup takes a while to appear. Wouldn't be entirely surprised if the filterSubprovider in the foreground process was creating a lot of extra work and blocking other UI activities. A little weird it didn't express those problems when it was in the background, if that's the case...

I guess we can roll back the inpage filter subprovider, since it's bogging down UI threads, and we'll need another way of deallocating these filter polling subscriptions. :(

**Comment by flyswatter** [comment]
Reproduction steps are:

1. Initial page load seems very slow (log of blockTracker getting first block seems to take a long time to proceed)
2. When sending, takes a while to pop up the send dialog.

Probably others, issues too, that I'm sure @2point1creations can comment on.

**Comment by 2point1creations** [comment]
Besdies whats mentioned above the only thing i see is when switching accounts in console i get the following  
`contentscript.js:2633 Error: PortDuplexStream - disconnected
    at PortDuplexStream._write (contentscript.js:207)
    at doWrite (contentscript.js:5005)
    at writeOrBuffer (contentscript.js:4994)
    at PortDuplexStream.Writable.write (contentscript.js:4931)
    at PostMessageStream.ondata (contentscript.js:4087)
    at PostMessageStream.EventEmitter.emit (contentscript.js:2633)
    at readableAddChunk (contentscript.js:3758)
    at PostMessageStream.Readable.push (contentscript.js:3717)
    at PostMessageStream._onMessage (contentscript.js:3371)`

**Comment by flyswatter** [comment]
That means our background process crashed.

Again, I'm not able to reproduce that one. I can switch accounts and it works fine on your site :(

**Comment by flyswatter** [comment]
I also am getting a ton of errors in your page that say:
`wallet.html:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

I wonder if there's something pausing your processing that might slow things down?

**Comment by kumavis** [comment]
> That means our background process crashed.
This means the network was changed without the dapp being reloaded

**Comment by flyswatter** [comment]
Ah!  A new error in-page:

`inpage.js:24289 Uncaught TypeError: Cannot read property 'blockNumber' of undefined
    at Web3ProviderEngine._inspectResponseForNewBlock (inpage.js:24289)`

**Comment by 2point1creations** [comment]
`wallet.html:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().` is being caused by our 3d engine and has been there for a while prior to this issue.  We also have looping functions leading to etherscan but those were also in working fine prior to this issue.   We have done tests where we remove all of that functionality and the problem persists.

**Comment by 2point1creations** [comment]
Hey guys, just an update. We completely uninstalled and reinstalled the MM extension and all was resolved.   its still a little laggy in the front end but sends, account changes etc are all functioning.  Could be the front end code Dan was talking about making it a bit heavier on the DApp but overall its not a deal breaker.  We're going to refine our code and loosing the api requests to see if we can boost some performance.    Thanks again for taking the time to investigate this.  Really looking forward to future updates.
