### ISSUE TITLE
Request: Make MetaMask work in the Tor Browser

### ISSUE THREAD

**Issue by leafcutterant** [MetaMask/metamask-plugin#1512]
Since MM has a Firefox port now, I tried to use it in Tor Browser. It installed and initialized itself properly, but account creation and restoration doesn't work. After entering a password (or a seed and a password) and pressing the button, a broken image icon pops up for a moment in the foreground, then disappears and the same icon appears permanently next to the menu icon. Also, the menu elements are not responsive.

Could you make MetaMask work in the Tor Browser?

Thank you!

![clipboard01](https://cloud.githubusercontent.com/assets/7106231/26585682/5ab4fcca-453c-11e7-847c-a9730828c6e1.png)

**Comment by tmashuang** [comment]
I have some feedback on this issue. Seems Metamask is incompatible with Firefox 45.9.0, which is the latest version of Tor that I installed.
![tor-firefox](https://cloud.githubusercontent.com/assets/13376180/26653599/6c189b12-4608-11e7-8e9a-4178d5cea03f.png)

**Comment by leafcutterant** [comment]
Sorry, I forgot to mention some details: I used Tor Browser 6.5.2 and MetaMesk 3.7.0.

**Comment by tmashuang** [comment]
The recent Tor Browser 7.0 updated with Firefox 52.1.2 should work with Metamask.

**Comment by leafcutterant** [comment]
Sadly I have to come back to this issue and request a re-opening.

I'm in Tor Browser 7.0.10, using Metamask 3.12.0, and the symptoms are very similar.

The extension responds very slowly and the UI has minor glitches (e.g. icon/picture doesn't load). But the main problem is that I'm unable to use the extension. Every time I try to restore a den or create a new one, the UI becomes unresponsive. I click out, click again on the MM icon, and the small windows that comes up is empty/gray. Only a browser restart can take me back to the initial state.

Metamask also asks me to accept the ToS every time I restart the browser and it forgets the den I tried to create. But this may be party due to my Tor Browser settings (it is set to forget everything when it is closed).

**Comment by TraderAndres** [comment]
Seeing the same issue on Tor 7.5.3 (based on Mozilla Firefox 52.7.3) (32-bit)

**Comment by vbresan** [comment]
Tor 7.5.6, after clicking on the MM icon, small window that comes up is gray. Metamask 4.8.0
