### ISSUE TITLE
general security question

### ISSUE THREAD

**Issue by peteratomic** [MetaMask/metamask-plugin#1515]
When installing the plugin, Chrome issues a warning that Metamask can copy data on all websites. Don't find any options to temporarily disable it when not in use. Seems odd to have to go into chrome://extensions/ just to turn it off.

**Comment by flyswatter** [comment]
There are a couple ways to understand your concern, so let me lay them out:

If you're concerned about the copy/paste permissions, you're right, we don't really use those, we added that to get rid of an Opera store warning, but we could just remove this if we accept giving up on Opera support.

Extensions don't really have a way to "turn themselves off". Extensions can *claim* to be good, but even if we did that, it doesn't really change your security story.

Lastly, we do plan to only "log you in" (expose your account) to sites you deliberately choose to, but while that's functionally similar to what you're describing, it's also pretty different.

Thoughts on how we might address your concern?

**Comment by kumavis** [comment]
> Metamask can copy data on all websites

this is because we need access to the page to inject the web3 api. i agree its scary, and we're asking browser vendors for an alternate api that covers our usecase but doesn't expose user's private data to us.

**Comment by peteratomic** [comment]
This is the concern:

![screen shot 2017-05-30 at 11 47 37 pm](https://cloud.githubusercontent.com/assets/7466182/26606511/7e0489e2-4592-11e7-8156-17c54708af4c.png)

So if there's no way to switch off the app, then without manually disabling the extension, then this reads to me as "if I visit any sensitive website like my bank account, metamask could copy any information on the screen."

It's not that I don't particularly distrust you, it's just, well, that's a fairly terrifying scenario. Honestly makes me wonder why anyone would use it, unless they're strictly using Eth dapps within that browser and nothing else.

**Comment by kumavis** [comment]
> that's a fairly terrifying scenario

i agree! we're also working on a non-extension version that wont have this issue.
another option you can do today is have a chrome profile that you only use for metamask + dapps

![image](https://cloud.githubusercontent.com/assets/1474978/26606763/1fb5a60e-4548-11e7-9b2e-02647f7f890e.png)

**Comment by kumavis** [comment]
feel free to join our slack and ask more questions
