### ISSUE TITLE
Sudden closure while trying to import json file 

### ISSUE THREAD

**Issue by Pac23** [MetaMask/metamask-plugin#1518]
Was trying to import another wallet,the plugin seems to close after clicking on the open file button for importing the json file to import account.

**Comment by tmashuang** [comment]
Browser and OS?

**Comment by Pac23** [comment]
@tmashuang Chrome (64 bit) Ver  58.0.3029.110 ,Windows 7 (64-bit),Windows classic theme(idk why but this could be a thing affecting because ever since i swtiched to this i have had weird issues ranging from network to file transfer speeds)

**Comment by Zanibas** [comment]
Being actively worked on by the chromium team as stated in this issue:
https://github.com/MetaMask/metamask-plugin/issues/1136

**Comment by Pac23** [comment]
but that issue seems to be on Ubuntu and not on windows or osx.

**Comment by visa10** [comment]
call developer tools by right click, on metamask window. It will prevent closing metamasc extention.

**Comment by hialpha** [comment]
The issue still on Windows, just tested on windows 7

**Comment by arsenicks** [comment]
> call developer tools by right click, on metamask window. It will prevent closing metamasc extention.

That worked for me, thanks..

This problem is still hapenning with brave under Linux at least.
Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
