### ISSUE TITLE
Very small max gas limit bug

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1528]
Users have reported a strange error that can appear on the gas limit view since version `3.7.2`:

<img width="343" alt="screen shot 2017-06-01 at 16 35 32" src="https://cloud.githubusercontent.com/assets/542863/26692797/cf7dab12-46b6-11e7-8ee0-c4fa6918fa39.png">

It looks like a problem with our new gas limit logic to me.

**Comment by flyswatter** [comment]
This bug is preventing some users from submitting txs, is a new top priority.

**Comment by flyswatter** [comment]
We've seen in the past that using `BN.muln()` to multiply a BN by a fraction is not safe, but we do it several places in [this file](https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/lib/tx-utils.js).

**Comment by kumavis** [comment]
Yes, good find

**Comment by flyswatter** [comment]
I'm still not sure that's the problem though...

**Comment by flyswatter** [comment]
I wrote a little test to see if `muln` will ever create a dramatically smaller number, and I haven't found one.

```javascript

    it('can multiply large numbers by fractions', function () {
      for (var i = 0; i < 100000; i++) {
        const input = (new BN('4709561')).addn(i)
        const factor = 0.9
        const output = txUtils.muln(input, factor)

        const half = (new BN('2509561')).addn(i)
        assert.ok(output.gt(half), 'output is greater than half')
        assert.ok(output.lt(input), 'output is less than input')
      }
    })
```

I'm more inclined to think the provider replied with an abnormally low gas limit, and so we need to consider the UX when the provider returns a plainly wrong gas limit. Perhaps "never enforce a gas max smaller than the gas min"?

**Comment by Zanibas** [comment]
Pinging @bneiluj to stay in the conversation!

**Comment by flyswatter** [comment]
This has been reported twice, both with a ceiling of `4750`.

**Comment by bneiluj** [comment]
Extra information https://github.com/MetaMask/metamask-plugin/issues/1529
As described in `1529` I was using `MetaMask 3.7.2`
After restarting chrome - I've got Metamask updated to `3.7.3`

Looks like `3.7.3: "Rebuilt to fix cache clearing bug."` fixed this issue ! ;)

**Comment by ralph-pichler** [comment]
Have the same issue now with 3.7.6.

**Comment by Zanibas** [comment]
We haven't had users report on this issue for awhile, so I'm assuming this was due to the ENS reveal logic. Once we see this issue again, we'll address it then.
