### ISSUE TITLE
Unable to import private keys using .json file

### ISSUE THREAD

**Issue by 39otrebla** [MetaMask/metamask-plugin#1536]
Metamask window closes itself as soon as Chrome window looses its focus. 

That said, I am unable to import keys from .json file because as soon as I click "Choose file", a new nautilus window is opened and, as per the above, Chrome looses its focus and MetaMask window closes itself. Quite annoying when used for development with Remix as well.

Ubuntu 16.04
Chrome Version 58.0.3029.110 (64-bit) 
Happens on Chromium as well.

**Comment by tmashuang** [comment]
We currently have an issue open for this and submitted an issue to Chromium. Duplicated #1136

**Comment by flyswatter** [comment]
A little workaround hack is to visit the popup UI in your main browser tab by visiting:
chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/popup.html

**Comment by 39otrebla** [comment]
@flyswatter the workaround works great, thank you!
@tmashuang I apologize for having submitted a duplicate, hope Chromium will fix soon, thank you.

**Comment by ltfschoen** [comment]
in the MetaMask browser plugin i just clicked my account icon and then clicked "Connect Hardware Wallet" and that took me to a chrome-extension://...../home.html#new-account/connect page, where i was then able to click my account icon and choose "Import Account" and then select "JSON File" and then when i clicked "Choose File" it allowed me to choose it (without the window losing focus) and then enter the password to import it successfully
