### ISSUE TITLE
Article on developing Solidity Dapps, and interfacing with Metamask, in BlockGeeks today!

### ISSUE THREAD

**Issue by Tectract** [MetaMask/metamask-plugin#1543]
Hi guys,

Thanks for your help dealing with that compiler issue I was having last week.

My article on developing Solidity smart-contracts was published on BlockGeeks.com today, and features the Metamask plugin very favorably! Thanks for making this awesome tool, I hope you enjoy this article and you can use it to help publicise your tool, freely. Cheers~

"How To Learn Solidity: The Ultimate Ethereum Coding Guide"

https://blockgeeks.com/guides/how-to-learn-solidity/

**Comment by flyswatter** [comment]
Awesome, I'll share this around, thanks for the fresh guide!

(Closing since it's not really an issue :) )
