### ISSUE TITLE
personal.sign parameter ordering seems wrong

### ISSUE THREAD

**Issue by kenshyx** [MetaMask/metamask-plugin#1557]
From this [this](https://github.com/ethereum/go-ethereum/blob/0255ed6335a6bb7fee210ba0ce3326b8669d0f11/console/bridge.go#L132) and [this](https://github.com/ethereum/web3.js/blob/81ab762ff11ab47afed37ac72628ac4ed84328c8/lib/web3/methods/personal.js#L64) it should be `personal.sign(message, account, pwd)`. After playing a while with the web3 injected by metamask it seems it's using `(account, message)`.

**Comment by flyswatter** [comment]
Thank you so much for catching this.  This is pretty bad.

Thinking of ways to fix this while breaking the least possible.  I was thinking we could try to respect existing behavior whne it' like:

```javascript
personalSign(account, message) {
  let correctAccount, correctMessage
  if ( resemblesMessage(account) && resemblesAccount(message) {
    console.warn(`Sorry developers, you should switch the param order, ${LINK_TO_BLOG_POST}`)
    correctAccount = message
    correctMessage = account
  }
  return oldPersonalSign(correctMessage, correctAccount)
}
```

Thoughts?

**Comment by kumavis** [comment]
That sounds pretty good Dan, what's the worst that could happen here? Accidently swapping the values if the message looks like an address?

**Comment by kumavis** [comment]
I guess we could load the addresses and see if there's a match to tell the difference
