### ISSUE TITLE
Coinbase unable to read MetaMask QR Codes

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1558]
Perhaps they changed their QR format.

**Comment by kumavis** [comment]
for coinbase seems they have an `ethereum:` prefix
![image](https://user-images.githubusercontent.com/1474978/27012937-d31d5eb8-4e8e-11e7-9ab2-c31fd4b7b43a.png)

**Comment by kumavis** [comment]
oh shit coinbase seems to incorrectly read the metamask QR code
(reads it as a different address!)

**Comment by kumavis** [comment]
my generic QR code reader shows that it does display the correct address

**Comment by kumavis** [comment]
reported issue to coinbase. incorrect read seems to be on android only, result is a garbage address with an invalid length, so doesnt allow you to send.

it worked when adding `ethereum:` prefix
