### ISSUE TITLE
Block tracker sometimes stops tracking new blocks

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1559]
I'm not completely sure how this happens but sometimes the block tracker simply stops polling.

The story of how this was noticed:

A user reported they were getting transactions failing, and upon looking at it, all their txs were appearing to be fine in the tx approval screen, but the RPCs were rejecting them with:

```
Insufficient funds. Account you try to send transaction from does not have enough funds. Required OMITTED_X_WEI and got: OMITTED_Y_WEI.
```

This seems to be an RPC error, and was the result of the local account balance not having been updated after an out-of-gas error.

Upon trying to check my own local polling, I opened the background process, and found that mine too had stopped polling. I switched providers and back again, and that fixed the problem, and suggested the same for the user, and it fixed their problem too.

**Comment by Zanibas** [comment]
Maybe addressed by #1586 #1587
