### ISSUE TITLE
Tokens not showing up in Metamask account

### ISSUE THREAD

**Issue by darkcoindavey** [MetaMask/metamask-plugin#1561]
Hi there 

I sent some ERC20 compliant tokens from Myetherwallet to Metamask.

They have left my wallet but don't show up in Metamask. Can you help please

**Comment by frankiebee** [comment]
We do not show token balances at the moment

**Comment by frankiebee** [comment]
but you can got to wallet.ethereum.org to see them

**Comment by darkcoindavey** [comment]
Thanks frankiebee, I'll try that...

**Comment by frankiebee** [comment]
closing in favor of #175

**Comment by darkcoindavey** [comment]
Hi Frankie,

I can see tokens in wallet.ethereum.org   Thanks for your help. I want to transfer them to etherdelta.github and need ETH to pay for gas. I sent 1.1 ETH to my address at wallet.ethereum.org but it's not showing up there, or on metamask. It is showing up at my address in etherscan though, so the transaction has gone through. Do I need to refresh metamask for it to show my balance of 1.1 ETH?

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/62391153-ed80e200-b518-11e9-894a-11479e3cb033.png)

**Comment by robomantis19** [comment]
how do i get my token coins out of metamask if they aren't showing up
