### ISSUE TITLE
My ETH is not showing up in metamask from coinbase transfer

### ISSUE THREAD

**Issue by LEscobar-Driver** [MetaMask/metamask-plugin#1562]
https://etherscan.io/address/0xb40bdea8e35068e5250725089e46ab816bf3197a

I sent 1.1 ETH from coinbase to my metamask chrome extension. They are present in etherscan but are not present in metamask?? Have I lost my ETH? I copied my address on metamask from the QR code copy mechanism.

**Comment by frankiebee** [comment]
@LEscobar-Driver are you on main net in meta mask? 
<img width="444" alt="screen shot 2017-06-07 at 2 42 38 pm" src="https://user-images.githubusercontent.com/11225267/26906275-fa43f42a-4ba0-11e7-8418-5be747e777d1.png">

PS: we do not show incoming transactions just ones sent from within metamask. when you send ether to a metamask account the balance should change
