### ISSUE TITLE
Balance of my account shows up in etherscan but not on Metamask

### ISSUE THREAD

**Issue by darkcoindavey** [MetaMask/metamask-plugin#1563]
Hi, 

I have an ETH balance in etherscan.io of 1.1 ETH that shows up when I click on the i symbol in Metamask (to view account on Etherscan). 

But my Metamask account shows 0 ETH. 

Why is this? Any help will be greatly appreciated. Thanks

**Comment by tmashuang** [comment]
Are you on Mainnet?
<img width="444" alt="26906275-fa43f42a-4ba0-11e7-8418-5be747e777d1" src="https://user-images.githubusercontent.com/13376180/26916365-f48c732a-4bde-11e7-811c-52390b29baee.png">

If so, could you provide your logs?
https://github.com/MetaMask/faq/blob/master/LOGS.md

**Comment by darkcoindavey** [comment]
Hi Thomas, thanks for reply. I'm away from my computer for about 12 hours
and will check as soon as I'm back.

Cheers

Dave

**Comment by darkcoindavey** [comment]
Hi Thomas,

Yes on mainnet. Will provide logs

**Comment by darkcoindavey** [comment]
Got this from popup log:

popup.js:26538 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by darkcoindavey** [comment]
Lots of errors in Chrome. Developer mode wasnt on, it is now.

Errors pasted below. Thanks

MetaMask initialization complete.
3background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
3background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:39443 ethquery failure Objectmethod: "eth_getBlockByNumber"params: Array(2)__proto__: Object SyntaxError: Unexpected end of JSON input
background.js:38482 SyntaxError: Unexpected end of JSON input
_callee5$ @ background.js:38482
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:39443 ethquery failure Object SyntaxError: Unexpected end of JSON input
background.js:2782 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2782
background.js:39443 ethquery failure Object SyntaxError: Unexpected end of JSON input
background.js:2782 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2782
background.js:39443 ethquery failure Object SyntaxError: Unexpected end of JSON input
background.js:2782 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2782
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:39443 ethquery failure Object SyntaxError: Unexpected end of JSON input
background.js:38482 SyntaxError: Unexpected end of JSON input
_callee5$ @ background.js:38482
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:39443 ethquery failure Object SyntaxError: Unexpected end of JSON input
background.js:2782 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2782
background.js:39443 ethquery failure Object SyntaxError: Unexpected end of JSON input
background.js:2782 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2782
background.js:39443 ethquery failure Object SyntaxError: Unexpected end of JSON input
background.js:2782 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2782
5background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
5background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
3background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
4mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:39443 ethquery failure Object TypeError: Failed to fetch
background.js:38482 TypeError: Failed to fetch
_callee5$ @ background.js:38482
background.js:39443 ethquery failure Object TypeError: Failed to fetch
background.js:2782 TypeError: Failed to fetch
(anonymous) @ background.js:2782
background.js:39443 ethquery failure Object TypeError: Failed to fetch
background.js:65171 TypeError: Failed to fetch
(anonymous) @ background.js:65171
2mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
2mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
mainnet.infura.io/metamask Failed to load resource: net::ERR_INTERNET_DISCONNECTED
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
3background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
mainnet.infura.io/metamask Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
background.js:39443 ethquery failure Object TypeError: Failed to fetch
background.js:38482 TypeError: Failed to fetch
_callee5$ @ background.js:38482
mainnet.infura.io/metamask Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
background.js:39443 ethquery failure Object TypeError: Failed to fetch
background.js:38482 TypeError: Failed to fetch
_callee5$ @ background.js:38482
www.cryptonator.com/api/ticker/eth-USD Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
2background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:3711 Uncaught TypeError: Cannot read property 'gasLimit' of null
    at background.js:3711
    at background.js:39446
    at Proxy.Web3ProviderEngine._inspectResponseForNewBlock (background.js:58271)
    at background.js:58249
    at background.js:8870
    at replenish (background.js:8750)
    at iterateeCallback (background.js:8740)
    at background.js:8886
    at resultObj.id (background.js:58229)
    at background.js:8961
background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:1637 warn was used no cb provided
warn @ background.js:1637
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:1637 warn was used no cb provided
warn @ background.js:1637
background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:42612 (node) warning: possible EventEmitter memory leak detected. 31 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42612
background.js:42618 console.trace
EventEmitter.addListener @ background.js:42618
3background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:1637 warn was used no cb provided
warn @ background.js:1637
background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:1637 warn was used no cb provided
warn @ background.js:1637
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:1637 warn was used no cb provided
warn @ background.js:1637
2background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
background.js:4242 Error in RPC response:
 Object
logger @ background.js:4242
background.js:1637 warn was used no cb provided
warn @ background.js:1637
6background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
www.cryptonator.com/api/ticker/eth-USD Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567
www.cryptonator.com/api/ticker/eth-USD Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
7background.js:567 MetaMask - Failed to query currency conversion.
(anonymous) @ background.js:567

**Comment by tmashuang** [comment]
Sometimes switching from mainnet to testnet and back or restarting MetaMask/the browser fixes things. We currently have issues open that might be related to this and will be monitoring them closely.

**Comment by darkcoindavey** [comment]
Ok thanks....

switching from mainnet to testnet and back DID fix it. Now showing my balance in Metamask.

Thanks Thomas

**Comment by n8twj** [comment]
I realize this is very old, but possibly relevant to someone searching.  If you had set google chrome to limit the access of MetaMask to only talk to say myetherwallet.com - this same scenario will play out...  Make sure the MetaMask extension can read and change site details for all sites.

**Comment by ikhana** [comment]
> I realize this is very old, but possibly relevant to someone searching. If you had set google chrome to limit the access of MetaMask to only talk to say myetherwallet.com - this same scenario will play out... Make sure the MetaMask extension can read and change site details for all sites.

Can't figure out how I can do this ? @n8twj

**Comment by n8twj** [comment]
@ikhana Perhaps things have been updated by now...   But If you Right click on the metamask icon... click on This Can Read And Change Data... If you restrict to anything other than "On All Sites" - you may have communication issues.

**Comment by ikhana** [comment]
@n8twj yeah it is so for now too. Solved thank you
