### ISSUE TITLE
ENS  Backward domain!

### ISSUE THREAD

**Issue by Rishat1980** [MetaMask/metamask-plugin#1564]
I buy the domain name eth in
Ropsten Test Net shows that the domain belongs to me, and in
Ethereum Main Net shows someone else's account! What is the problem ?

**Comment by tmashuang** [comment]
Ethereum Main Net is real money/ether and Ropsten Test Net is monopoly money/ether.

**Comment by Rishat1980** [comment]
Ok, Ethereum Main Net у меня есть реальные деньги и их списывают за имена, когда я их бронирую в 
Ropsten Test Net.
