### ISSUE TITLE
Metamask account not unlocking

### ISSUE THREAD

**Issue by jl2fa** [MetaMask/metamask-plugin#1566]
When I attempt to unlock the account, the GUI freezes at loading, like so below:
![image](https://user-images.githubusercontent.com/9888717/26943346-3ef633f0-4c53-11e7-9caf-2f62abd5ba0b.png)

I lost my seed phrase; if I reinstall the extension, do I lose the associated account?

Thanks in advance for the help.

**Comment by kumavis** [comment]
> I lost my seed phrase; if I reinstall the extension, do I lose the associated account?

yes. dont uninstall. please join our slack so we can try to debug this together (including sharing private info). http://slack.metamask.io/

**Comment by kumavis** [comment]
![image](https://user-images.githubusercontent.com/1474978/26944401-5fabcf3a-4c3d-11e7-9c73-4f81544607b4.png)

**Comment by kumavis** [comment]
```
i think i have a guess as to why it didn't work

[12:43] 
when i reinstalled metamask

[12:44] 
i got the metamask plugin chrome tab opened

[12:44] 
on my other device using chrome

[12:44] 
and that other device with chrome has its own metamask
```

**Comment by kumavis** [comment]
solved by:
- recover "wallet" data from localstorage
- manual install of https://github.com/MetaMask/metamask-plugin/releases/tag/v3.4.0
- update json blob below with "wallet" value
- overwrite metamask 3.4.0 localstorage with edited json blob
- restart, log in, ignore shown account, `menu > settings > reveal seed phrase`
- reinstall normal chrome store metamask, recover from seed phrase

```json
{
  "meta": {
    "version": 10
  },
  "data": {
    "config": {
      "provider": {
        "type": "testnet"
      }
    },
    "wallet": "...",
    "NoticeController": {
      "noticesList": [
        {
          "read": true,
          "date": "Thu Feb 09 2017",
          "title": "Terms of Use",
          "body": "hi",
          "id": 0
        }
      ]
    },
    "CurrencyController": {
      "currentCurrency": "USD",
      "conversionRate": 0,
      "conversionDate": "N/A"
    },
    "PreferencesController": {
      "frequentRpcList": [],
      "selectedAddress": "0xa5d5ca20b5a8a33bcf9b25ba865a39a228757be2"
    },
    "seedWords": null
  }
}
```

**Comment by jl2fa** [comment]
thanks for your help aaron :)
