### ISSUE TITLE
Transaction goes through but says it failed  

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-plugin#1567]
seems like something in the retry logic and the pending to confirmed logic
<img width="396" alt="screen shot 2017-06-08 at 10 52 01 am" src="https://user-images.githubusercontent.com/11225267/26943788-9fdb2d14-4c3b-11e7-8804-6d7db05f2acf.png">

**Comment by frankiebee** [comment]
#1568 how ever resolving this issue is unrelated the image has something i find worth noting 
it should go
```
1,  
0, 
```
but in their instance it goes:
```
0,
1 failed (gave up submitting tx)```

**Comment by CurrencyTycoon** [comment]
Experiencing this problem problem. Just thought I give extra info:
When I hover over the 'failed' transaction, it says "Gave up submitting tx".
I have multiple accounts, and other accounts work fine. Tried re-starting Chrome. The balance for the account is showing correct, however, still marking the transaction as error.
