### ISSUE TITLE
Transaction nonce is too low

### ISSUE THREAD

**Issue by dasdqwdqw** [MetaMask/metamask-plugin#1569]
"transaction nonce is too low. Try incrementing the nonce" is the error message i am getting. I cannot make a single transaction all day, tried adjusting the gas price and limit to no avail.  Please assist, thanks.

**Comment by kumavis** [comment]
please reset metamask by switching to testnet and back
then try again and let us know

**Comment by dasdqwdqw** [comment]
It worked, thank you!

**Comment by andrewo73** [comment]
Hi I am getting the same error. When I check the TX the nonce is 0. Should be 3 though? Any help

**Comment by worldofprasanna** [comment]
@kumavis It worked like charm 👍 But what was the issue ?
