### ISSUE TITLE
Seed not working

### ISSUE THREAD

**Issue by tym55** [MetaMask/metamask-plugin#1576]
Hi there Meta 

I love the platform. However i am have having difficulties getting my account imported with the seed. 

I dont know why my account was suddenly gone from my chrome addon metamask , I hadnt  uninstalled it but it didnt show up it said create account or import.

So I pushed import and typed in the seed and a new password which it asked me to do and it just loads for a second and then does nothing. 

I did not export the private keys and the seed is not responding. Could you please help me solve this issue.

Thanks

Hit

**Comment by tmashuang** [comment]
What browser and version are you using? What OS are you using? What version of Metamask? Any errors in the console?

**Comment by kumavis** [comment]
Please check both popup and background logs
https://github.com/MetaMask/faq/blob/master/LOGS.md
Thanks

**Comment by tym55** [comment]
Thank you all, i am sorry i had installed it on mozzilla firefox and not chrome, does this make any difference in my issue? The log instructions are not working.

**Comment by tym55** [comment]
I have installed chrome and tried importing the seed there with the same issue, however at least i can provide the logs. Shall i post the logs here publicly?

**Comment by tym55** [comment]
![image](https://user-images.githubusercontent.com/29316351/27000909-84637424-4dbc-11e7-8176-30b9a643ac19.png)

**Comment by tmashuang** [comment]
Mozilla does not provide adequate debugging steps. The logs should not have any private information in them. It will help us see the steps if your account was created or if there was an error with account creation.

**Comment by flyswatter** [comment]
You could optionally join our slack and DM logs to one of our team members privately. It shouldn't have any personal info, but it's still safer to not post the logs publicly. (The logs could include your addresses, past transactions, and even your encrypted vault.)

**Comment by tym55** [comment]
Thank you, will someone inform me how I can solve this issue or if those logs say anything? Is this a security breach? How can I reach a team member privately for help?

**Comment by tmashuang** [comment]
Join our slack channel, metamask.slack.com. DM me, same username as github.

**Comment by tym55** [comment]
Hi tmashuang,

Thank you,

I have created a slack team but I still can`t log in to your slack team, it says I need to contact the team administration for an invitation.

**Comment by kumavis** [comment]
@tmashuang has to be `http` for the current slack autoinviter - its the only thing on heroku
@tym55  http://slack.metamask.io/

**Comment by tym55** [comment]
Thank you for all the hasty support, I have contacted tmashuang on the Slack channel

**Comment by flyswatter** [comment]
This was a problem with seed phrase input, and is addressed in #1584.
