### ISSUE TITLE
funds and wallet disappear 

### ISSUE THREAD

**Issue by jamesweb666** [MetaMask/metamask-plugin#1580]
i had my wallet with 61 veri, restart computer and when i went to login , ask me for a new password , so i did but it was to open another one, so i forgot and delete evrything ( account  ) and went to restore with my passprhase, bamm nothing there, if i press check the network from their, nothing, its not on the network and my account is on the main ethereum network and i also try with my keyfile , nothing there

**Comment by flyswatter** [comment]
That's very strange, there are a number of details that could help us sort this out for you.

First of all, I take it you had your original seed phrase with your 61 veri? As long as you recorded the phrase correctly, we should be able to recover that account.

Was the account with the 61 veri your first MetaMask account? If it was not the first account, you may need to press the `+` (add account) button until you reveal/re-generate the missing account. MetaMask will always generate the same accounts in the same order from the same seed phrase.

That's a pretty good guess of what's wrong here, so go ahead and make sure you've tried generating the accounts before I try debugging this further.

Another follow-up question that comes to mind: How long ago did you first install MetaMask?

**Comment by jamesweb666** [comment]
Yes ,at first i didnt work but i just retry and forget everything and redo it wiith passphrase and its back,you have no idea the stresss i just got,by the way you supoort not good,you should have a support email, i went crazy earlier until someane gave me that email online, in case of problem its not your bit that help on the install that will help   , look all good an max tomorrow ill tell everyone its now ok .     But again you should do sonething for your supoort , your site really unclear on that


Envoyé depuis ma tablette Samsung
-------- Message d'origine --------De : Dan Finlay <notifications@github.com> Date : 17-06-12  12:33 AM  (GMT-05:00) À : MetaMask/metamask-plugin <metamask-plugin@noreply.github.com> Cc : jamesweb666 <websolutiona@gmail.com>, Author <author@noreply.github.com> Objet : Re: [MetaMask/metamask-plugin] funds and wallet disappear (#1580) 
That's very strange, there are a number of details that could help us sort this out for you.
First of all, I take it you had your original seed phrase with your 61 veri? As long as you recorded the phrase correctly, we should be able to recover that account.
Was the account with the 61 veri your first MetaMask account? If it was not the first account, you may need to press the + (add account) button until you reveal/re-generate the missing account. MetaMask will always generate the same accounts in the same order from the same seed phrase.
That's a pretty good guess of what's wrong here, so go ahead and make sure you've tried generating the accounts before I try debugging this further.
Another follow-up question that comes to mind: How long ago did you first install MetaMask?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MetaMask/metamask-plugin","title":"MetaMask/metamask-plugin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MetaMask/metamask-plugin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@flyswatter in #1580: That's very strange, there are a number of details that could help us sort this out for you.\r\n\r\nFirst of all, I take it you had your original seed phrase with your 61 veri? As long as you recorded the phrase correctly, we should be able to recover that account.\r\n\r\nWas the account with the 61 veri your first MetaMask account? If it was not the first account, you may need to press the `+` (add account) button until you reveal/re-generate the missing account. MetaMask will always generate the same accounts in the same order from the same seed phrase.\r\n\r\nThat's a pretty good guess of what's wrong here, so go ahead and make sure you've tried generating the accounts before I try debugging this further.\r\n\r\nAnother follow-up question that comes to mind: How long ago did you first install MetaMask?"}],"action":{"name":"View Issue","url":"https://github.com/MetaMask/metamask-plugin/issues/1580#issuecomment-307687964"}}}

**Comment by flyswatter** [comment]
Sorry about that. We are adding more support infrastructure already, and will be adding links to it everywhere, like on the site.
