### ISSUE TITLE
Can't enter JSON, plugin window closes every time.

### ISSUE THREAD

**Issue by kusayuzayushko** [MetaMask/metamask-plugin#1605]
When i'm trying to unlock my local wallet and picking JSON file, plugin window loose focus and closes. 
OS: linux. 
Window manager: i3wm

**Comment by tmashuang** [comment]
Duplicate of #1536 and 1136. A good workaround is to open the extension url, chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html, directly in a new tab and import through the tab.

**Comment by magum** [comment]
Please explain this "open the extension url, chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html, directly in a new tab" in details

**Comment by danfinlay** [comment]
What he's describing is the same workaround as is described in this article:
https://support.metamask.io/kb/article/9-changing-metamasks-popup-font-size-chrome

It's a URL, you visit it like a website.

**Comment by magum** [comment]
Thanx, I got it already). This url looks like abracadabra.

**Comment by danfinlay** [comment]
Yeah, probably would've helped to put it on its own line like 
`chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html`

Or maybe clarifying that `nkbihfbeogaeaoehlefnkodbefgpgknn` is our chrome store ID first.
