### ISSUE TITLE
block-tracker in UI not refreshed on network change.

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1608]
Steps:
- Select a network with a low block number
- Close popup
- Open popup
- Open UI logs
- Select a network with a higher block number.

Result:
the UI's `eth-block-tracker` will begin walking the blockchain from the previous network's block number to the new network's latest block number.

**Comment by flyswatter** [comment]
Will fix as part of #1603.

**Comment by flyswatter** [comment]
Actually this is a little weird, I might like a consultation on how to approach this from @kumavis or @frankiebee.

**Comment by frankiebee** [comment]
So if you subscribe to the network changing you could stop the current block tracker and create a new one for the new network. and reQuery all the token stuffs 
and possibily in the ui call a force update?
 https://facebook.github.io/react/docs/react-component.html#forceupdate

**Comment by flyswatter** [comment]
I think I found the problem, the block tracker was part of the token view, so cleaning up the tracker was part of deallocating the old tracker on network change, so this is really just part of the other issue.
