### ISSUE TITLE
Unable to allocate transaction entry, saving wrong transaction in chrome history

### ISSUE THREAD

**Issue by dasdqwdqw** [MetaMask/metamask-plugin#1613]
Hi, i've used metamask to bid on an ENS name and got "Unable to allocate transaction entry" after a repeated attempt i successfully bid, however the amount that was stored in the browser history(and exported in .JSON file) is slightly higher than the real transaction (as seen in etherscan). So when i try to reveal my bid,  i am unable to as the transaction that was saved was the invalid one.
Please help me as i will loose my ETH.
Thank you in advance

**Comment by flyswatter** [comment]
I would maybe try editing the JSON file to the correct value just in case that works.

You should contact the ENS Ðapp team for real support on this, this regards their product.
https://github.com/ethereum/ens-registrar-dapp/issues
