### ISSUE TITLE
Eth not showing up in metamask. 

### ISSUE THREAD

**Issue by xxxROACHxxx** [MetaMask/metamask-plugin#1633]
I sent eth from coinbase to metamask. It's confirmed on coinbase as having been sent. Never showed up on the other end. I noticed that metamask was by default set on test net. Have I lost all that ether?
my receiving metamask address is 0x8FEAF525A56342599ed077C1fB430CbC658f49D3

**Comment by tmashuang** [comment]
Confirming that you do not see your 26 Ether on Mainnet?

**Comment by xxxROACHxxx** [comment]
Yes thank you... I almost had a heart attack. For future reference. Is there something on meta that I should avoid.  By that I mean something that would cause me to lose ether if I'm incredibly stupid.... which i'm prone to doing often

**Comment by tmashuang** [comment]
Just validate the address that you're sending to and using etherscan to monitor the transactions.

**Comment by xxxROACHxxx** [comment]
Ive tried sending 3 transactions and none go through. This is the latest
transaction. Is there something wrong?Transaction
 0x88f084b35de7999342c310c39186851e203222adf9ca57ddc754b01c7aa07311

**Comment by flyswatter** [comment]
Yeah the blockchain is clogged up enormously at the moment from the Status sale. It could take hours before activity resumes like normal. https://twitter.com/myetherwallet/status/877233648457535488
