### ISSUE TITLE
i lost my private keys 

### ISSUE THREAD

**Issue by rerori** [MetaMask/metamask-plugin#1640]
i reinstall metamask because "failed: gave up submitting tx" error.

i think i just do "unlock" using my passward. after reinstall.

but program need private key..

i know just address and passward this account... 

how can i do? 30eth in this wallet. 

0x088C3E4B3E0c8Fc1197136e1dECdd02504992174

**Comment by Zanibas** [comment]
Did you write down your seed words anywhere?

**Comment by rerori** [comment]
i backup my email first. but i think it's dangerous from hacking email... so i deleted it.

**Comment by Zanibas** [comment]
Do you mean you saved your seed words in an email you sent? Is there anywhere else you could've saved those seed words?

If you do not have the seed words, we cannot help you, unfortunately. Seed words are the thing we ask users to keep above all else. We regret your loss, but sadly we cannot help you further--we do not have the ability to restore access to that account without a private key or a seed word.

**Comment by rerori** [comment]
ok.. thank you.

**Comment by TonyVernon20** [comment]
There are a lot of untrue recommendations and impostors, its hard to tell who is legit. If you have been scammed by fake crypto investors, lost money to scammers, I refer you to contact (cryptospamhacker@gmail .com) they will surely help you out. Took me long to find them.
