### ISSUE TITLE
Metamask not recognising Password + Lost Wallet keys!

### ISSUE THREAD

**Issue by ramutasu** [MetaMask/metamask-plugin#1647]
Hello,

My account was working well last night, I go to log in this morning, the computer has turned off and upon restarting, metamask doesn't recognise my password (definitely the right password). 
Plus I lost my wallet keys.

I realise this is my own fault, but is there anything I can do to regain access now?!

**Comment by tmashuang** [comment]
Restore from seed phase.

**Comment by ramutasu** [comment]
Wallet keys / seed phrase - are lost...

**Comment by tmashuang** [comment]
Unfortunately, we are not able to restore accounts when users do not have their seed phrase.

**Comment by flyswatter** [comment]
If you still have MetaMask installed, and really have the right password, we should be able to help you decrypt this vault. I'm boarding a plane, so can't help yet, but keep it installed.

**Comment by ramutasu** [comment]
that's a fucking kick in the teeth.

too late.

thanks anyway

**Comment by Jamshd** [comment]
Hello sir,

I forgot my password to Metamask. I don't know my seedphrase. Can you help me please?

**Comment by danfinlay** [comment]
@Jamshd for individual support, please email support@metamask.io
