### ISSUE TITLE
private key recovery

### ISSUE THREAD

**Issue by rerori** [MetaMask/metamask-plugin#1650]
i ask last night about issue 1640 

"i lost my private keys - https://github.com/MetaMask/metamask-plugin/issues/1640"

and then i have new questions.

if my compute backup before metamask reinstall, private key recovered??

**Comment by flyswatter** [comment]
Yes, possibly! Save that backup. I'm getting on a plane, will help more soon. You're looking for the file where Chrome saves extension data on your operating system.

**Comment by rerori** [comment]
... i have not backup extension file. i didnt backup that file. 

i mean my computer hdd disk get back before reinstall metamask.

is it possble?

..sorry about my poor english.

 i need your help please.

**Comment by flyswatter** [comment]
I am boarding a plane. Save your backup. It may be possible.

**Comment by rerori** [comment]
i ask some date recovery company.. they said it is not possible to get back my computer before reinstall.

you needs metamask chrome extension before reinstall? right?

**Comment by DavidRomero1984** [comment]
No recuerdo mi contraseña de pagos. Que debo hacer para recuperarla?
