### ISSUE TITLE
ShapeShift...

### ISSUE THREAD

**Issue by gn0mee** [MetaMask/metamask-plugin#1651]
I was buying 0.5 ETH with ShapeShift(BTC->ETH) but I removed my metamask accidentally when ShapeShift 
 is working.
So I reinstalled metamask and imported my wallet.
But there was nothing in HISTORY.
I think I lost my ETH how can I find my ETH.
Please help me.

**Comment by flyswatter** [comment]
History only shows outgoing transactions currently. Check on a block explorer to see if the funds were ever sent in from Shapeshift. If not, talk to them.

**Comment by tmashuang** [comment]
If the Eth was not deposited into your account and not refunded into your BTC refund address, contact Shapeshift  to find the status of your transaction.

**Comment by gn0mee** [comment]
Okay, I will contact Shapeshift right away.
Thank you very much.
