### ISSUE TITLE
Looking for a quick fix 

### ISSUE THREAD

**Issue by cobyrne09** [MetaMask/metamask-plugin#1653]
Sorry to use this message board for potentially the wrong reason. I am running the metamask chrome extension and am getting the "transaction gas price is too low. There is another transaction with the same nonce..."  message when I have a bunch of pending transactions (and a bunch of repeat transactions). All of the pending transactions are from about a day ago, and show "Unable to locate Transaction entry" on ethereum scan and are from when ethereum was backed up. Increasing the gas price does nothing. Is there a way to reset this mess and send the transactions again or increase the nonce? I unfortunately have some bids that need to be revealed shortly. Thanks!

**Comment by tmashuang** [comment]
Some quick fixes for nonce issues are to switch networks, restore account with seed phrase, or disable/enable Metamask.

**Comment by flyswatter** [comment]
Thomas is correct, you will then need to re-submit the transactions that never went through.

We'll be improving this nonce issue soon, you can follow in #1127

**Comment by SteffenLanger** [comment]
If anyone finds this through Google, here is how MetaMask solves the issue today: https://metamask.helpscoutdocs.com/article/36-resetting-an-account

In essence, there is a [Reset Account] button in the settings.
