### ISSUE TITLE
On the Etherscan I get :"Sorry, we are Unable to locate the Transaction entry."

### ISSUE THREAD

**Issue by jsal45** [MetaMask/metamask-plugin#1672]
Hello, I've sent 4 transaction on my MetaMask, and all I get is failed & on the Etherscan I get :"Sorry, we are Unable to locate the Transaction entry." Three of those transactions have a (failed) in red. 

popup.js:26538 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning	@	popup.js:26538

module.exports = shallowEqual;
},{}],176:[function(_dereq_,module,exports){
(function (process){
/**
 * Copyright 2014-2015, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 */

'use strict';

var emptyFunction = _dereq_('./emptyFunction');

/**
 * Similar to invariant but only logs a warning if the condition is not met.
 * This can be used to log issues in development environments in critical
 * paths. Removing the logging code for production environments will keep the
 * same logic and follow the same code paths.
 */

var warning = emptyFunction;

if (process.env.NODE_ENV !== 'production') {
  (function () {
    var printWarning = function printWarning(format) {
      for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
        args[_key - 1] = arguments[_key];
      }

      var argIndex = 0;
      var message = 'Warning: ' + format.replace(/%s/g, function () {
        return args[argIndex++];
      });
      **if (typeof console !== 'undefined') {
        console.error(message);**
      }
      try {
        // --- Welcome to debugging React ---
        // This error was thrown as a convenience so that you can use this stack
        // to find the callsite that caused this warning to fire.
        throw new Error(message);
      } catch (x) {}
    };

    warning = function warning(condition, format) {
      if (format === undefined) {
        throw new Error('`warning(condition, format, ...args)` requires a warning ' + 'message argument');
      }

      if (format.indexOf('Failed Composite propType: ') === 0) {
        return; // Ignore CompositeComponent proptype check.
      }

      if (!condition) {
        for (var _len2 = arguments.length, args = Array(_len2 > 2 ? _len2 - 2 : 0), _key2 = 2; _key2 < _len2; _key2++) {
          args[_key2 - 2] = arguments[_key2];
        }

        printWarning.apply(undefined, [format].concat(args));
      }
    };
  })();
}

module.exports = warning;
}).call(this,_dereq_('_process'))
},{"./emptyFunction":161,"_process":22}],177:[function(_dereq_,module,exports){
module.exports = identity;

/**
 * Set a mat4 to the identity matrix
 *
 * @param {mat4} out the receiving matrix
 * @returns {mat4} out
 */
function identity(out) {
    out[0] = 1;
    out[1] = 0;
    out[2] = 0;
    out[3] = 0;
    out[4] = 0;
    out[5] = 1;
    out[6] = 0;
    out[7] = 0;
    out[8] = 0;
    out[9] = 0;
    out[10] = 1;
    out[11] = 0;
    out[12] = 0;
    out[13] = 0;
    out[14] = 0;
    out[15] = 1;
    return out;
};
},{}],178:[function(_dereq_,module,exports){
module.exports = invert;

/**
 * Inverts a mat4
 *
 * @param {mat4} out the receiving matrix
 * @param {mat4} a the source matrix
 * @returns {mat4} out
 */

**Comment by tmashuang** [comment]
Try switching networks and back. Afterwards, try resending.

**Comment by jsal45** [comment]
Thank you. That was spot on. It worked.

**Comment by Clermont1** [comment]
@tmashuang Hey, same issue for me (using metamask for chrome - which I'm completely new to) thru Etherdelta, however, your suggestion to @Jsal45 was over my head.  Can you explain or do a simple walk-through for the layman?  Thank you! much appreciated.
