### ISSUE TITLE
EOS ICO, 

### ISSUE THREAD

**Issue by cryptcoinalt** [MetaMask/metamask-plugin#1673]
I have used MM to do the ICO EOS. sent some ETH but at no point did it ask me to export private key!  I have sent the ETH and it shows in the interface my ETH submitted and my potential EOS obtained. 
When do i give my private key? Is this to claim the EOS and transfer them?

**Comment by Zanibas** [comment]
@cryptcoinalt is there a public guide out there explaining the EOS sale and why it needs your private key? We can help you move forward if we can see that information!

**Comment by flyswatter** [comment]
Basically no one should ever need your private key. That's why it's called private. It is the keys to your account, don't pass them out lightly.

**Comment by flyswatter** [comment]
Maybe you're asking about keeping an account backup? Your seed words do that.

Please link to the instructions you're asking from. Until then, I'm just closing his.
