### ISSUE TITLE
Parity Chrome extension breaks MetaMask Chrome plugin

### ISSUE THREAD

**Issue by thehighfiveghost** [MetaMask/metamask-plugin#1679]
Getting reports from several users of Melon (running on Kovan testnet) that when the Parity extension is installed, the MetaMask plugin does not work with the Kovan testnet, even if Parity is currently running on the Ethereum mainnet.

**Comment by flyswatter** [comment]
Yes, they both inject competing web3 APIs, there's not a good way to run them both at once that I know of. Would require one extension to do extra work to yield its web3 to the other.
