### ISSUE TITLE
help help

### ISSUE THREAD

**Issue by guito10** [MetaMask/metamask-plugin#1693]
I need help I created a wallet in metamask with eth to buy eos, however I uninstalled and reinstalled metamask, but now I can not login because I do not remember the question, what should I do, my money is there and I can not access I need help

**Comment by guito10** [comment]
I need help I created a wallet in metamask with eth to buy eos, however I uninstalled and reinstalled metamask, but now I can not login because I do not remember the question, what should I do, my money is there and I can not access I need help

**Comment by guito10** [comment]
I have proof that I sent eth from poloniex to metamask, but now I can no longer access my account, I did not know the question, so I did not save what I should do, please I need help

**Comment by flyswatter** [comment]
Did you back up your seed phrase? The seed phrase, when you first set up MetaMask, is the only way to restore your accounts. If you didn't back it up, there's nothing we can do to help you.

**Comment by guito10** [comment]
No I did not save the sentence, please there must be some means to help me, my money is there! And the ones I bought? Was it all lost?



________________________________
De: Dan Finlay <notifications@github.com>
Enviado: quarta-feira, 28 de junho de 2017 21:20
Para: MetaMask/metamask-plugin
Cc: guito10; Author
Assunto: Re: [MetaMask/metamask-plugin] help help (#1693)


Did you back up your seed phrase? The seed phrase, when you first set up MetaMask, is the only way to restore your accounts. If you didn't back it up, there's nothing we can do to help you.

**Comment by flyswatter** [comment]
Do you maybe have regular computer backups, over the time you had MetaMask installed?

**Comment by guito10** [comment]
I tried to back up I did not get it, do not hit the date, please help me


________________________________
De: Dan Finlay <notifications@github.com>
Enviado: quarta-feira, 28 de junho de 2017 21:24
Para: MetaMask/metamask-plugin
Cc: guito10; Author
Assunto: Re: [MetaMask/metamask-plugin] help help (#1693)


Do you maybe have regular computer backups, over the time you had MetaMask installed?

**Comment by flyswatter** [comment]
I'm sorry, there's nothing I can do to help you. You deleted your vault.

**Comment by guito10** [comment]
There must be some way to track my tokens or my wallet, please.



________________________________
De: Dan Finlay <notifications@github.com>
Enviado: quarta-feira, 28 de junho de 2017 21:24
Para: MetaMask/metamask-plugin
Cc: guito10; Author
Assunto: Re: [MetaMask/metamask-plugin] help help (#1693)


Do you maybe have regular computer backups, over the time you had MetaMask installed?

**Comment by flyswatter** [comment]
If you still have your account address, you can go on a block explorer to look at everything you lost, but without the seed phrase or private keys, all of that is lost.

**Comment by guito10** [comment]
Contract address 0xd0a6e6c54dbc68db5db3a091b171a77407ff7ccf
Ethereum account 0x965d2bb2f11c250675ee7935544441b94b230b5e


eos



help please


________________________________
De: Dan Finlay <notifications@github.com>
Enviado: quarta-feira, 28 de junho de 2017 21:26
Para: MetaMask/metamask-plugin
Cc: guito10; Author
Assunto: Re: [MetaMask/metamask-plugin] help help (#1693)


Closed #1693<https://github.com/MetaMask/metamask-plugin/issues/1693>.

**Comment by flyswatter** [comment]
Yes, I can see in here that you sent 0.26... ether into this account, and then sent several small transactions into the EOSCrowdsale. If you lost the private keys, you lost that.

https://etherscan.io/address/0x965d2bb2f11c250675ee7935544441b94b230b5e

**Comment by guito10** [comment]
Yes, that's right, you managed to identify, please help me man! I can not lose that money! Give me a hand please


________________________________
De: Dan Finlay <notifications@github.com>
Enviado: quarta-feira, 28 de junho de 2017 21:30
Para: MetaMask/metamask-plugin
Cc: guito10; Author
Assunto: Re: [MetaMask/metamask-plugin] help help (#1693)


Yes, I can see in here that you sent 0.26... ether into this account, and then sent several small transactions into the EOSCrowdsale. If you lost the private keys, you lost that.

https://etherscan.io/address/0x965d2bb2f11c250675ee7935544441b94b230b5e

**Comment by flyswatter** [comment]
That money is already lost. Please don't spend money you can't afford to lose with MetaMask, especially without reading any of our messages or warnings.

**Comment by guito10** [comment]
My god, and now, if you can give me some help, my eth account at poloniex is 0x2457a903510ff94100e9d5a4bd73eac69c7c08aa My btc account is 16KjgZyveH7c6WkjPJ95zKPc9mJGaDd1q3 Please my friend, if you can help me, I operate and trade in poloniex, I used this capital, I can make 15% in the day, if you can help me by sending me some value, I'll be very grateful, please


________________________________
De: Dan Finlay <notifications@github.com>
Enviado: quarta-feira, 28 de junho de 2017 21:45
Para: MetaMask/metamask-plugin
Cc: guito10; Author
Assunto: Re: [MetaMask/metamask-plugin] help help (#1693)


That money is already lost. Please don't spend money you can't afford to lose with MetaMask, especially without reading any of our messages or warnings.

**Comment by guito10** [comment]
My god, and now, if you can give me some help, my eth account at poloniex is 0x2457a903510ff94100e9d5a4bd73eac69c7c08aa My btc account is 16KjgZyveH7c6WkjPJ95zKPc9mJGaDd1q3 Please help me with something, I have no more money.


________________________________
De: Dan Finlay <notifications@github.com>
Enviado: quarta-feira, 28 de junho de 2017 21:45
Para: MetaMask/metamask-plugin
Cc: guito10; Author
Assunto: Re: [MetaMask/metamask-plugin] help help (#1693)


That money is already lost. Please don't spend money you can't afford to lose with MetaMask, especially without reading any of our messages or warnings.
