### ISSUE TITLE
Empty Token screen says "Loading"

### ISSUE THREAD

**Issue by alex-miller-0** [MetaMask/metamask-plugin#1694]
When I open my shiny new Token tab (thanks for that, by the way!), it just says "Loading" indefinitely. There is nothing to load, as my account has never touched a token.

![image](https://user-images.githubusercontent.com/7378490/27661699-232d2332-5c10-11e7-882a-60ae2b58961d.png)

**Comment by flyswatter** [comment]
Well, I can tell you one thing: It's loading ;)

Seriously, though. It's probably Infura lag. You could trigger a re-request by clicking `sent` and `tokens` again, or you could look for a possibly uncaught error in the logs:

https://github.com/MetaMask/faq/blob/master/LOGS.md

**Comment by flyswatter** [comment]
Just to be clear, this is what we show if we find no tokens:

![screen shot 2017-06-28 at 2 48 49 pm](https://user-images.githubusercontent.com/542863/27661927-ed019bac-5c10-11e7-8d84-65d9fe32d2ae.png)

**Comment by alex-miller-0** [comment]
Yeah it's getting a 504 from Infura

![image](https://user-images.githubusercontent.com/7378490/27662150-88150822-5c11-11e7-8b3c-c37aae3d7b41.png)

**Comment by flyswatter** [comment]
Ok, reported to Infura, I think they're processing abnormally heavy traffic right now. Try pointing it at a local node for fun!

**Comment by alex-miller-0** [comment]
Confirmed expected behavior on my own node 👍

**Comment by flyswatter** [comment]
Closing as it seems to be a network issue, not a MetaMask issue.
