### ISSUE TITLE
Add compile step to token-tracker for earlier firefox compatibility

### ISSUE THREAD

**Issue by Veendo** [MetaMask/metamask-plugin#1696]
I'd been using Chrome plugin for a couple of weeks, with no issue.(Mac OSX 10.8.5)

Last night I did a small buy from Coinbase, and transfered to another wallet...With no issue.  
Today, I can't access MetaMask. I click on the plugin, and I get a small white box below the cursor, but Metamask will not open. 

I have rebooted machine and restarted Chrome. 
NOTE: EtherDelta page sees MetaMask wallet and account. But I cannot open Metamask plugin. Suggestions?

**Comment by tmashuang** [comment]
Can you DM me on http://slack.metamask.io? Same username

**Comment by Veendo** [comment]
Slack wants me to UPGRADE...(I have an alt OS, it 's just not open at moment)I am going to try another machine.Hang on. V


-------- Original Message --------
Subject: Re: [MetaMask/metamask-plugin] Metamask Chrome - Won't open
(#1696)

**Comment by tmashuang** [comment]
There should be a browser version for Slack, I think.

**Comment by Veendo** [comment]
Thomas,Here is screen shot of what glitch looks like when I click on MetaMask. As I said, it was working fine for at least a week. I did six transactions total, with no trouble. Today when I tried opening plugin, this little box (in pic) appeared, and plugin would not open.I'll read up on security and find logs to send you.V


-------- Original Message --------
Subject: Re: [MetaMask/metamask-plugin] Metamask Chrome - Won't open
(#1696)

**Comment by osascruz** [comment]
For me the same, doing inspect (cntrl+shift+I) on this little bubble windows , it says 
 uncaught SyntaxError : Unexpected identifier   popup.js: 25792  
Last night june 28th , all was ok,  this morning , impossible to use metamask.

**Comment by Veendo** [comment]
I reinstalled on another machine using seed words. It was easy. Tomorrow, I will pull log(s) from glitched machine, once I have a little time.

**Comment by skycharger** [comment]
I also have exactly the same issue, , worked fine up until last night, now a little white box appears when you click on it,  Slack wants me to upgrade my browser to work, so that's not a route for me at the moment

**Comment by tmashuang** [comment]
Seems like Veendo got it working by reinstalling Metamask and importing his account back in with his Seed Phrase. I am curious to what operating system everyone is on and Chrome version.

**Comment by skycharger** [comment]
Yes, i was on a windows XP with Chrome 

i just installed it on a Mac on Chrome and used the seed phrase and it works now on the other machine

**Comment by skycharger** [comment]
i was on a Windows XP with Chrome
i now have  installed it on a Mac with Chrome, used the Seed Phrase and its working ( on the Mac)

**Comment by 4levels** [comment]
I had the same issue on my Debian box: little white square box instead of the usual interface.  It seems related to the new version of Google Chrome.  I tried deleting and reinstalling the extension, deleting my Chrome user profile, reinstalling the current Chrome version, all to no avail.
Only when I completely removed Chrome and downloaded the latest .deb from their website, I could get the extension to work again.  After restoring my account with the 12 secret phrases, I did however notice that my transactions no longer show up.  The balance is correct however and on etherscan my transactions are still visible.

**Comment by Veendo** [comment]
HI. I'm using the last version of Chrome that will run in OSX 10.8 (I need older version for programs I have not upgraded, that I use every day).CHROME: Version 49.0.2623.112 (64-bit)Mac Pro 2 x 2.8GHz Quad Core Intel Xeon24GB RamMac OSX 10.8.5  (12F2560)Note that this machine is still not activating the MetaMask Plugin. I restored MetaMask w/ seed words on a laptop.I'm not considering a reinstall of MetaMask on this machine (10.8.5). Thanks,V










-------- Original Message --------
Subject: Re: [MetaMask/metamask-plugin] Metamask Chrome - Won't open
(#1696)

**Comment by flyswatter** [comment]
Yesterday's MetaMask update introduced some new syntax that requires a recent browser to use. Sorry, we didn't notice the requirement change beforehand.

The workaround is to update your browser.

Let me know if updating your browser doesn't fix this issue.

**Comment by Veendo** [comment]
Dan,Sorry to be replying here. Saw info on update. Good to know. It is unfortunate that old Chrome is excluded....It forces me to a laptop, as I use OSX 10.8.5 as my primary OS - due to audio production needs (pro tools, plugins and cost of upgrading). That aside...I wanted to know what is safe to share. A Thomas Huang w/ a github address wanted me to send logs. I searched the ConsenSys team web page, and did not see his name...though he DM'd me an email address that matched that domain. I see you listed as MetaMask BUILDER (Congrats...Awesome program/extension. Really great).  If possible, there should be a place to check to verify support people (if Thomas is one). I looked on the Metamask.io page and the ConsenSys website to validate his identity, and could not find it. Given the security concerns, it would be good to have a SECURITY PAGE that lists:-what you can and cannot share, -and with whom you can and cannot share it. Essentially, a way to cross-check legit support people. He (Thomas H) seemed legit and very helpful...But as a user, I have know idea what info is included in logs, should I pass along. I was able to re-establish my Metamask account w/ seed words on laptop w/ updated Chrome.Thank you for your time and a great program!V


-------- Original Message --------
Subject: Re: [MetaMask/metamask-plugin] Metamask Chrome - Won't open
(#1696)

**Comment by Veendo** [comment]
And BTW, thank you Thomas...I appreciated your help. My concerns are general, and totally not related to you.

**Comment by osascruz** [comment]
@Dan Finlay,  it is unfortunate that XP can not upgrade chrome, XP is not supported anymore, which means I can not use metamask on my older laptops.  If it is just a syntax issue,  is there any work around for XP users ?

**Comment by flyswatter** [comment]
Yes, it's possible to get it compatible again. The issue is with our new [eth-token-tracker](https://www.npmjs.com/package/eth-token-tracker) module.

This module exports some new ES6 syntax. If we added a build system to that module, like we have as the `compile` script for [eth-block-tracker](https://github.com/MetaMask/eth-block-tracker), we could get it working with older versions of Firefox again.

We have a few responses to the token feature that we need to implement soon, and that could be one of them.
