### ISSUE TITLE
https://eos.io/distribution/ doesn't load

### ISSUE THREAD

**Issue by btsfav** [MetaMask/metamask-plugin#1697]
The latest update broke this page. won't load properly now

**Comment by tmashuang** [comment]
How so?

**Comment by btsfav** [comment]
@tmashuang oh sorry, there's no direct link.

click "get eos"

then

![](http://i.imgur.com/eW3lNGs.png)

this brings you to the metamask friendly crowdsale page. latest MM update broke it, it does not load properly now

**Comment by flyswatter** [comment]
I click "Get EOS", but it asks me to check a lot of boxes that I don't want to legally be liable for checking, as a U.S. resident, who hasn't read their white paper, purchase agreement, or terms of service.

Could you maybe check the logs, and look for errors that could be thrown here? 
https://github.com/MetaMask/faq/blob/master/LOGS.md

I suspect the network tab under the background logs may be the place to look.

**Comment by nottinhill** [comment]
This page does not load for me either. I need to disable the plugin several times and hit reload about 30-40 times and wait approx. 1-2 hours then the page show up.

Please fix.

Also please enable viewing of daily distribution count without any slow cumbersome Google Wallet for the rest of us.

**Comment by lightrush** [comment]
Here's a log form the background: https://gist.github.com/lightrush/1c660623e681728b9c4c577f49aec4fc

**Comment by sprihodko** [comment]
Same for me
Showing this error message
```
Error: SyntaxError: Unexpected end of JSON input
    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8237:28386)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8238:28122
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:168:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8214:5
    at nrWrapper (https://eos.io/js/monitoring.js:1:11483)
```

**Comment by lightrush** [comment]
I'm not sure if this is MetaMask's fault or is some API it's talking to being uncooperative?

**Comment by Avelaskes** [comment]
Same problem!!!! what to do?

**Comment by gazarian** [comment]
anyone figure this out ?

**Comment by tmashuang** [comment]
some users have been having luck with running a local node on through their console. https://github.com/metamask/faq/blob/master/USERS.md#using-a-local-node

**Comment by Cu4rach4** [comment]
i guess is a problem with latency...or a problem on gateway...

> background.js:65853 POST https://mainnet.infura.io/metamask 502 ()
> RpcSource.handleRequest @ background.js:65853
> next @ background.js:58483
> HookedWalletSubprovider.handleRequest @ background.js:66600
> next @ background.js:58483
> handleRequest @ background.js:66887
> next @ background.js:58483
> FilterSubprovider.handleRequest @ background.js:65981
> next @ background.js:58483
> (anonymous) @ background.js:65631
> BlockCacheStrategy.hitCheck @ background.js:65753
> BlockCacheProvider._handleRequest @ background.js:65629
> (anonymous) @ background.js:65593

**Comment by tmashuang** [comment]
https://consensyssupport.happyfox.com/kb/article/11-infura-connectivity-issues

**Comment by flyswatter** [comment]
Confirmed this is a problem with our Infura connection, they simply need to scale up a bit for all this new token sale traffic. In the meanwhile, the link Thomas shared contains the relevant workarounds for this issue.

https://consensyssupport.happyfox.com/kb/article/11-infura-connectivity-issues
