### ISSUE TITLE
ERC20 Tokens visible on etherscan, not appearing in wallet.ethereum or MetaMask while on Token Factory

### ISSUE THREAD

**Issue by VRstronaut** [MetaMask/metamask-plugin#1704]
Hi Devs and Supporters,

Here's my etherscan address:

You can see my CFI Tokens sitting there: https://etherscan.io/address/0x65dc07cd766ff55227ecda6b65b0732c3c883368#tokentxns

However they don't appear on wallet.ethereum nor on MetaMask while on that or the Token Factory Site.

Whats the deal?

**Comment by tmashuang** [comment]
https://blog.cofound.it/cofound-it-crowdsale-faq-2b4b45d8b32a
