### ISSUE TITLE
Clarify that network spinner is interactive UI element

### ISSUE THREAD

**Issue by mrgdizzle** [MetaMask/metamask-plugin#1707]
Trying to login all it says is searching for network?

**Comment by bilthon** [comment]
Same here

**Comment by assafmo** [comment]
Also here

**Comment by flyswatter** [comment]
When you click the spinner in the top left, what network is it trying to connect to?

Are you able to select a different network? What about a different network, and then the Main Network again?

**Comment by bilthon** [comment]
Fair enough, this just solved the problem, I was trying to connect to a http://rpc.makerdao.com:7777. Sorry it was a dump user-side problem, at least in my case. It was solved after selecting the "Ethereum main net" option.

The spinner icon doesn't exactly convey the message that it is an interactive UI element though, so you might want to change that.

**Comment by assafmo** [comment]
@flyswatter localhost:8545. Thank you, my bad.  
I didn't know I can click the spinner, the window was confusing, looked like this
![metamask](https://user-images.githubusercontent.com/22766533/27802797-a3f7402a-602e-11e7-9860-f884d88f3402.jpg)

Anyway now it works. Thank you.

**Comment by flyswatter** [comment]
We'll make that menu item more clear for this issue.

**Comment by flyswatter** [comment]
![searching for network](https://user-images.githubusercontent.com/542863/27808179-fcfeb560-5ffa-11e7-90e9-ac1c36d6e72b.png) 

Some sketches by our designer Christian.

**Comment by bilthon** [comment]
Cool! In my opinion the carrot indicator is enough.

**Comment by assafmo** [comment]
I too think that the carrot is enough.  
But maybe replace the searching network with connecting to the main/test net that the clear message shows. I think it's clearer that way.

**Comment by flyswatter** [comment]
Great ideas. Combining them.
