### ISSUE TITLE
metamask is blank

### ISSUE THREAD

**Issue by johnsbrt** [MetaMask/metamask-plugin#1715]
![image](https://user-images.githubusercontent.com/14153298/27753800-fa95bb5e-5d9b-11e7-968e-c0a6438bee34.png)

I just get a blank box below the metamask icon.  I have uninstalled and reinstalled metamask (I have my seed phrase)

I am running Windows 7 professional 
Chrome Version 54.0.2840.59 m (64-bit)

**Comment by flyswatter** [comment]
We accidentally broke compatibility for older browsers in the last release. You can update your browser to fix this, or just wait a few hours, we're publishing a fix for this soon.
