### ISSUE TITLE
Unable to change MetaMask settings

### ISSUE THREAD

**Issue by filmakarov** [MetaMask/metamask-plugin#1717]
Hello!

Used MetaMask to get some EOS.
It worked ok at 30th of June, and I put some ETH on my MetaMask account.
Today I've got the following message from EOS distribution app

> If problems persist there may be a problem with your connection to the Ethereum network. You can try configuring MetaMask to use one of the following servers:
> http://rpc.makerdao.com:7777

I did this in MetaMask settings, but now my MetaMask does not connect at all (Serching for Network) and it does not allow me to change Settings back to default

<img width="348" alt="2017-07-02 17 27 48" src="https://user-images.githubusercontent.com/3930375/27770776-98f43b24-5f4d-11e7-8be4-caaf71ceb9af.png">

How can I change settings back to get my MetaMask working?

Google Chrome 59.0.3071.115
Mac OS 10.12.5

Thank you!

**Comment by flyswatter** [comment]
In the top left network menu (currently a spinner), you can select another network, like "Main Ethereum Network".

**Comment by filmakarov** [comment]
It worked! Thank you!
