### ISSUE TITLE
How to remove a Token added to MetaMask, Token is still in ICO mode and thus unrecognized

### ISSUE THREAD

**Issue by ddkdlk** [MetaMask/metamask-plugin#1718]
I added a token to Metamask, and now etherdelta won't let me log into exchange do to unrecognized token in metamask chrome plug-in. I see how to add tokens, but is there a way to remove them from wallet till they are active? Thank you for all your time, effort, and patients. I was getting a failure script when I was trying to go on etherdelta.

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by flyswatter** [comment]
Adding a token to MetaMask's token tracker does not affect sites you visit. The token problem you're having is something else.

We don't have the ability to remove tokens from the list yet, but it's just a view, it has no underlying impact on how you interact with sites.
