### ISSUE TITLE
A Token added to MetaMask still in ICO mode, wont allow access to etherdelta  *ERROR*

### ISSUE THREAD

**Issue by ddkdlk** [MetaMask/metamask-plugin#1719]
I added a token to Metamask, and now etherdelta won't let me log into exchange do to unexpected token in metamask chrome plug-in. I see how to add tokens, but is there a way to remove them from wallet till they are active? Thank you for all your time, effort, and patients. I was getting a failure script when I was trying to go on etherdelta. Here is the error I found: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:36 MetaMask - injected web3

Uncaught SyntaxError: Unexpected token *  bundle.js:3328

**Comment by flyswatter** [comment]
The SyntaxError you got does not refer to an Ethereum token, but a JavaScript character.

I believe you're running an older browser, I think you'll fix this problem by updating it.
