### ISSUE TITLE
MetaMask can not send transactions to localhost:8545

### ISSUE THREAD

**Issue by quangleehong** [MetaMask/metamask-plugin#1722]
i used MetaMask for private Eth blockchain talking to network via geth client the issue is i can import the accounts created via geth client cli with the private key, the MetaMask can see the money on coinbase acc by mining, but i try to send eth between accounts then the spinner icon keep spinning and then the transaction failed. dont know if any extra step to start geth client parameters so that the metamask can work with geth client via localhost:8545 ?
currently i start the geth with:  geth --datadir "path\to\node" --networkid 12346493 --rpc --rpcport 8545 --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "db,eth,net,web3,personal,web3" --unlock 0,1,2 --nodiscover --testnet console

is there any thing to adjust so that metamask can send eth transactions ?

metamask chrome plugin version : 3.8.1, install from chrome extension

**Comment by flyswatter** [comment]
Our guide to using geth with MetaMask is here:

https://github.com/MetaMask/faq/blob/master/USERS.md#using-a-local-node

I'd think your `--rpccorsdomain="*"` would work, but looks like our guide makes it specific, so maybe worth trying those flags exactly.

**Comment by soenkeba** [comment]
I run in the same issue, I realized that the CHAINID in the genesis block and the geth --networkid was not the same so (see https://ethereum.stackexchange.com/questions/13498/invalid-sender-error-on-private-chain).

**Comment by kumavis** [comment]
@soenkeba i think geth 1.6 no longer defaults the net id to chain id, so we're hearing this issue recently. we dont currently have a way to query the chainId directly so have always used the network id

**Comment by quangleehong** [comment]
i found that the issue coming from networkid is not the same with chainId in genesis block , change the networkid to be the same with chainID then the transaction done. 

off topic: please do me another favor since i just step in the dapp with web3js 
if the client does not have the geth runing( so no eth.account(account[0] available) in local but only metamask wallet with some ether in the EOA account , how can we call web3 to get that address as sender address  in client side web3 code ?

**Comment by QingyangKong** [comment]
Hi  @soenkeba , what is the chainId metamask uses? Is there a way changing chainId for MetaMask

**Comment by danfinlay** [comment]
When spinning up a local network, you have to set both its `networkId` and `chainId` to the same value for MetaMask compatibility.  These are flags on geth, and are probably on parity, too.
