### ISSUE TITLE
Shapeshift to MetaMask. Never arrived

### ISSUE THREAD

**Issue by felipecaldas** [MetaMask/metamask-plugin#1724]
Hi all,

I have used Shapeshift to transfer some BTC straight to my MetaMask address. The transaction has already been confirmed on SS for about 1 hour now, but no signs of ether on my account.

Also, the confirmation e-mail SS sent me with the blockchain information cannot be found: https://etherscan.io/tx/0x132d444d2b5e466330eacb60435d9358b4aac40b2436b007903204b41a410933

Can anyone shed me some light?

Thank you
Felipe

**Comment by tmashuang** [comment]
What does your SS provided address say on a BTC block explorer, bitref?

**Comment by felipecaldas** [comment]
Hey mate
the link I posted is the only one I have. It was emailed to me. Where can I see thw BTC block explorer?

**Comment by felipecaldas** [comment]
My bad, here's the BTC block explorer
https://blockexplorer.com/address/14ucV25BeN6DMpbQXLr69WbTbChFLMN75P

**Comment by tmashuang** [comment]
A couple things could be happening here. The transaction could be still getting mined or there is an issue with how SS sent the transaction. Either way contact SS support and they should be able to provide more information.

**Comment by felipecaldas** [comment]
Will do Thomas. Thanks for your help!

**Comment by pointtoken** [comment]
If you are wanting to ShapeShift ERC20 tokens that are in your MetaMask wallet, check out [https://www.efolio.info/shapeshift](https://www.efolio.info/shapeshift) which has a safe and simple implementation.
