### ISSUE TITLE
MM errors eos.io/distribution

### ISSUE THREAD

**Issue by hbkimz** [MetaMask/metamask-plugin#1726]
My MM doesn't load eos.io/distribution.

Here are background logs. 
Please help me out.

MetaMask initialization complete.
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:42435 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42435
background.js:42441 console.trace
EventEmitter.addListener @ background.js:42441
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:65323 SyntaxError: Unexpected end of JSON input
_callee6$ @ background.js:65323
background.js:42435 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42435
background.js:42441 console.trace
EventEmitter.addListener @ background.js:42441
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:42435 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42435
background.js:42441 console.trace
EventEmitter.addListener @ background.js:42441
background.js:42435 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42435
background.js:42441 console.trace
EventEmitter.addListener @ background.js:42441
background.js:42435 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
EventEmitter.addListener @ background.js:42435
background.js:42441 console.trace
EventEmitter.addListener @ background.js:42441
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
mainnet.infura.io/metamask Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
3mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
3mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 500 ()
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
mainnet.infura.io/metamask Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
mainnet.infura.io/metamask Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
mainnet.infura.io/metamask Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:65323 InternalError
_callee6$ @ background.js:65323
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:65323 SyntaxError: Unexpected end of JSON input
_callee6$ @ background.js:65323
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:65323 InternalError
_callee6$ @ background.js:65323
tryCatch @ background.js:51906
invoke @ background.js:52144
prototype.(anonymous function) @ background.js:51958
step @ background.js:10505
(anonymous) @ background.js:10518
4mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
4mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
4mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
4mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
2mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:65323 SyntaxError: Unexpected end of JSON input
_callee6$ @ background.js:65323
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 504 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 500 ()
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
background.js:2929 SyntaxError: Unexpected end of JSON input
(anonymous) @ background.js:2929
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 500 ()
background.js:65323 SyntaxError: Unexpected end of JSON input
_callee6$ @ background.js:65323
mainnet.infura.io/metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
background.js:4397 Error in RPC response:
 Object
logger @ background.js:4397
metamask Failed to load resource: the server responded with a status of 500 ()
background.js:4397 Error in RPC response:
 Object {message: "SyntaxError: Unexpected end of JSON input", code: -32000}
logger @ background.js:4397
onPayloadHandled @ background.js:67496
(anonymous) @ background.js:58517
(anonymous) @ background.js:9072
replenish @ background.js:8952
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
(anonymous) @ background.js:65633
resultObj.id @ background.js:58497
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
(anonymous) @ background.js:8961
eachLimit @ background.js:8829
(anonymous) @ background.js:8889
end @ background.js:58494
activeRequestHandlers.forEach @ background.js:66890
next @ background.js:66890
resultObj.id @ background.js:58497
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
(anonymous) @ background.js:8961
eachLimit @ background.js:8829
(anonymous) @ background.js:8889
end @ background.js:58494
background.js:4397 Error in RPC response:
 Object {message: "SyntaxError: Unexpected end of JSON input", code: -32000}
logger @ background.js:4397
onPayloadHandled @ background.js:67496
(anonymous) @ background.js:58517
(anonymous) @ background.js:9072
iterateeCallback @ background.js:8937
(anonymous) @ background.js:9088
next @ background.js:66891
resultObj.id @ background.js:58497
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
(anonymous) @ background.js:8961
eachLimit @ background.js:8829
(anonymous) @ background.js:8889
end @ background.js:58494
metamask Failed to load resource: the server responded with a status of 502 ()
background.js:4397 Error in RPC response:
 Object {message: "SyntaxError: Unexpected end of JSON input", code: -32000}
logger @ background.js:4397
onPayloadHandled @ background.js:67496
(anonymous) @ background.js:58517
(anonymous) @ background.js:9072
replenish @ background.js:8952
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
(anonymous) @ background.js:65633
resultObj.id @ background.js:58497
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
(anonymous) @ background.js:8961
eachLimit @ background.js:8829
(anonymous) @ background.js:8889
end @ background.js:58494
activeRequestHandlers.forEach @ background.js:66890
next @ background.js:66890
resultObj.id @ background.js:58497
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
(anonymous) @ background.js:8961
eachLimit @ background.js:8829
(anonymous) @ background.js:8889
end @ background.js:58494
background.js:4397 Error in RPC response:
 Object {message: "SyntaxError: Unexpected end of JSON input", code: -32000}code: -32000message: "SyntaxError: Unexpected end of JSON input"__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()
logger @ background.js:4397
onPayloadHandled @ background.js:67496
(anonymous) @ background.js:58517
(anonymous) @ background.js:9072
iterateeCallback @ background.js:8937
(anonymous) @ background.js:9088
next @ background.js:66891
resultObj.id @ background.js:58497
(anonymous) @ background.js:9163
replenish @ background.js:8957
iterateeCallback @ background.js:8942
(anonymous) @ background.js:9088
resultObj.id @ background.js:58499
(anonymous) @ background.js:9163
replenish @ background.js:8957
(anonymous) @ background.js:8961
eachLimit @ background.js:8829
(anonymous) @ background.js:8889
end @ background.js:58494
background.js:65853 POST https://mainnet.infura.io/metamask 504 ()
RpcSource.handleRequest @ background.js:65853
next @ background.js:58483
HookedWalletSubprovider.handleRequest @ background.js:66600
next @ background.js:58483
handleRequest @ background.js:66887
next @ background.js:58483
FilterSubprovider.handleRequest @ background.js:65981
next @ background.js:58483
(anonymous) @ background.js:65631
BlockCacheStrategy.hitCheck @ background.js:65753
BlockCacheProvider._handleRequest @ background.js:65629
(anonymous) @ background.js:65593
background.js:65323 InternalError {message: "Gateway timeout. The request took too long to proc…n when querying logs over too wide a block range.", code: -32603}

**Comment by flyswatter** [comment]
Sorry, the network connection issues are because our backend is overwhelmed. The short-term workaround is to point your MetaMask at [a local node](https://github.com/MetaMask/faq/blob/master/USERS.md#using-a-local-node) instead.

You can also try changing the network (top left spinner) to another and back again. Some users have had success with that method.
