### ISSUE TITLE
Does not connect to https://wallet.ethereum.org/

### ISSUE THREAD

**Issue by SemElVik** [MetaMask/metamask-plugin#1735]
![2017-07-04_08-03-39](https://user-images.githubusercontent.com/27207809/27815822-fd08710a-608f-11e7-8948-a85867b4e12b.png)

Does not connect to https://wallet.ethereum.org/
Version: browser, metamask, OS, all updated. Also does not connect to https://eos.io/distribution/. And on the browser YandexBrowser all works.
Did reinstall Google, did not help.
What should be done?

**Comment by kumavis** [comment]
strange that its not working for you - sounds like you are using it correctly
check the javascript console for wallet.ethereum.org for errors
also try restarting the page a couple times and see if it works sometimes

**Comment by kumavis** [comment]
oh! i see you have the parity extension installed - i think they are competing. try disabling one of them.

**Comment by SemElVik** [comment]
I've got Parity installed. Can he somehow influence this? (They are not running in parallel).

**Comment by kumavis** [comment]
yes the parity browser extension can interfere with metamask

**Comment by SemElVik** [comment]
Yes thank you) . In the process and I drew attention to it)
