### ISSUE TITLE
Metamask

### ISSUE THREAD

**Issue by Nikitosss94** [MetaMask/metamask-plugin#1738]
I have a question: how to get EOS tokens from Metamask to the bitfinex exchange. 
In Metamask there is no "SEND" button in the tokens tab.

**Comment by flyswatter** [comment]
You're right, we just started adding token support (the list) recently, and will be adding `SEND` soon. In the meanwhile, you'll need to use a site with metamask that lets you send tokens. There's a nice list of them here:

https://consensyssupport.happyfox.com/kb/article/4-managing-tokens
