### ISSUE TITLE
tx controller - resubmit - balance validation

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#1752]
we need to fix this validation to check not just the `value` but the tx `maxCost`
https://github.com/MetaMask/metamask-plugin/blob/34e2f6650d0db42b9f820d56a7acf9b72ca14da2/app/scripts/controllers/transactions.js#L448

**Comment by kumavis** [comment]
@frankiebee you've been doing resubmit validation, so maybe a good ticket for you
though may have been covered by https://github.com/MetaMask/metamask-plugin/pull/1750
also related - ui level validations https://github.com/MetaMask/metamask-plugin/issues/1746

**Comment by flyswatter** [comment]
Fixed in #1762
