### ISSUE TITLE
Detecting if the account is locked

### ISSUE THREAD

**Issue by coopermaruyama** [MetaMask/metamask-plugin#1766]
I need to get the user's coinbase but `web3.eth.coinbase` throws an exception if the user's account is locked. This is fine, but in this case I would like to show a notification telling the user they should unlock their account. I have found no information regarding this in the docs.

Is there support and/or a recommended way to detect if a user has their account locked?

**Comment by flyswatter** [comment]
Right now the only way to detect if a user's account is locked is checking if the `web3.eth.accounts` array is empty.

**Comment by flyswatter** [comment]
This is discussed in more detail on our DEVELOPER guide:
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md

**Comment by sulliwane** [comment]
I'm trying to detect when Metamask is locked. I'm using this code:
```html
    <script>
    window.addEventListener('load', () => {
      setInterval(function() {
        console.log(window.web3.eth.accounts[0])
      }, 1000);
    })
    </script>
``` 
The logged value never change, even when I lock/unlock/switch account from Metamask UI.

What am i missing here ?

Many thanks!

**Comment by danfinlay** [comment]
Recently this synchronous account lookup has gotten less reliable, I spent several hours trying to track down why, no luck.

You can always reliably identify account changes using the async method:
`web3.eth.getAccounts(function (err, accounts) { console.log(accounts[0]) })`

**Comment by sulliwane** [comment]
many thanks, the async version works perfectly. All async! :)

**Comment by pierrelegrain** [comment]
This was my workaround - checking metamask's own _isUnlocked_ to direct the user to go unlock their Metamask account before attempting to connect. It's dumb, but it works.

let isLoggedIn = await ethereum._metamask.isUnlocked();
connectWallet.addEventListener('click', () => {
	if (isLoggedIn) {
		ethereum.request({ method: 'eth_requestAccounts' }); // Opens the metamask extension pop-up
	} else {
		alert('Please log in to Metamask before attempting to connect.');
	}
});
