### ISSUE TITLE
Block phishing site blacklist

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1767]
Great prior art [we've been given permission](https://twitter.com/sniko_/status/883749689727823873) to import:

https://github.com/409H/EtherAddressLookup

**Comment by 409H** [comment]
Merged the [package.json PR24](https://github.com/409H/EtherAddressLookup/pull/24) on our end, so you should be good as far as pulling the blacklist as a dependency 👍

**Comment by flyswatter** [comment]
Pointed at it now in PR #1768, thanks @409H!
