### ISSUE TITLE
Don't reload the extension when changing provider

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#247]
Will require dropping some cached items, but otherwise the reload should be unnecessary.

**Comment by flyswatter** [comment]
Might be useful in service of the zero client lib #23

**Comment by flyswatter** [comment]
Notes:

It’s a tricky issue, because it requires purging all network-related in-memory storage. An incomplete purge will result in bugs. Two major places to start looking are:
- The `MetaMaskProvider` in `app/scripts/metamask-controller.js` caches, could simply be re-instantiated.
- Any `ObservableStore` in our `app/scripts` folder that stores network-specific data. A table of the various observable stores that should be considered are here: https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/metamask-controller.js#L145-L156

**Comment by kumavis** [comment]
@frankiebee is making a `networkController` that will help with this

**Comment by frankiebee** [comment]
Fixed in PR #1455
