### ISSUE TITLE
Add parity provider

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#330]
Is this an option?  Could we connect MetaMask to a parity node?

**Comment by crazyquark** [comment]
I tried to do this and transactions fail, I don't know why, I just get this error object:
`ZoneAwareError
__zone_symbol__error
:
Error: Transaction execution error. at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:27885) [<root>] at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:26989 [<root>] at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:179:7 [<root>] at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6682:5 [<root>] at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6570:47) [<root> => <root>] at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6820:38) [<root>] at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7931:25) [<root>]
message
:
"Transaction execution error."
originalStack
:
"Error: Transaction execution error.↵    at ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7362:33)↵    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:27885)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:26989↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:179:7↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6682:5↵    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6767:31)↵    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6570:47)↵    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6820:38)↵    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7931:25)"
stack
:
"Error: Transaction execution error.↵    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:27885) [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:26989 [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:179:7 [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6682:5 [<root>]↵    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6570:47) [<root> => <root>]↵    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6820:38) [<root>]↵    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7931:25) [<root>]"
zoneAwareStack
:
"Error: Transaction execution error.↵    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6705:27885) [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6706:26989 [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:179:7 [<root>]↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:6682:5 [<root>]↵    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6570:47) [<root> => <root>]↵    at ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:6820:38) [<root>]↵    at data.args.(anonymous function) (http://localhost:4200/polyfills.bundle.js:7931:25) [<root>]"
__proto__
:
Object
message
:
"Transaction execution error."`

**Comment by kumavis** [comment]
our default mainnet rpc provider is a parity node

@crazyquark I think your issue is related to https://github.com/MetaMask/metamask-plugin/issues/1238
