### ISSUE TITLE
Vault Recovery - consider 2-pane view

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#336]
When recovering a wallet, you have to type in your seed phrase & your new password. My problem is I store both my seed phrase and my password (that I use for metamask) in a password manager. The problem is when I navigate away from the metamask extension, I lose the info that I put in previously. So here’s what happens:

1. I copy my seed phrase from my password manager
2. Open metamask and input the seed phrase
3. Open password manager to copy my password [metamask closes]
4. Open metamask to input… oh no! I lost my seed phrase! :disappointed:

Super low priority but just wanted to bring it to your attention :slightly_smiling_face:

reported by @karlfloersch (slack: karl-floersch)

**Comment by flyswatter** [comment]
Will be fixed with the solution to #432, closing as a duplicate.
