### ISSUE TITLE
Indicating USD value on tx notifications

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#362]
Blocked by #278

**Comment by Zanibas** [comment]
Two mockups by Vlad

![03b-metamask-app-usd](https://cloud.githubusercontent.com/assets/1840057/17673231/20e7277e-62d5-11e6-914b-c3a4852125dc.
![03c-metamask-app-usd](https://cloud.githubusercontent.com/assets/1840057/17673249/2c3c8074-62d5-11e6-88f4-850a36842ba4.jpg)
jpg)
