### ISSUE TITLE
Txs blocked by insufficient ether for gas cost still produces tx in tx history

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-plugin#416]
To reproduce:
Initiate a tx to another wallet which attempts to give your entire balance. MM will block it, but still produce a tx in the tx history for it, not marked as failed.

**Comment by flyswatter** [comment]
Maybe we should change this to a "send max" button feature, like Mist has.

**Comment by flyswatter** [comment]
1.  Make it impossible to send more than you have (gas included).
2. (longer term) Verify out of funds errors get shown as errors in tx history.

**Comment by flyswatter** [comment]
If we move from FontAwesome to [Google Material Icons](https://design.google.com/icons/), we get an out of gas icon.

**Comment by flyswatter** [comment]
Dupe of #546
