### ISSUE TITLE
Persist UI state between popup openings

### ISSUE THREAD

**Issue by rverbee** [MetaMask/metamask-plugin#432]
I was using MetaMask to send a very specific amount of ether to POPA. I had to copy and paste both the POPA address and a long number representing the amount of ether they wanted me to send (0.49472723474274 or whatever). 

When I pasted the address and left metamask to copy the amount from the POPA web page, MetaMask reloads when I return to paste the amount and I lose the address I just pasted in.

Guess I could just copy both to a text file or something...

**Comment by flyswatter** [comment]
We're probably going to do a per-form persisting on the UI side, so we can re-load forms in progress when the popup is re-opened.

Forms to do this for:
- Recover vault screen
- Buy ether with shapeshift screen?
- Send tx screen

Ideally in a reusable way so this process is at least mostly automated.
