### ISSUE TITLE
Fix Terms of Service Typos

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#446]
Thanks to Joseph Chow:

TOS typo "Etherium": IS MEANT FOR DEVELOPERS OR PEOPLE WITH A UNDERSTANDING OF THE ETHERIUM PROTOCOL.

[6:06]  
another 2 security and reimbursement: *SECURTIY* RISKS IN METAMASK THAT MAY RESULT IN LOSS OF ETHER AND THE THE METMASK TEAM IS NOT HELD RESPONSIBLE FOR *REINBERSMENT* OF LOST FUNDS

After finding those two he stopped reading, so there may be more.

We should maybe pass this through a basic spell checker. We all missed this apparently.

**Comment by Zanibas** [comment]
Closed by  #448
