### ISSUE TITLE
Replace all chrome-specific method calls with generic extension API

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#453]
Looks like there's likely not a single thing we're doing that is actually Chrome specific.

[WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions).

[Guide to porting Chrome extensions to other platforms](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension).

The catch is that Chrome has us calling things like `chrome.notifications.create`, when the standard just says `notifications.create`, so we might have to use some kind of cross-browser polyfill to easily use the relevant local extensions APIs.

We've received interest for compatibility for Firefox, IE, and Safari.

**Comment by yorkerhodes3** [comment]
Sounds great.  How are things going on modifying the version to see if it still works on Chrome first with the generic calls? If that is your approach.

**Comment by flyswatter** [comment]
We had some other urgent issues first, but I should get more time to work on this soon.

My initial experiments looked like chrome hides all of these standard calls behind a chrome object, so we might need some platform conditional logic.

**Comment by flyswatter** [comment]
I swapped out all of our direct chrome references into a module that checks for a chrome global, and the extension is still working, now I can begin testing on other platforms.

I've already seen there's at least one method we use (`runtime.reload`) that won't work on FireFox.
