### ISSUE TITLE
Mixed font styles on transaction approval dialog

### ISSUE THREAD

**Issue by jorisbontje** [MetaMask/metamask-plugin#468]
The "New Unsigned Transaction" dialog contains a mix of serif and sans-serif fonts. This seems to be quite arbitrary / something that was forgotten to be styled rather than intended.

![image](https://cloud.githubusercontent.com/assets/620959/16981088/57c7544c-4e69-11e6-885a-11b24503d423.png)

**Comment by flyswatter** [comment]
This is a symptom of the sort of SVG rendering we're using to cram some interesting information into the small notification graphic.

So far we haven't gotten the SVG rendering the fonts we want, although it should be possible.

Another solution is #452, where we would replace the chrome notifications with popups, which could have their own fully interactive UI in them.

**Comment by flyswatter** [comment]
Closing in favor of #452
