### ISSUE TITLE
Add support for Ethereum Classic

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#490]
Not sure how bad people are calling for this, but it's a thing, and infura is supporting it at `https://mainnet-nf.infura.io`, so I figure we could tuck it away in the config or something.

I don't envy the dapp developers who might have to add a `isForkedChain()` call on every boot up.

Kindof curious people's thoughts on what the dev experience is going to be like for that...

**Comment by Ryanmtate** [comment]
👍
