### ISSUE TITLE
Add custom gas field to send tx form

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#495]

**Comment by flyswatter** [comment]
Would be nice to have a Mist-like slider between "speed" and "cost".

**Comment by D-Nice** [comment]
Really need this feature, bunch of calls are failing because not enough gas is being provided.

**Comment by flyswatter** [comment]
@D-Nice Would this slider adjust the gasPrice or the gas field? It seems like these both have different benefits.  Maybe a gasLimit too? I was surprised to see Mist only provides one slider for these three values.

**Comment by D-Nice** [comment]
The gas field itself I find to be most important, however, gasPrice would be a nice addition as well(maybe have it under an advanced or developer mode to not confuse the average user). Mist only provides one slider, but it does give the option to set a custom gas limit right before sending a transaction.

**Comment by flyswatter** [comment]
Forgive me, some stream of consciousness here on the UX of gas fees.

That's a little strange to me that you think `gas` itself is the important field, I'm pretty sure for example that Mist's primary slider is for `gasPrice`, because it represents the urgency to include the tx on the block, making it the more casually user-useful parameter, the `limit` (aka the `gas` field) being the thing that seems less likely to need tuning.

In fact, when you first chimed in here that txs were failing, it was right around the time that miners raised their gas prices in response to the geth DDOS attack, so I'm tempted to suspect that's what you were hitting, you may have not been able to get a tx included on a block because of a low gas fee.

It partly seems more likely to me because we actually emulate every tx before presenting it to the user (by calling `estimateGas`), to estimate the total `gas` cost, so normally it should "just work", so either you had some strange kinds of txs that had hard-to-estimate gas costs, or you were actually not paying enough for the gas.

Does this sound about right? Maybe `gas` belongs under `advanced`, and `gasPrice` we could represent as being "transaction fee" (as mist calls it), with the current miner rate as average, and maybe a warning that low fees may be slow to include, or not included at all?

I wonder if there's a definite minimum tx fee we should dare at? Do any miners take dirt cheap gasPriced txs?

We used to fudge the `gas` value to higher than the estimate, I kindof think this might actually be ok in most cases. The `minimum` gas value could be the estimated value, and the user could raise it higher, and the `transaction fee` could be more prominent?

**Comment by D-Nice** [comment]
It wasn't an issue with gasPrice, it was indeed an issue with the estimated amount of gas being sent via MetaMask not being high enough, hence the tx was getting a out of gas error.
