### ISSUE TITLE
Event Filters - Support loading Historical Events

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#503]
Today both @jorisbontje and @austp contacted us on our slack with issues around the contract.Event api.

For Joris, he reported that the `myInstance.Event({}, { fromBlock: 1920000 }, function (err, result) {})` api wasn't working for him, and wanted to know how to load a series of events with MetaMask.

For @aust, he found he could trigger a disconnection to metamask error with a basic Truffle coin contract by calling `meta.allEvents()` like this:
```
var meta = MetaCoin.deployed();
var events = meta.allEvents();
events.watch(function(err, e) {
    if (err) {
        console.log(err);
    } else {
        console.log(e.event + ": " + JSON.stringify(e.args));
    }
});
```

He then found a workaround, by putting the `allEvents()` call in a 100ms `setTimeout` call, so it seems to be an issue with us not loading an events connection in time.

### Peripheral, not necessarily related

When porting to FireFox, I recently updated our inpage script injection strategy. Before we'd been using the `contentscript` to inject a `script` tag with the `src` property set to the `inpage.js` script, but we learned that the `src` attribute does not guarantee ordered loading, while directly setting the `innerContent` property did.

I'm partly curious if this is an issue in the new way we're injecting the script.

**Comment by kumavis** [comment]
allEvents() is working for me on master with and without waiting for the window load event
```
console.log('ready')
// window.addEventListener('load', startApp)
startApp()

function startApp() {

  console.log('go')
  var MetaCoin = web3.eth.contract([{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"success","type":"bool"}],"type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"remaining","type":"uint256"}],"type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_from","type":"address"},{"indexed":true,"name":"_to","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_owner","type":"address"},{"indexed":true,"name":"_spender","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Approval","type":"event"}])
  var meta = MetaCoin.at('0xfd78216af702ddc3fed7783db1eea14c6fead93d')
  var events = meta.allEvents()
  events.watch(function(err, e) {
    if (err) {
      console.log(err)
    } else {
      console.log(e.event + ": " + JSON.stringify(e.args))
    }
  })

}
```

**Comment by kumavis** [comment]
Watching a specific event is also working fine on master.

```js
console.log('ready')
// window.addEventListener('load', startApp)
startApp()

function startApp() {

  console.log('go')
  var MetaCoin = web3.eth.contract([{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"success","type":"bool"}],"type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"remaining","type":"uint256"}],"type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_from","type":"address"},{"indexed":true,"name":"_to","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_owner","type":"address"},{"indexed":true,"name":"_spender","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Approval","type":"event"}])
  var meta = MetaCoin.at('0xfd78216af702ddc3fed7783db1eea14c6fead93d')
  var events = meta.allEvents()
  events.watch(function(err, e) {
    console.log('allEvents!')
    if (err) {
      console.log(err)
    } else {
      console.log(e.event + ": " + JSON.stringify(e.args))
    }
  })

  meta.Transfer({}, { fromBlock: 1420000 }, function (err, result) {
    console.log('Transfer Event!')
    console.log(arguments)
  })

}

```

**Comment by kumavis** [comment]
> For @aust, he found he could trigger a disconnection to metamask error with a basic Truffle coin contract by calling meta.allEvents() like this:

My guess is that there was an application error that triggered the disconnection (we've since made it so app errors do not cause a disconnect)

**Comment by kumavis** [comment]
@jorisbontje @austp, I'll need some help to reproduce these errors

**Comment by kumavis** [comment]
here's what i tested against
https://github.com/kumavis/dapp-filter-example

**Comment by flyswatter** [comment]
Let's publish Monday morning and ask the people who had issues of they persisted.

- Dan

**Comment by jorisbontje** [comment]
Using the `dapp-filter-example` I get the following output:
```
Navigated to http://127.0.0.1:9966/
inpage.js:31MetaMask - injected web3
index.js:3 ready
index.js:9 go
```

After which nothing more gets logged. Instead I would expect the `Transfer` events to be logged. This is with MetaMask 2.7.3, connected to Morden testnet and Chrome Version 52.0.2743.116 (64-bit).

Note that I did have to start `beefy` as following to get around a "Could not find a suitable bundler" error: `beefy index.js --live --open --browserify browserify`

**Comment by kumavis** [comment]
@jorisbontje ok you are expecting historical logs, got it. will fix.

**Comment by kumavis** [comment]
@jorisbontje testing this, allEvents doesnt seem to ask for historical events.

**Comment by kumavis** [comment]
it generates a filter with undefined `fromBlock`
wiki (not really reliable source of geth behavior) indicates that the fromBlock default is “latest"
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
which would mean: no, does not lookup historical events

**Comment by jorisbontje** [comment]
The problem is not with ` var events = meta.allEvents()` but with
```
meta.Transfer({}, { fromBlock: 1420000 }, function (err, result) {
    console.log('Transfer Event!')
    console.log(arguments)
  })
```

That should define `fromBlock`  and return historic event; at least it does so with `parity` and `geth` but doesn't with MetaMask.
