### ISSUE TITLE
Transactions fail after encountering out of gas error.

### ISSUE THREAD

**Issue by AustP** [MetaMask/metamask-plugin#510]
I was testing my Dapp and sent ETH to my contract. I had done this probably about 20 times before but for some reason this time I got a out of gas error.

![image](https://cloud.githubusercontent.com/assets/2007045/17266362/67a234f2-55b4-11e6-9f79-867d6d0ee186.png)

So I tried sending the ETH again. After approving the transaction via MetaMask, nothing happens. I don't get any errors logged, and my contract doesn't receive any ETH. The transaction shows up in MetaMask's transaction history though.

Anyways, I checked MetaMask's background page's console for any errors. After about 30 seconds of nothing happening, this error shows up in the console:

![image](https://cloud.githubusercontent.com/assets/2007045/17266161/4928035a-55b2-11e6-9bfe-4f4e44bc2e1c.png)

**Comment by flyswatter** [comment]
That error is our development live reloaded, we should deactivate it in production, but it shouldn't cause that first bug, that first bug is weird!

- Dan

**Comment by AustP** [comment]
I've got some more information. This might be a web3 issue after all...

So I just updated my solidity code, and now whenever I send a transaction with more than the allowed ether, I get the out of gas exception. Here is the block snippet that handles that logic:

    // if they go over the maximum, refund them the rest
    if (participant.amount > maximum) {
        uint refund = participant.amount - maximum;
        participant.amount = maximum;
        amount -= refund;
        msg.sender.send(refund);
    }

Now, if I change the block to this:

    // if they go over the maximum, refund them the rest
    if (participant.amount > maximum) {
        uint refund = participant.amount - maximum;
        amount -= refund;
        msg.sender.send(refund);


        // NOTICE: this line moved to the bottom
        participant.amount = maximum;
    }

then when I send a transaction with more than the allowed ether, I don't get the exception and everything works as intended.

**Comment by flyswatter** [comment]
I'm not sure I understand this problem, it seems like more of a provider/client issue than MetaMask.  We're validating what we can, it's very strange the provider returns different results based on a small change like this.

**Comment by AustP** [comment]
I agree. I just moved this issue to https://github.com/ethereumjs/testrpc/issues/140
