### ISSUE TITLE
Inpage provider loses connection on Tokenfactory

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#511]
Tried loading up [BeerCoin](http://tokenfactory.surge.sh/#/token/0x74c1e4b8cae59269ec1d85d3d4f324396048f4ac) as announced in [this Reddit post](https://www.reddit.com/r/ethereum/comments/4v7opj/introducing_beercoin/), but every time I load the page, I get an error.

We've been getting a lot of "inpage provider lost connection" bugs this week, ever since I changed the script injection from `src` to `innerContent`, to fix our late-injection bugs.  I don't know if they're related, I think it may have just changed when we needed to wire up some things.

I'll just drop it here so @simondlr knows we're aware of this and working on it soon.

**Comment by flyswatter** [comment]
Oh but actually these 'inpage provider' disconnections may just get thrown when the page throws errors within the page? Is there a way we can not do that?

If you add a breakpoint on our inpage provider disconnection error, and check the `err.stack`, you'll see the err is actually thrown from within TokenFactory itself.

It would be great if we could let normal bugs get thrown without making them look like we caused them, it adds an unfortunate amount of obtruction to understanding the bug.

**Comment by flyswatter** [comment]
I also now think this is a bug with how TokenFactory deals with BeerCoin (which is an abnormal token contract).

**Comment by flyswatter** [comment]
While I'm talking about TokenFactory, I think it would be cool if the front-page of TokenFactory linked to some popular EIP20 tokens, like Unicorns, etc, the way they did with myEtherWallet:
https://ipfs.pics/ipfs/Qmaumn3eKSyo6EGqZYKMdw4tXGPEaeB2dNQR5RsFzLov5A

**Comment by simondlr** [comment]
> I think it would be cool if the front-page of TokenFactory linked to some popular EIP20 tokens

Yip. Have had plans to add this.

I will check the errors this weekend somewhere. Cheers for reporting!

**Comment by simondlr** [comment]
I eventually found the bug. Trying to solve it. It has to do with token ABIs, which is turning out to be difficult to solve.

**Comment by flyswatter** [comment]
Closing this as a Tokenfactory issue, we're going to improve our stream failure handling in #523.
