### ISSUE TITLE
Can't access methods on web3 until console.log(web3.eth);

### ISSUE THREAD

**Issue by Manidos** [MetaMask/metamask-plugin#512]
OS: Windows 7, 32 bit
BROWSER: Chrome, v.51.0.2704.103 m
SERVER: NodeJs 5.11.0

- MetaMask injects **web3** object.

`console.log(web3);`
`object {...}`

- I try to **console.log** any method on it and get **undefined**:

`console.log(web3.toWei);`
`undefined`

- Then I try  **console.log(web3.eth)**:

`console.log('web3.eth');`
`r {_requestManager: s, compile: Object}`

- Then I try **(console.log(web3.toWei);** again and it **is** there!

`console.log('web3.toWei');`
`function (t,e){var n=x(t).times(b(e));return I(t)?n:n.toString(10)}`

**Comment by kumavis** [comment]
@Manidos we have some magic in place that avoids fully loading web3 until its used (bc its injected into every tab, including non-ethereum dapps). seems like we goof'd there. will fix.

Thanks!

**Comment by kumavis** [comment]
hmm actually the code looks a little different than i remember, but heres a starting point for whoever picks up this issue
https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/lib/auto-reload.js#L10

**Comment by flyswatter** [comment]
This issue will represent removing the lazy loading. We may re-add it correctly in a future issue.
