### ISSUE TITLE
fee display problem

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#513]
submitted by @sridhar87:

> I'm having an issue using Metamask - for the first transaction - I'm able to see the transaction value and fee properly. From the second transaction onwards, my fee is set to a high 50 million, and it is unlikely that transaction would be successful. This happened to me twice. Let us know if this is a known bug.

> Edit: Looks like it is a display problem. But in the history/transaction list, I'm able to see the correct values. Only when the user is prompted immediately when I call sendTransaction, I'm seeing this issue.

**Comment by kumavis** [comment]
TLDR:
fee in history/transaction list looks good
fee in conf page looks bad

**Comment by Zanibas** [comment]
Can't seem to reproduce. Can I get some specific steps? Is this also a notification issue?

**Comment by flyswatter** [comment]
This was from before we adopted the popup type tx confirmation, so I think this was implicitly fixed.  Closing for now.
