### ISSUE TITLE
Custom endpoint shows loader continuously

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#514]
> ok .. so on metamask .. the circular thing starts rotating and it never connects although it says trying to connect .. and at the same time my ubuntu system really gets slow …

![](https://files.slack.com/files-pri/T08427P1C-F1XLB7NP3/screen_shot_2016-08-02_at_9.13.39_pm.png)

**Comment by flyswatter** [comment]
Duplicated in #534
