### ISSUE TITLE
Ethereum Classic Network doesn't work.

### ISSUE THREAD

**Issue by AustP** [MetaMask/metamask-plugin#515]
Visit https://wallet.ethereum.org/ on the Main Ethereum Network and you will see that blocks are coming in.

![image](https://cloud.githubusercontent.com/assets/2007045/17352894/ffe20cc4-58f7-11e6-90a3-c4d649f2e692.png)

Now switch to the Ethereum Classic Network and you will see that no blocks are coming in.

![image](https://cloud.githubusercontent.com/assets/2007045/17352908/1ecf6582-58f8-11e6-8e6c-b1d5c4bf1764.png)

Alternatively, pasting the following in a web3 injected console will show transactions:

    web3 = new Web3(new Web3.providers.HttpProvider('https://mainnet.infura.io/'));
    web3.eth.filter('latest').watch(function(err, tx) {
        if (err) {
            console.log(err);
        } else {
            console.log('mainnet: ' + tx);
        }
    });

But if you paste the same code only updating the network, you will see no transactions:

    web3 = new Web3(new Web3.providers.HttpProvider('https://mainnet-nf.infura.io/'));
    web3.eth.filter('latest').watch(function(err, tx) {
        if (err) {
            console.log(err);
        } else {
            console.log('mainnet-nf: ' + tx);
        }
    });

**Comment by kumavis** [comment]
@hermanjunge can you take a look at this?

**Comment by Firescar96** [comment]
The node is back now, it lost all of it's ETC peers and couldn't sync to the network. We will work on getting a set of ETC bootnodes to prevent it happening again.

**Comment by Firescar96** [comment]
Infura and Metamask no longer support ETC (for the forseeable future)
