### ISSUE TITLE
Buy button on tx conf view

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-plugin#519]
- Dropping the buy button in the notification. 
possibly looking into switching from notifications to pop ups.
- In a perfect world hold the tx untill their is enough eth in balance. 
- And buy amount possibly have a input
- Buy amount cant be more then 5.

**Comment by frankiebee** [comment]
may be related with issue #361

**Comment by flyswatter** [comment]
Put `buy` button in the `conf-tx` template, and eventually in the notification once we use popups, too.

**Comment by kumavis** [comment]
put it here `pending-tx` template, not in `pending-tx-details` template
https://github.com/MetaMask/metamask-plugin/blob/master/ui/app/components/pending-tx.js
