### ISSUE TITLE
Event Filters - Support Pending Transaction Filters

### ISSUE THREAD

**Issue by Manidos** [MetaMask/metamask-plugin#521]
Hey! 
Here's my JS code:
```
var filter = web3.eth.filter('pending');
filter.watch(function (error, log) {
  console.log(log);  
});
```
As I understand it this snippet is supposed to log **hashes** of the most recent pending transactions. It's not happening in my case. I get only this in my browser:

![z2bqp](https://cloud.githubusercontent.com/assets/16019131/17517241/467cac68-5e64-11e6-8958-046f63b77cbb.png)

When I change the parameter to **latest** it works as intended:
```
var filter = web3.eth.filter('latest');
filter.watch(function (error, log) {
  console.log(log);  
});
```

**Comment by kumavis** [comment]
This is a confusing aspect of the web3.js API:
* filters for "latest" watch blocks.
* filters for "pending" watch pending txs

https://github.com/ethereum/wiki/wiki/JavaScript-API#parameters-29

Though you should still be seeing results for "pending".
Issue is that provider-engine does not currently support pending filters
https://github.com/MetaMask/provider-engine/issues/23
