### ISSUE TITLE
Prepare project for firefox addon market

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#522]
I've started the email thread, but this needs to be pushed further.

**Comment by flyswatter** [comment]
Reach out to Daniel for tips! (Our new MS contact w/ Mozilla experience)

**Comment by flyswatter** [comment]
Reached out to him.

**Comment by flyswatter** [comment]
Covers #487

**Comment by flyswatter** [comment]
I got a Mozilla PM contact from Daniel, I've reached out to them.

**Comment by flyswatter** [comment]
They seem to have changed the automated analysis process, maybe because of my earlier complaints?

I submitted for a preliminary review, not sure that will give full permissions, should be done in 3 days.  A full review takes 10 days, and I believe that's *per version*!

When it's done, it'll be available here:
https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/

**Comment by flyswatter** [comment]
They've re-applied the size limit, now raised to 4MB per file.

Our background.js file is now 200kb over 4MB, so to move this ticket forward, we need to decrease bundle size, either by minifying code, removing deps, or something.

This will not be affected by the new fox, b/c it's the background process.

When I use `discify` to analyze our bundle usage, it claims we have 400kb of lodash in our bundle, b/c of `eth-lightwallet`, but lodash shouldn't be that large. I think we're potentially bundling unused assets.

We also have `crypto-js`, which is 200kb, which *should* be redundant with some of `eth-lightwallet`'s imports.

**Comment by flyswatter** [comment]
Two new options for releasing to Firefox:

1. Mozilla seems to now permit self-signing if you self-host an update URL.
2. We're at 4.6MB, and 800KB is our old eth-lightwallet on `dev`, which we only use now to migrate old-style vaults.  If we release our firefox edition without the migration code, we could get the background script's size down to ~3.8MB, and then we just need to do a final compat QA pass.

**Comment by flyswatter** [comment]
We did this. We could publicize it at our will:
addons.mozilla.org/en-us/firefox/addon/ether-metamask

**Comment by nicexe** [comment]
https://addons.mozilla.org/en-us/firefox/addon/ether-metamask/ shows version 3.9.2 while the latest release is 3.9.12
