### ISSUE TITLE
Add sync methods to web3

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#525]
I don't personally strongly support this priority, but am opening it as a place to sound comments.

I got a user who really wanted sync methods on Reddit here:
https://www.reddit.com/r/ethereum/comments/4svuqp/comment/d6b1jsf

**Comment by kumavis** [comment]
Web3 is deprecating synchronous methods as it moves to websockets
https://github.com/ethereum/web3.js/issues/326
