### ISSUE TITLE
Discrepancy Between Popup and Notification Max Transaction Fee

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-plugin#526]
On EtherFaucet, when the page requests one ether from our account, the notification indicates that the max tx fee is none. However, upon checking the actual popup tx confirmation, there is actually a small fee involved.

I know this may be moot if we decide to switch to a dedicated window/tab for 'notifications', but just wanted to document the problem. It doesn't  seem to happen with larger max tx costs.

**Comment by flyswatter** [comment]
Postponing this fix until after we converge on a new notification system.

**Comment by kumavis** [comment]
![image](https://cloud.githubusercontent.com/assets/1474978/17650041/c0a6e364-61f7-11e6-8871-cab629526837.png)

![image](https://cloud.githubusercontent.com/assets/1474978/17650042/c4b800aa-61f7-11e6-8f4b-740ee96ddc8e.png)

**Comment by flyswatter** [comment]
Should be solved by #452
