### ISSUE TITLE
Fix bug where metamask returns provider's accounts

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#536]
### Summary

When visiting truffle apps for at least one user, the injected `web3.eth.accounts` returns the provider's accounts instead of metamask accounts.

### Introduction

Currently a problem experienced by @neerajsaran, I have been unable to replicate it myself.

Please correct me anywhere I'm wrong, @neerajsaran, but:

They're using a mac on Chrome, this bug is experienced with both geth and testrpc, with Truffle 2.x, and the current Chrome store build of MetaMask (2.7.3).

### Behavior

When going to normal pages, the injected `web3.eth.accunts` returns an array of the selected metamask account, this is fine.

However, when visiting a truffle application, it instead returns the top three truffle accounts in an array.

### Current suspects

- Hooked-wallet subprovider is somehow passing-through the accounts of the current provider instead of its own. (doesn't explain why not on mine)
- Truffle is doing some strange provider overwriting, but only on some specific version? (doesn't explain why not on mine)

Please use this thread to ask new questions of @neerajsaran, so we can try to track down this strange behavior.

**Comment by kumavis** [comment]
> Hooked-wallet subprovider is somehow passing-through the accounts of the current provider instead of its own. (doesn't explain why not on mine)

highly unlikely a single simple subprovider is failing, much more likely the metamask web3 provider is not being used. A simple test:
```js
web3.currentProvider.constructor.name // => "MetamaskInpageProvider" or "HttpProvider"
```

**Comment by kumavis** [comment]
> Truffle is doing some strange provider overwriting, but only on some specific version? (doesn't explain why not on mine)

more likely. tru@neerajsaran can you list the exact version of truffle you are using?
```
╭─kumavis@xyzs-MBP  ~/dev/metamask-crx ‹node-v6.3.1›  (inpage-fixes) 
╰─$ truffle version
Truffle v2.0.7
```

**Comment by neerajsaran** [comment]
Neerajs-MacBook-Pro:MetaMask Neeraj$ truffle -v
Truffle v2.0.4 - a development framework for Ethereum

**Comment by kumavis** [comment]
I didn't see any relevant-looking changes since `2.0.4`.

Here is where truffle bootstraps.
https://github.com/ConsenSys/truffle-default-builder/blob/417755546fad19be7d5db1d8de9ab1224dc4ca02/processors/post/bootstrap.js#L16-L22

**Comment by flyswatter** [comment]
Hey @neerajsaran, please try logging `web3.currentProvider.constructor.name`, our current theory is that Truffle was ignoring the Metamask provider.

**Comment by kumavis** [comment]
we are now reccomending awaiting page load
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#web3---ethereum-browser-environment-check

**Comment by kumavis** [comment]
Here is the bug over in truffle
https://github.com/ConsenSys/truffle/issues/236

**Comment by neerajsaran** [comment]
@flyswatter not sure if it make sense or not but i am getting value "i".
<img width="1222" alt="screen shot 2016-08-15 at 11 09 58 pm" src="https://cloud.githubusercontent.com/assets/19916332/17686796/8802b8f2-633d-11e6-9d7c-1a7f9941dbe2.png">

**Comment by flyswatter** [comment]
I don't know what would return `i`, but it's not the provider MetaMask injects. It may indeed be the Truffle race condition documented [here](https://github.com/ConsenSys/truffle/issues/236).

**Comment by neerajsaran** [comment]
ok thanks for the help. I will follow other ticket created.

**Comment by macbem** [comment]
Almost a year later, I'm still experiencing this bug on Truffle w/ testrpc.
