### ISSUE TITLE
Cant create new alt network when already connected to alt network

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#541]
![image](https://cloud.githubusercontent.com/assets/1474978/17653580/7b757d8c-624c-11e6-8bcb-221137cd3cb2.png)

**Comment by kumavis** [comment]
Would also be nice if it persisted alternate connections

**Comment by flyswatter** [comment]
MVP would be to always show "custom RPC" menu item at the bottom.
