### ISSUE TITLE
No way to copy Tx Hash from history

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#545]
If you are on a custom network, it wont link to a block explorer, and theres no way to see the full tx hash. should always have a copy button.

**Comment by kumavis** [comment]
theres litteraly a copy button, idk what im talking about

**Comment by flyswatter** [comment]
I think this is one of those parts we always said would be on the expanded tx list item. We've been putting that off for a while, but it would be easy to throw a copy button on in the meanwhile.

- Dan
