### ISSUE TITLE
Prevent negative values in amount.

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#546]
![image](https://cloud.githubusercontent.com/assets/1474978/17654244/be089ebe-6255-11e6-97a8-4d2ce8878b1b.png)

tx value should not be negative

**Comment by flyswatter** [comment]
Lol. Did you happen to save this state for UI tests?

- Dan

**Comment by flyswatter** [comment]
The send form is where this was created, it should have more validations.

**Comment by flyswatter** [comment]
Also verify `max total <= account balance`
