### ISSUE TITLE
Password encryption vulnerable to lookup / rainbow tables due to hard-coded salt

### ISSUE THREAD

**Issue by Gustav-Simonsson** [MetaMask/metamask-plugin#555]
This vulnerability is in the eth-lightwallet dependency: https://github.com/ConsenSys/eth-lightwallet/issues/109

**Comment by flyswatter** [comment]
Wow, thank you for catching this!  Are you doing a full audit of lightwallet, or did you just catch this by luck?

**Comment by kumavis** [comment]
@Gustav-Simonsson Thank you. Happy to provide you with any additional information you need to evaluate MetaMask.

**Comment by Gustav-Simonsson** [comment]
@flyswatter At http://string.technology/ we're trying out MetaMask for a few of our systems and found this while looking at how it's using keys.

**Comment by flyswatter** [comment]
I've submitted [a PR to eth-lightwallet](https://github.com/ConsenSys/eth-lightwallet/pull/111) that would allow us to adopt a per-vault salt.

**Comment by flyswatter** [comment]
In response to some feedback, I've submitted [a second PR to eth-lightwallet](https://github.com/ConsenSys/eth-lightwallet/pull/113) allowing a salted lightwallet constructor.

Once that's merged, we can modify metamask to use the new methods.
