### ISSUE TITLE
Forgot Password - Go Back

### ISSUE THREAD

**Issue by eshon** [MetaMask/metamask-plugin#563]
<img width="357" alt="screen shot 2016-08-20 at 9 34 21 am" src="https://cloud.githubusercontent.com/assets/1017762/17831547/c8e64896-66b9-11e6-9772-dc4959261fcf.png">

I forgot my password and now want to go back to the opening screen so I can create a new account. Might be nice to add a way to go back:

![mm_back](https://cloud.githubusercontent.com/assets/1017762/17831545/b43307f4-66b9-11e6-926d-00b92d65c15d.png)

**Comment by flyswatter** [comment]
What would it go back to? The initial screen that says create new vault or restore vault?

What if they press it by accident? Should we add another button like 'log in' to that first screen if they have an active vault?

- Dan

**Comment by eshon** [comment]
Yes.

**Comment by flyswatter** [comment]
I like that, this is a simpler design for #539, so I'm closing that one in favor of this.

**Comment by adrianbrink** [comment]
So, I don't have my seed or my password. How can I reset the entire thing and just start with a new account?

**Comment by comodoro** [comment]
Likewise. I did not save them for test networks. Do I have to reinstall the extension? And will it forget the old accounts, or do I have to delete something?

**Comment by KitKat6** [comment]
Likewise. Didn't find a way to reset the wallet.

**Comment by flyswatter** [comment]
If you lost both seed and password, you currently need to reinstall to clear MetaMask's state, sorry.

**Comment by jasperdg** [comment]
Even if I reinstall Brave my metamask data gets saved and asks for seed/password. What to do?

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking Metamask wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by richardsonn09** [comment]
@13403 
@adrianbrink 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com
