### ISSUE TITLE
Out of sync

### ISSUE THREAD

**Issue by FrankHold** [MetaMask/metamask-plugin#564]
"danfinlay: I just signed two txs in metamask but they don't seem to have been submitted to the blockchain. Have you heard people having this experience? This is Dan, from MetaMask."

Hi, I did try the same this morning and did not get a transaction through (empty transaction). Is it possible that metamask server is out of sync?

Thank you, 
Franky

**Comment by bamos01** [comment]
Im having the same problem- empty transactions - its not 100%- sometimes I get one through but its not reliable

**Comment by flyswatter** [comment]
Yes, node desynchronization is a bug that's known, and our backend team (Infura) is working on tooling to prevent it in the future.

The short term solution is connecting to a local rpc server.

- Dan

**Comment by FrankHold** [comment]
Thanks for the info!

**Comment by zoernert** [comment]
Could it be that the EventEmitter message showing in the console of the background page is related to this? I think it happens always on my site, if an EventEmitter "Max Listeners" message is shown directly after the message got signed.

**Comment by flyswatter** [comment]
That's an interesting lead, glad to have it documented on the issue.

**Comment by flyswatter** [comment]
The backend synchronization problem should be fixed, I'll leave this issue open until tomorrow for anyone to report a reoccurrence.

**Comment by jorisbontje** [comment]
Still out of sync on mainnet; the Infura nodes on mainnet are constantly throwing / triggering sync events. To reproduce / monitor:
```
web3.eth.isSyncing((error, sync) => {
    console.log('sync', error, sync);
})
```

**Comment by kumavis** [comment]
I think this issue will reappear at times as Infura grows and evolves and makes mistakes. I'll close it for now but feel free to comment on here again.

**Comment by kfichter** [comment]
Getting an out of sync issue as well. MetaMask doesn't see new entries into the storage of a contract unless I disable and then enable the plugin again.

**Comment by flyswatter** [comment]
That sounds like a fresh issue to me, @kfichter. Would you mind opening a new issue, mentioning your system/browser/version on it, with any reproduction steps you can provide?

**Comment by kfichter** [comment]
Sure thing, I'll do that right now.
