### ISSUE TITLE
Add a loading indicator for login

### ISSUE THREAD

**Issue by Firescar96** [MetaMask/metamask-plugin#599]
I found a bug where if I leave the locked client open in one window and go do other things for a minute or so, when I return Metamask is unlocked. This could be related to a variety of things: pollution from my uninstall and reinstallation, my use of the Chromium based Vivaldi browser, or my use of multiple workspaces.

I have a 3-4 minute video showing this in action, but I would prefer not to put it up publicly.

**Comment by flyswatter** [comment]
Haven't been able to reproduce, tried a 10 minute leave-open on mac/chrome.

Also inspected the logout code, confirmed we absolutely `delete` the keystore and idmgmt on logout, so this is still defying explanation.

I've given @Firescar96 instructions on logging the background process, hoping we can catch some error in the deleting the `keystore` and `idmgmt`, but no luck so far logging the issue.

**Comment by Firescar96** [comment]
How long should unlocking the wallet normally take?

**Comment by flyswatter** [comment]
Well in your example it takes a few minutes.

Normally this *should* never happen, so I can’t even speculate how long would be a fair test of this.

**Comment by Firescar96** [comment]
This isn't actually a unlocking bug, it just takes a long time for my client to unlock, when I was trying random passwords in my video I accidentally hit the right one.

**Comment by flyswatter** [comment]
OH??  So you'd entered a password, and *then* had to wait for minutes before it unlocked?!

That makes me think some of the websocket errors you were getting were in fact the comms channels between the background process & foreground.  Thanks for the clarification!

I'm not sure adding a loading indicator is a good enough fix, that's way too slow an unlock!
