### ISSUE TITLE
Transactions sometimes confirmed by RPC then never reach blockchain.

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#659]
We've had a few users report this, most recently @wighawag.

Seems like RPCs are receiving TXs, telling users they've been received, and then not relaying them to the blockchain sometimes.

Sounds like an Infura issue? @hermanjunge

**Comment by wighawag** [comment]
this issue happen while on the mainnet using  https://fdd.etherisc.com/

While metamask was telling me the tx was accepted it seems that the dapp was not aware as it was being silent. no popup came to confirm the tx hash.

This in contrast to when the tx actually get propagated, the dapp is in that case confirming me the tx hash and tell me that the policy has been accepted.

**Comment by kumavis** [comment]
This was resolved in provider-engine
