### ISSUE TITLE
Accounts screen has jumpy transition

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#670]
We've worked out most of our transition bugs, and most of our transitions are smooth looking.

One that still isn't (or got bad at some point) is the accounts screen entering view.

When first entering, the entire view is pushed down a little bit, like this:

![screen shot 2016-09-14 at 4 12 58 pm](https://cloud.githubusercontent.com/assets/542863/18533235/4fca9f02-7a96-11e6-9c36-6a81b2c858fd.png)

What you can't tell here (but can easily see in practice) is that once it arrives in place, this view jumps up a good bit.

I just did some investigating, and the solution did not seem as obvious to me as I'd hoped it would.  Opening an issue to ensure later investigation.

**Comment by Zanibas** [comment]
Should we wait for the new implementation of accounts screen before proceeding on this? Considering this blocked until then.

**Comment by flyswatter** [comment]
I don't think this is blocked by that, I think this is a CSS issue, and shouldn't touch any JS code.

**Comment by Zanibas** [comment]
Normally:
![screenshot from 2017-03-30 15-14-04](https://cloud.githubusercontent.com/assets/1840057/24521935/e4c509ca-155b-11e7-96ea-f35a3e155d07.png)

With a 1px black border around every element:
![screenshot from 2017-03-30 15-14-38](https://cloud.githubusercontent.com/assets/1840057/24521944/ede24090-155b-11e7-8b66-94c2dc11d45b.png)

Wot in tarnation, where did this random space between our navbar and the select account section come from?
