### ISSUE TITLE
Switching provider is no longer reloading dapps

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#695]
We used to auto-reload web dapps when we switched the provider, but this is no longer happening.

**Comment by kumavis** [comment]
Confirming that this is a bug. Investigating...

**Comment by kumavis** [comment]
seems like contentscript-page communication now dies on extension disconnect
not a big surprise, but new behavior

**Comment by kumavis** [comment]
this is challenging bc now we can only detect a disconnect by adding a heartbeat between inpage and contentscript

**Comment by kumavis** [comment]
fixed by https://github.com/MetaMask/metamask-plugin/pull/730
