### ISSUE TITLE
user: Balance Value currency not persisting

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#705]
submitted by @haiqu

> USD is the default setting, even if it's changed this isn't sticky.

seems to persist fine on restarts on `2.13.3`

**Comment by kumavis** [comment]
@haiqu please provide additional repro instructions or will close

**Comment by flyswatter** [comment]
If you check the changelog, you'll see this was just fixed, either yesterday or in today's release.

- Dan

**Comment by haiqu** [comment]
I'm on 2.13.2 and the one you mention isn't yet available. Will retest when I can update from Google store.

**Comment by flyswatter** [comment]
This should have been fixed, could you verify? https://github.com/MetaMask/metamask-plugin/blob/master/CHANGELOG.md#2132-2016-10-4

**Comment by haiqu** [comment]
Confirmed as fixed in 2.13.3
