### ISSUE TITLE
user: Unable to sendTx from mixed-case address

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#707]
submitted by @haiqu

> In the account selection dropbox my account number is shown in two ways: Original (upper and lower case) and Modified (all lower case). I had been selecting what I though was the correct account - Original - and the withdraw was failing. Tonight I tried the Modified account number and managed to successfully withdraw my remaining ETH.

**Comment by flyswatter** [comment]
Is this in the metamask plugin or some other Ðapp?

- Dan

**Comment by kumavis** [comment]
i left off some other relevant parts of the issue. the dropdown he's referencing is in the dapp, but when we submits the tx it doesnt work

**Comment by flyswatter** [comment]
It's funny, because we internally use checksums on addresses, but maybe:

- We don't checksum our injected current addresses.
- This dapp is adding a checksum to the current addresses.
- When we receive this format in the `from` field we fail it, because it doesn't exactly match any of ours.
