### ISSUE TITLE
Send -> Transaction Data field not parsed

### ISSUE THREAD

**Issue by haiqu** [MetaMask/metamask-plugin#713]
As a test I entered some random text into the Transaction Data field under the Send menu. The transaction appeared to go through but did not arrive at the destination address, and my Ether vanished into the ether.

I believe this field needs to be parsed for valid data before the send can be initiated.

**Comment by flyswatter** [comment]
Data validity is somewhat dependent on the code of the contract being sent to, so this would require some very accurate simulation of the effects of the tx.

Long term we look forward to giving good responsiveness for previewing a tx.

**Comment by haiqu** [comment]
OK, well at least pop up a warning when the user enters something there, eh. :)

**Comment by flyswatter** [comment]
Could you provide a transaction hash of the transaction that you entered random data in?

**Comment by haiqu** [comment]
0x61833148be051103503b9eb12e9b279cb498bcb2b4a533cacf94f67b0d03d038
0x074a24e962374521d2b82bd47d50f533f0d761f4cd4c7585c24ec2e284a26e85

First one was a transfer of 0.001 Eth from EtherDelta to my account, second was 0.01 Eth. I'm down less than $0.20 but someone might try a larger amount ...

- Rob

**Comment by kumavis** [comment]
https://testnet.etherscan.io/tx/0x61833148be051103503b9eb12e9b279cb498bcb2b4a533cacf94f67b0d03d038
https://etherscan.io/tx/0x61833148be051103503b9eb12e9b279cb498bcb2b4a533cacf94f67b0d03d038

**Comment by kumavis** [comment]
https://testnet.etherscan.io/tx/0x074a24e962374521d2b82bd47d50f533f0d761f4cd4c7585c24ec2e284a26e85
https://etherscan.io/tx/0x074a24e962374521d2b82bd47d50f533f0d761f4cd4c7585c24ec2e284a26e85

**Comment by kumavis** [comment]
none of these resolve in the block explorer

**Comment by kumavis** [comment]
what was your expected behavior?

**Comment by kumavis** [comment]
When I submit a tx with random data, I see the following error
![screen shot 2016-10-17 at 11 37 12 am](https://cloud.githubusercontent.com/assets/1474978/19450394/13673192-945e-11e6-8916-1abb38991ac0.png)

**Comment by kumavis** [comment]
Closing for now, can reopen if this is not resolved. Adding additional validation in #739

**Comment by haiqu** [comment]
I didn't get the warning above, and the funds vanished. But that was in 2.3.12 so maybe that has changed. If it happens again I'll reopen.
