### ISSUE TITLE
Fix incorrect DELEGATECALL warning

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#743]
We have a nice warning for when a contract is going to call another contract with your identity, it looks like this:

![screen shot 2016-10-17 at 12 44 03 pm](https://cloud.githubusercontent.com/assets/542863/19452877/91a0bd2c-9467-11e6-8a7a-e458439c4ae1.png)

But in this example, the warning is wrong!  This contract does not use `DELEGATECALL`, so something else is wrong, probably in our warning display logic.

**Comment by flyswatter** [comment]
More important is the contract code throwing the warning.  The `getCode` response throwing this warning is this:

```
0x606060405260e060020a60003504637bd703e8811461003157806390b98a111461005c578063f8b2cb4f1461008e575b005b6100b4600435600073f28c53067227848f8145355c455da5cfdd20e3136396e4ee3d6100da84610095565b6100c660043560243533600160a060020a03166000908152602081905260408120548290101561011f57506000610189565b6100b46004355b600160a060020a0381166000908152602081905260409020545b919050565b60408051918252519081900360200190f35b604080519115158252519081900360200190f35b60026040518360e060020a02815260040180838152602001828152602001925050506020604051808303818660325a03f4156100025750506040515191506100af9050565b33600160a060020a0390811660008181526020818152604080832080548890039055938716808352918490208054870190558351868152935191937fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef929081900390910190a35060015b9291505056
```

**Comment by flyswatter** [comment]
I've replicated this bug with a test in [this PR].

I believe it's a problem with `eth-bin-to-ops`, and specifically its `pushDataLength` [logic](https://github.com/ethereumjs/bin-to-ops/blob/master/index.js#L17), but I'm not really familiar with what it should be.

@kumavis would you like to pick this up? You've spent much more time at the VM layer than me.

**Comment by kumavis** [comment]
@flyswatter 
So this was addressed in https://github.com/MetaMask/metamask-plugin/pull/745
The conclusion was that the assumption is incorrect -- this code does in fact contain a `delegate_call`.
 Where did this code come from and why do you think it doesn't have a `delegate_call`?

**Comment by kumavis** [comment]
we discussed on a call that this was indeed a mistaken assumption
