### ISSUE TITLE
Infinite reload bug

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#746]
Submitted by "joe" on our Slack.

His app, [Community](https://github.com/ChicoBitcoinJoe/Community) is experiencing an infinite refresh bug.

The console shows this error:

![screen shot 2016-10-18 at 1 15 59 pm](https://cloud.githubusercontent.com/assets/542863/19494684/248bfcc8-9535-11e6-8746-84ddb818fd28.png)

**Comment by flyswatter** [comment]
Those errors are from `ipfs`, I don't think they're related.

It does not always get stuck in this loop.

**Comment by flyswatter** [comment]
The reload is being called by the `endOfStream(PingStream, triggerReload)` line.

The `PingStream` is timing out, so we need a more tolerant way of handling a ping timeout than reloading.

**Comment by kumavis** [comment]
The change we made to "fix" this was based on a misunderstanding -- reverting that change which may cause this issue to re-appear.

**Comment by kumavis** [comment]
@ropod7 
I will take another look at this

**Comment by kumavis** [comment]
We are calculating extension comms failure with a setTimeout -- messages seemed to be blocked, and then the timeout triggers the redirect.

I think we could use a series of smaller setTimeouts to calculate an unblocked time span

**Comment by ropod7** [comment]
It's fixed. Thanks!
