### ISSUE TITLE
Cryptonator API seems is blocking us

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#753]
request result is some ddos protector page
https://gist.github.com/kumavis/277616195606b9904e6c31d38e0ca43d

**Comment by flyswatter** [comment]
We should probably just host our own cached version of that endpoint for our users.

- Dan

**Comment by kumavis** [comment]
but what if infura...

**Comment by flyswatter** [comment]
Yeah, either way, it should be a light enough script to not need much fussing over.

**Comment by flyswatter** [comment]
Infura is currently working on an API like this for us, and we're working on what it should look like.

**Comment by Zanibas** [comment]
Asked for an update, will see what comes back.
