### ISSUE TITLE
Ipfs async call triggering error with metamask related files

### ISSUE THREAD

**Issue by ChicoBitcoinJoe** [MetaMask/metamask-plugin#754]
This code
![image](https://cloud.githubusercontent.com/assets/21048886/19545288/e4dfcf54-9639-11e6-98d5-cee7f5daef7c.png)

triggers this error
![image](https://cloud.githubusercontent.com/assets/21048886/19545277/cdd41a68-9639-11e6-8ef1-b1d8d49f674c.png)

The branch with where this error can be reproduced is at https://github.com/ChicoBitcoinJoe/Community/tree/MetaMask-Bug-Hunting

**Comment by flyswatter** [comment]
Oh man, sorry for not getting to this yet, is this still an issue for you, @ChicoBitcoinJoe?
