### ISSUE TITLE
Accept/Deny Tx panel never loads the accept deny buttons

### ISSUE THREAD

**Issue by ChicoBitcoinJoe** [MetaMask/metamask-plugin#755]
- Using a slow internet connection
- Chrome Icon correctly showed a pending tx

![image](https://cloud.githubusercontent.com/assets/21048886/19545428/ff5a0128-963a-11e6-8972-05c90fbf279f.png)

**Comment by flyswatter** [comment]
@frankiebee I wonder if this could be related to the bug we were looking at earlier today, where a geth rejection throws no error, simply returns no tx hash, and so we log the tx in the list, but it has no link?

**Comment by frankiebee** [comment]
@ChicoBitcoinJoe  is it possible to provide the params (or more detail) for the tx so I can try and replicate this.

**Comment by ChicoBitcoinJoe** [comment]
@frankiebee This is the tx info https://testnet.etherscan.io/tx/0xdba6b8042b692e4a9e6b69a7a96e5b6ef6c4b73806994d0ae3704a9f62e4cb32

I create the tx in my dapp here 
https://github.com/ChicoBitcoinJoe/Community/blob/MetaMask-Bug-Hunting/services/LinkDB.js#L165

**Comment by flyswatter** [comment]
Just came back to this for the first time in a while, not sure what the problem was.  Can you update on this, @ChicoBitcoinJoe?  Have you ever seen this again?
