### ISSUE TITLE
Deadly estimation

### ISSUE THREAD

**Issue by chevdor** [MetaMask/metamask-plugin#756]
This happens when trying to send funds to a contract that probably does not behave nice.
I am using version from master at commit 229d95956bc36ec413533df00389f8c5127e050b

Some paths are redacted but the little useful left is there.

![screen_shot_2016-10-21_at_20_06_57](https://cloud.githubusercontent.com/assets/738724/19607469/553df596-97ca-11e6-9d81-66609a202e51.png)

**Comment by chevdor** [comment]
This test was made against testrpc btw.

**Comment by kumavis** [comment]
@chevdor wait why did you redact the paths

**Comment by kumavis** [comment]
we dont use `subproviders/vm`... strange

**Comment by kumavis** [comment]
Oh you are using testrpc - this is an error from the rpc endpoint (testrpc) that we are displaying

**Comment by kumavis** [comment]
you'll need to file an issue https://github.com/ethereumjs/testrpc/issues/new including the target contract code and the tx params (value, data, etc)

**Comment by chevdor** [comment]
@kumavis I redacted stuff that are not interesting or relevant like `/Users/bob/MyTopSecretProject/...`

While I don´t mind reporting an issue to testrpc, I still think it should be at least handled properly in metamask with a more friendly message. Such message does not help adoption.

**Comment by kumavis** [comment]
@chevdor can you suggest some language that would make the error more straight forward?

**Comment by flyswatter** [comment]
I think the first line (the `error.message`) would be fine, if we excluded the stack trace, and formatted it better.

**Comment by ethernomad** [comment]
Related? https://github.com/ethereum/go-ethereum/issues/3163

**Comment by flyswatter** [comment]
Probably not, since this was on testrpc, although better error handling is still important.

**Comment by chevdor** [comment]
What is not cool for the user is to get the extension filled up with a stack trace they cannot use.
As @flyswatter I think using only error.message would be fine: Moreover, this is not just failing the tx, it is kind 'craching' (if I can say that for an extension) as it puts it in a state where the user cannot move on.

So I would suggest using:
- error.message
- handling the exception so that some kind back button allows coming back to the main screen of the extension

I will check if I can put a faulty contract on testnet to help with testing.

**Comment by chevdor** [comment]
After double checking, I see that we have this back button. Honestly, the rest was so red and 'scary' (think about the normal Joe...) that I missed the button :)

**Comment by flyswatter** [comment]
Oh this must be a testrpc error! The stack is from them!

- Dan

**Comment by flyswatter** [comment]
I'm trying to find where this awful formatting gets concatenated, but having trouble.

@chevdor, could you either:

1. Provide me with some solidity to create a contract with this estimation hazard
2. Paste a [ui state log](https://github.com/MetaMask/faq/blob/master/LOGS.md#ui-state-logs-chrome) here?

For the UI state log, you might want to edit the account address fields and `transactions` history hash.

I could also write you an anonymizing script for that log file, it would be a good resource anyway.

**Comment by chevdor** [comment]
@flyswatter I am currently trying to reproduce the issue on tesnet. I keep you updated.

**Comment by chevdor** [comment]
I could not reproduce this issue on testnet...
As @flyswatter I would suggest making the error more friendly and that should do.

**Comment by Zanibas** [comment]
@chevdor quick question: when you first got the error on your original post: was this after you attempted submission of the transaction on the MetaMask side, or did this warning appear as soon as the confirm transaction screen appeared?

**Comment by flyswatter** [comment]
@Zanibas I've talked through this a few times with Chevdor, so I'm pretty sure:
- This is from our normal `send` screen.
- We transition to the confirmation screen after hitting `send` (check our actions)
- This is the enormous warning that shows up when the tx couldn't actually be prepared for a confirmation, but the confirmation view is shown.

**Comment by chevdor** [comment]
@Zanibas Sorry for the delayed answer, the reason is that it is already a while ago and I have no idea anymore so I need to check again. However, since the BACK arrow points back to CONFIRM TX, I am 99% sure this is after clicking the approve/confirm button.

**Comment by Zanibas** [comment]
Attempt: fixed by #811
