### ISSUE TITLE
Morden Test Network and Localhost 8545 both showing selection checkmark

### ISSUE THREAD

**Issue by jorisbontje** [MetaMask/metamask-plugin#761]
With MetaMask 2.13.5:

1) I select network "Localhost 8545"
2) When I get back to the metamask extension, "Morden Test Net" is shown in the header
3) When I click on the red "Morden Test Net" line, both "Morden Test Net" and "Localhost 8545" have an orange selection checkmark. See screenshot: 
![screenshot 2016-10-24 16 22 04](https://cloud.githubusercontent.com/assets/620959/19649561/91448922-9a06-11e6-8397-3c16e3cfe731.png)

I would expect only "Localhost 8545" to have an orange checkmark.

**Comment by flyswatter** [comment]
I agree this isn't what I'd expect.  Is your local node running Morden?

**Comment by flyswatter** [comment]
That sounds like a reasonable expectation. Is your local node running morden by any chance?

- Dan

**Comment by jorisbontje** [comment]
Yes. My local parity node was running Morden.
