### ISSUE TITLE
Allow custom gas limits in send view

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#765]

**Comment by Zanibas** [comment]
Our send view is already crowded as is: where shall we place the input for a gas limit?

Also, should gas limits be expressed as a hard number or as a multiplier, aka a field or a slider?

**Comment by flyswatter** [comment]
The view should be scrollable, and if we want to simplify it, we should have a collapsible advanced section, maybe using section details tags

- Dan
