### ISSUE TITLE
Mainnet Metamask taking unusually large fees?

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#770]
On our slack, submitted by jacksmies:

jacksmies [9:24 PM]  

> Hello guys, I have an issue. I am sending a small amount of ether 0.01ETH but metamask is adding a very high fee, 2ETH. What am i doing wrong?

jacksmies [9:34 PM]  

> it works fine on the testnet. There 0.01ETH takes 0.015 in fees

**Comment by Zanibas** [comment]
Messaged jacksmies for more details--could not reproduce on Main with our latest production build.
