### ISSUE TITLE
Remove extension api from popup/background

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#775]
These should be replaced with some WindowController or something that is built for the platform (extension, mascara, etc)

e.g.

``` js
extension.tabs.create
extension.windows.create
extension.runtime.getManifest
extension.windows.update
extension.windows.getAll
```

**Comment by flyswatter** [comment]
Just to clarify: `background` is the right place for these platform-specifics.  It's the other files, like the UI or the metamask-controller and its children, that needs these cleaned out.

**Comment by frankiebee** [comment]
yup yup

**Comment by flyswatter** [comment]
Based on what Aaron points out there, I think there are actually two distinct things there the platform should provide:

- A window manager
- A manifest equivalent (whatever we use from the manifest, which may merely be the version number).

**Comment by kumavis** [comment]
reposting from #1291 
in order for metamask to work on different platforms / in different environments ( extension, metamascara, electron... ), we need to move all the platform dependent parts out of the core libraries

main offender: `metamaskController`
also: ui's `info` screen

some notes:

```
  ui
    connect to background
    notification
  proxy
    connect to background
  background
    notification
    metamaskController

  notification
    window mgmt
      extension.windows

  metamaskController
    window mgmt
      extension.tabs.create({ url })
    set rpc provider
      extension.runtime.reload()
```
