### ISSUE TITLE
Use ServiceWorker

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#776]
`background.js` should live in a service worker inside the iframe.
This allows us to share a cache and avoids conflicts of multiple instances writing the state to localstorage.

downsides: not great browser support.
http://caniuse.com/#search=serviceworker
https://jakearchibald.github.io/isserviceworkerready/

**Comment by frankiebee** [comment]
https://github.com/frankiebee/BackgroundSW

**Comment by kumavis** [comment]
Wheee~
