### ISSUE TITLE
tx's not being signed when coming from example dapp

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-plugin#779]
frankiep [4:40 PM]   

> okay after a brief walk through it does not ever hit signTransaction in metamask-controller when you sign a transaction and are debugging from the popup side. but does try to sign from controller.js after hitting sync tx but before the popup has loaded

**Comment by frankiebee** [comment]
this is due to the fact that we do not persist the callbacks and this cause a los of the call back for signing

**Comment by kumavis** [comment]
ok so our solution is:
1) make wallet subprovider where we have more control over approval and signing
2) extract the txExtraDetailsFiller into a utility

**Comment by kumavis** [comment]
This has been resolved and published to the chrome store. rejoice!
