### ISSUE TITLE
Gracefully handle testrpc -f mode

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#783]
Reported by @Schaeff:

When he uses the new `testrpc -f $RPC_URL` flag to fork an existing blockchain with testrpc, he gets some strange behavior on metamask:
- Account balance drops to 0, does not update until first block is mined.
- Tx history persists, and new txs here will be saved even after he un-forks.

These are kindof rare cases, but if developers make `-f` a common flag, we might want to accommodate it.

**Comment by flyswatter** [comment]
@Schaeff

**Comment by flyswatter** [comment]
Thanks to @Schaeff for coming up with this workaround:

He says:
`testrpc -f $RPC_URL -i 898989898989` solves the problem of MM merging forked and original transaction histories
(`-i` sets a custom `networkId`)
Still requires mining a block though

**Comment by kumavis** [comment]
testrpc networkId issue https://github.com/ethereumjs/testrpc/issues/189

**Comment by kumavis** [comment]
dan sez:
* the account balance issue is fixed after the first block i mined.
* the tx history is based on the network id, i think testrpc should use a unique test network id when forking

**Comment by kumavis** [comment]
TODO: confirm that when using a forked chain, initial balance RPC requests return a 0 balance

**Comment by kumavis** [comment]
fork network id https://github.com/ethereumjs/testrpc/issues/195

**Comment by flyswatter** [comment]
Closing since we have a good workaround, and have proposed better fixes in other projects.
