### ISSUE TITLE
Webpages sometimes lose connection and do not re-establish

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#790]
From @chevdor

It seems that metamask is losing it sometimes randomly: `index.js:54 Uncaught Error: StreamProvider - Unknown response id(…)` That a critical issue because my DAPP then seems to lose the connection to web3 and a reload is required. Is is a known issue? It occurs randomly (apparently)

I thought we added connection re-establishing already, so I'm not sure why it sometimes requires a reload.

**Comment by chevdor** [comment]
Full details in #791

**Comment by flyswatter** [comment]
He continued elsewhere:

which follows:
```
inpage-provider.js:14 MetamaskInpageProvider - lost connection to MetaMask
```
That is uncool :slightly_smiling_face:

it seems to happen when I call a contract function, sometimes

**Comment by chevdor** [comment]
I would not say it loses the connection and does not re-establish as the extension keeps running fine. However, the contract call that was never made never succeeds or/and no feedback comes back. See #791 for the details.

**Comment by flyswatter** [comment]
Closed as duplicate
