### ISSUE TITLE
Events in Metamask

### ISSUE THREAD

**Issue by sanchez5674** [MetaMask/metamask-plugin#792]
Hi, 

I've taken a very simple example from here:

https://github.com/frozeman/simple-dapp-example

And, I'm trying to run it using Metamask instead of Geth. Everything works fine after making the calls asynchronous but I can't seem to get the Dapp to trigger on the Deposit events. 

The solidity contract is as follows:
```
contract GuessNumber{
    
    uint8 number;
    
    event Deposit(address from, uint value);
    event SetNumber();

    function() {
        if (msg.value >= 0)
            Deposit(msg.sender, msg.value);
    }
    
    function setNumber(uint8 givenNumber) {
        number = givenNumber;
        SetNumber();
    }
    
    function guessNumber(uint8 givenNumber) constant returns (bool) {
        return (givenNumber == number);
    }
}
```
I can check if someone has set the number:

```
// Check if somebody set a number
GuessNumberInstance.SetNumber({}).watch(function(e, log) {
    if(!e) {
        console.log('A new number was set on block #'+ log.blockNumber);
        alert('A new number was set on block #'+ log.blockNumber + ' Try to guess!');
    }
});
```

However, when I try to check a Deposit it does not seem to work:

```
// Check if money arrived
GuessNumberInstance.Deposit({},{fromBlock: 0, toBlock: 'latest'}).watch(function(e, log) {
	if(!e) {
        console.log('Money arrived! From:'+ log.args.from, log.args.value.toString(10));

         // add the transaction to our collection (miniMongo)
        Deposits.upsert('tx_'+ log.transactionHash ,{
            from: log.args.from,
            value: log.args.value.toString(10),
            blockNumber: log.blockNumber
        }); 
    }
	else
		console.log("Something went wrong!")
});
```

Thanks in advance for the help. 

Carlos

**Comment by kumavis** [comment]
@sanchez5674 hi. what network are you using? morden? testrpc? can you give me addresses of some contracts you've published and tx's that have triggered a Deposit event?

**Comment by kumavis** [comment]
note that querying the whole blockchain for events is not a reasonable request. That must search through millions of blocks for events, and will fail.
`fromBlock: 0, toBlock: 'latest'`

**Comment by sanchez5674** [comment]
Hi, 

I'm using Morden. Is it possible to connect to testrpc from Metamask? 

This is the address to the contract:

https://testnet.etherscan.io/address/0x1cd7aa7d71d6a42c4fa57ad574fa3805f17729ee

I agree that searching through the entire blockchain is probably not the best idea. But, is it possible to just get blocks from a given address? 

Thanks for the help. 

Carlos

**Comment by kumavis** [comment]
@sanchez5674
> to just get blocks from a given address

im not sure exactly what you mean, but looking up events is expensive right now, and nodes (especially light clients) can't guarantee that historical events will be available

**Comment by kumavis** [comment]
> Is it possible to connect to testrpc from Metamask? 

yes, you can set the network to point at localhost:8545 and run [ethereumjs-testrpc](https://github.com/ethereumjs/testrpc)

**Comment by kumavis** [comment]
how should we handle unreasonable requests? currently the request runs until we timeout.

**Comment by kumavis** [comment]
can make a provider-engine middleware that emits a warning when you are requesting logs over too many blocks

**Comment by stiv-yakovenko** [comment]
Yes, it looks like web3 api for accessing events with metamask is not working: https://ethereum.stackexchange.com/questions/21048/listen-to-blockchain-events-in-js#comment21688_21048
