### ISSUE TITLE
Gas buffer not effective

### ISSUE THREAD

**Issue by chevdor** [MetaMask/metamask-plugin#798]
I just tested (partly) 2.13.7. The gas issue is still there at least for payment from within metamask. 

See https://testnet.etherscan.io/tx/0x2a5e3e360e116613ca421b5694ea1e16afedc4d1bc744c0642b14c3bd0563645

31640 needed, 31640 passed             => NOT OK
 
To compare with a transfer (same value) from Parity: https://testnet.etherscan.io/tx/0xbc60c9259f12a0c5daa407e2f40e9a78cffe8b327478c0391fd7303c753aec14

31640 needed, 37968 passed (31640+20%)   => OK

**Comment by chevdor** [comment]
see #795 The fix there is probably ok but missing in other places ?

**Comment by Zanibas** [comment]
#801 hopefully should take care of this @chevdor! We'll push this fix in the next weekly release.
