### ISSUE TITLE
State variables not visible in browser-solidity

### ISSUE THREAD

**Issue by TbLtzk** [MetaMask/metamask-plugin#800]
Hi, I'm new here, so please indulge if the issue is not even about metamask but rather the solidity-browser compiler. I Use MetaMask on the morden testnetwork and I have deployed this contract:
```pragma solidity ^0.4.0;
contract StateHolder {
    address public owner;

    uint public openNumber;
    string public openString;
    string public myString;

    function StateHolder() {
        owner = msg.sender;
    }

    function changeOpenNumber(uint _newNumber) {
        openNumber = _newNumber;
    }

    function changeOpenString(string _newString) {
        openString = _newString;
    }

    function changeMyString(string _newString) {
        if (msg.sender != owner)
            throw;
			
        myString = _newString;
    }
}
```
The contract sits here and seems all right:
https://testnet.etherscan.io/address/0xc0771e9af291f4378141bec751d089348d19aba9.

However if I go to https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.4+commit.4633f3de.js and watch the contract address, all state variables are undefined.

[Update]
You can use https://ethereum.github.io/browser-solidity/?gist=0a2acac5d68d558a0f2a8ac944ef87f2 to load the above contract right away <<<

![image](https://cloud.githubusercontent.com/assets/8383712/20140858/c6785644-a68d-11e6-8638-e8044b2f0be7.png)

I even managed to submit a transaction (writing to the myString variable) (see second transaction on the contract), so I would expect the owner field to be `0x9d4Ce9074D802A3D4EFC6F6cc14d016e8a7B0CC4` and myString should be `TestOpenString`.

**Comment by flyswatter** [comment]
Hi there!

Sorry for the delay in a response.

Checking `myString` in MetaMask issues a query equivalent to this curl request:

```bash
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{ "data": "0x492bfa18", "from": "0x55e2780588aa5000f464f700d2676fd0a22ee160", "gas": "0x2dc6c0", "to": "0xc0771e9af291f4378141bec751d089348d19aba9", "value": "0x0" }, "latest"],"id":1}' https://mainnet.infura.io/metamask
```
This returns the essentially empty response:
```
{"jsonrpc":"2.0","result":"0x","id":1}
```
Right now, Metamask's backend (Infura) is using Parity as its nodes. This makes it look like either:
- The contract has a null return value for that field
- Parity has a bug.

I'm getting access to a geth node now that I can run this same command against for comparison.

**Comment by TbLtzk** [comment]
Hmm, maybe it's the problem of mainnet vs. testnet.
I have metamask configured to run on morden testnet and this is where the contract has been deployed.
But the query suggests it queries mainnet

>... https://**mainnet**.infura.io/metamask

Thanks for your help, Dan!

**Comment by flyswatter** [comment]
Ah, can't believe I didn't check that. I would suggest:
- Browser-solidity should include the deployed network on their link, and warn users when they're viewing from the wrong network.

Are you getting the behavior you want on testnet?  I'm getting a very different result, but it still doesn't look right:

```json
{"jsonrpc":"2.0","result":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000","id":1}
```

Which results in an error over `myString` that says `Failed to decode output: Error: Invalid offset: 0`.

**Comment by flyswatter** [comment]
Sounds like we got this, so I'm closing this.

**Comment by TbLtzk** [comment]
Ah sorry I didn't respond to your previous comment. I would also say the result on the testnet was not correct either. Maybe it was a confusion with Morden testnet vs. ropster Testnet.
The url on etherscan now changed to https://morden.etherscan.io/address/0xC0771e9AF291F4378141bEc751D089348D19ABa9
And Metamask must be configured to use morden as well. Now, if I do this the contract variables don't get displayed at all
![image](https://cloud.githubusercontent.com/assets/8383712/20532871/d879f6b0-b0db-11e6-858e-593df26818a4.png)

**Comment by flyswatter** [comment]
I don't know if you have followed this news, but [Morden is basically broken](https://blog.ethereum.org/2016/11/20/from-morden-to-ropsten/), so while it's possible it *was* broken because of Morden, it's unlikely that it suddenly fixed itself.

I would recommend re-trying this experiment on Ropsten, mainnet, or a testrpc.

**Comment by TbLtzk** [comment]
Ok, thx for the info and your help. I'll do as you suggest and try on Ropsten. We'll see

**Comment by TbLtzk** [comment]
On ropsten I cannot even deploy the contract:

I've configured metamask to ropsten and provided with sufficient test ether
![image](https://cloud.githubusercontent.com/assets/8383712/20601063/f6d820e2-b256-11e6-9d25-4aec8bf3155b.png)
Now, if I click on create button within browser solidity, MetaMask does not show up to confirm contract deployment. Instead, the browser solidity indicates 'waiting for transaction to be mined' and gets stuck like this.
![image](https://cloud.githubusercontent.com/assets/8383712/20601197/9cab8310-b257-11e6-97cb-f2c11da950d5.png)

**Comment by flyswatter** [comment]
I believe there is a different issue going on, and that browser-solidity may have recently broke compatibility.

https://github.com/ethereum/browser-solidity/issues/342#issuecomment-262764137

**Comment by TbLtzk** [comment]
Ok, then i will have an eye on that one first. Thanks!
