### ISSUE TITLE
Refactor Tx details and gas calculations

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-plugin#803]
There is a lot of repeated code in `pending-tx-details` and in `idStore` that calculates gas costs. We should both reduce repeated code as well as separate concerns of view and calculations.

**Comment by kumavis** [comment]
this much math should be in the background, not the view

**Comment by kumavis** [comment]
test comment

**Comment by kumavis** [comment]
test 2

**Comment by flyswatter** [comment]
This is going to be part of the Tx-Manager.
