### ISSUE TITLE
Signing and submitting txs is long

### ISSUE THREAD

**Issue by chevdor** [MetaMask/metamask-plugin#817]
When a user/dapp submits a tx, I suppose that the request to sent to the node that returns the tx hash. Currently, that can take from 15s to more than 2 minutes.
What can be done to improve the user experience and keep updated on the progress?

The issue can be seen here: https://ethincorp.com/beta/
When the user click the green CREATE button, Metamask shows up and asks for confirmation.
So far so good.

Once the user confirmed the action, the DAPP gets no more heartbeat until the tx hash comes back loooonnnng after.

How could that be improved? Is there a way to get the tx hash back faster?
I usually see it already in Etherscan way before it is returned by Metamask.

**Comment by flyswatter** [comment]
That does sound wrong. We should call back to the dapp as soon as we have a tx hash.

**Comment by chevdor** [comment]
If you open your devtools, I am displaying the tx hash as soon as I (=the DAPP) gets it so you will see it (at least for now). Right now, it seems to take very long (like minutes if at all).

Having to wait for the receipt is then more than fine but IMO, the tx hash should come back much much quicker.

Right now, I got one that failed after 240s. The interesting thing is that you DO return the tx hash in the timeout message.
`Exception which calling the create function Error: Transaction 0x580a09d1857e265e6b5a31170d1837d2c5c9cf557cd02a97d6907ed7619530bc wasn't processed in 240 seconds!(…)`

But indeed, this tx never made it to the network for some reason.

**Comment by flyswatter** [comment]
Right, I'm not disagreeing. I'm saying it *should* do that. We should make sure it does that.

**Comment by flyswatter** [comment]
Is this still an issue for you?
