### ISSUE TITLE
Add Ropsten link support

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#834]
Our [initial Ropsten comptibility PR](https://github.com/MetaMask/metamask-plugin/pull/833) was unable to make tx links work for Ropsten, because we rely on Etherscan, which has not added Ropsten support yet.

This issue will remain open until we are able to add ropsten link support in `ui/lib/account-link.js`.

**Comment by kumavis** [comment]
`testnet.etherscan.io` now refers to the new testnet
