### ISSUE TITLE
Ether dissapears when switching from Morden to Ropsten

### ISSUE THREAD

**Issue by sanchez5674** [MetaMask/metamask-plugin#861]
Hi, 

Maybe this is what is supposed but the test ether I have in Morden disappears when switching to Ropsten. The wallet address are exactly the same so I'm not sure why that would happen. In any case, is there a way to get the ether back? 

Carlos

**Comment by Zanibas** [comment]
Ropsten is an entirely new chain, separate from Morden, so you will lose all your either when switching. However, you can get new ether easily from our faucet at this address if you need to!

https://faucet.metamask.io/

**Comment by kumavis** [comment]
@sanchez5674 let us know if you have any more q's about the new test network
