### ISSUE TITLE
link to ropsten faucet upon clicking buy when using ropsten network

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-plugin#862]
Hi,

I noticed that there no link to faucet anymore when in testnet. 
It is very useful for newcomers to be able to get testnet from the faucet. THis way they can test dapps without the need to get from somewhere else

Is it possible to have this back ?

Thanks

**Comment by flyswatter** [comment]
We're adding this back, we didn't have a Ropsten faucet yet yesterday.

We'll probably be adding auto-fauceting and a faucet link back today.

**Comment by wighawag** [comment]
Great! thanks for the quick updates!
