### ISSUE TITLE
Metamask plugin is quite slow at times (ui freeze)

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-plugin#863]
Upon clicking on the fox icon, the metamask plugin popup takes time to appear and can be frozen sometimes.

Similarly and to a greater extent the transaction popup freeze quite often. I can hear my pc's fan speeding up too. The UI is sometime non responsive.

System tested : Windows 7 chrome Version 54.0.2840.99 m

**Comment by Zanibas** [comment]
Does this also happen on fresh install, or after the app has been installed for some time?

**Comment by wighawag** [comment]
I just tried and it seems that on fresh install (or browser reboot) it is faster (though a bit slower to respond to the plugin icon than other plugin).
It seems it get slower as more tx popup appear

**Comment by flyswatter** [comment]
Closing as duplicate of #789
