### ISSUE TITLE
Tx Gas Limit Issue - Testrpc

### ISSUE THREAD

**Issue by gnazarkin** [MetaMask/metamask-plugin#877]
Getting "tx has a higher gas limit than the block" with any gasLimit set when trying to send transaction or deploy a new contract on testrpc using Metamask. Doesn't happen on mainnet, and only happens on testrpc when using Metamask

**Comment by kumavis** [comment]
duplicate of https://github.com/MetaMask/metamask-plugin/issues/868
fix published moments ago as *2.13.10* , plugin will auto update within the hour
