### ISSUE TITLE
web3.reset(true) is not working

### ISSUE THREAD

**Issue by nanexcool** [MetaMask/metamask-plugin#882]
Calling `web3.reset(true)` gives an error:

Uncaught Error: The MetaMask Web3 object does not support synchronous methods like eth_uninstallFilter without a callback parameter.

Error is being thrown in `app/scripts/lib/inpage-provider.js` 

https://github.com/MetaMask/metamask-plugin/blob/626903e9f237163fe00132c777435caa845ad3f3/app/scripts/lib/inpage-provider.js#L66

**Comment by flyswatter** [comment]
Looks like you're the first person to try using that method on a project using `provider-engine`!

We need to add support to the `reset()` call to the filter subprovider, which should remove all filters, as well as remove our sanitization warning that throws the error you saw for this method.

You can see where we handle local filters [here](https://github.com/MetaMask/provider-engine/blob/master/subproviders/filters.js#L51-L90).

**Comment by kumavis** [comment]
This is blocked by finishing the big provider-engine refactor so we can have filters per-dapp instead of shared

**Comment by flyswatter** [comment]
@denisgranha reports he gets the same error for `uninstallFilter`, it seems like basically the same issue, would you agree?

**Comment by kumavis** [comment]
@flyswatter `Uncaught Error: The MetaMask Web3 object does not support synchronous methods like eth_uninstallFilter without a callback parameter.` error? If so thats a bug. Assuming he is indeed providing a callback.

**Comment by kumavis** [comment]
I suppose we can support sync for methods that dont return a result, like uninstall

**Comment by nanexcool** [comment]
@kumavis  I don't think you can provide a callback, at least not in `web3.reset`.

We're calling it here: 

https://github.com/makerdao/maker-market/blob/868a80556ae7aabb470c94cc417f1df2abd074c9/frontend/imports/startup/client/network.js#L129

Which is almost the exact same code as the `web3.eth.isSyncing` example code in the API:

https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethissyncing

**Comment by flyswatter** [comment]
@nanexcool I think @kumavis understands `reset()` takes no callback, that's why he's suggesting we can support sync methods for those.  Right now we both don't support it in either way, which is to say we need to add support for it.

**Comment by nanexcool** [comment]
@flyswatter ah ok, I understand! Thanks!
