### ISSUE TITLE
Auto-detect mis-generated accounts and warn users

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#894]
Needs messaging system in place first.

Detect if any accounts are mis-generated, show text identifying those accounts, and link to blog post for solving.

**Comment by Zanibas** [comment]
Blocked by #892

**Comment by flyswatter** [comment]
The IPFS team has a cool visualization tool we could use if we start using this language instead of the blocked language:

Depends on #892

**Comment by flyswatter** [comment]
Also depends on #654, since we need to know how many accounts to check for validity.

**Comment by flyswatter** [comment]
Oh actually not on 654, since the vault includes how many accounts should be derived.  That issue is only for fresh restores.

**Comment by flyswatter** [comment]
I have this all working on the `RecoverLostAccounts` branch, but I need to combine it with the fix for  #932 or it's pretty meaningless, so will be fixing these with the same PR.
