### ISSUE TITLE
Check out Inferno

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#898]
We've wanted to reduce our load time & RAM consumption, and a new React equivalent called [Inferno](https://github.com/trueadm/inferno/blob/master/README.md) could do just that.

Previously we've considered moving direction to pure hyperscript or something similar, but were held back by our current usage of `ReactCssTransitionGroup`, and [Inferno has a replacement for that, too]( https://www.npmjs.com/package/inferno-transition-group).

**Comment by Zanibas** [comment]
We will most likely defer to staying for React in the meanwhile, in order to speed up development for DevCon. Maybe in the future we can explore this still!
