### ISSUE TITLE
Contract marked as published when actually pending

### ISSUE THREAD

**Issue by rolandkofler** [MetaMask/metamask-plugin#901]
The transaction was not published but Metamask says so.

https://testnet.etherscan.io/tx/0x9049b82253bcad519ff582c41bd3921ee5f3c6351f0d0fed42909238a816574a

![image](https://cloud.githubusercontent.com/assets/979444/20754109/a5d5c886-b709-11e6-896e-b70141489e3d.png)

**Comment by flyswatter** [comment]
This looks like another slow propagation issue, because it looks published now.

**Comment by rolandkofler** [comment]
Anyway you should not give false witness ;-)
Means you should wait until the tx is mined in order to say "contract published"

**Comment by flyswatter** [comment]
Agreed, I'll let this issue represent the false witness bug for now.

**Comment by flyswatter** [comment]
Now that we're merging the new TX Manager, this is just a UI issue!
