### ISSUE TITLE
Investigate Chromebook Compatibility

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#902]

**Comment by k26dr** [comment]
Has Chromebook compatibility been fixed yet? If not, I'd like to contribute to fixing this, I have an Ethereum Dapp I've built that I'd like to be able to use on my Chromebook.

**Comment by flyswatter** [comment]
By all means, anything you can do to debug it could help, only one of our team has a chromebook.

If you can get it installed, you might find valuable evidence in the logs:
https://github.com/MetaMask/faq/blob/master/LOGS.md

**Comment by k26dr** [comment]
These is the error I see in the background log. Any tips? I'll be attempting to debug and fix it. 

TypeError: Cannot read property 'provider' of undefined
    at ConfigManager.getProvider (background.js:1565)
    at ConfigManager.getCurrentRpcAddress (background.js:1642)
    at MetamaskController.initializeProvider (background.js:2975)
    at new MetamaskController (background.js:2865)
    at setupController (background.js:202)
    at background.js:162
    at _fulfilled (background.js:46119)
    at self.promiseDispatch.done (background.js:46148)
    at Promise.promise.promiseDispatch (background.js:46081)
    at background.js:45889

**Comment by k26dr** [comment]
Typing the command logState() into the background console throws an error. Is there some other way to get the UI State logs?

**Comment by k26dr** [comment]
Is the store being passed around everywhere a global redux store?

**Comment by k26dr** [comment]
Well, this is interesting. I cloned the repo onto my Chromebook and ran the extension locally, and it worked. The error that was showing up in the background logs does not show up in the developer version. 

So maybe there's some unreleased code that fixed the issue, whatever it was?

**Comment by Zanibas** [comment]
Sorry we didn't get to this sooner--got backlogged, if the issue still persists outside of the dev version, let us know.
