### ISSUE TITLE
Network should be visible on transaction confirmation page

### ISSUE THREAD

**Issue by rolandkofler** [MetaMask/metamask-plugin#924]
While the network, e.g. "Mainnet", "Ropsten" is visible on the main window, it doesn't appear when a transaction has to be confirmed. The user should have perfect overview of the transaction details and not fear that he sends to the wrong network.

**Comment by flyswatter** [comment]
Definitely sounds like a bug. I could've swore we showed the menu bar on the tx approval view.

- Dan

**Comment by rolandkofler** [comment]
Proof
![image](https://cloud.githubusercontent.com/assets/979444/21256458/b75d8312-c372-11e6-8aa0-a16a955319f7.png)

**Comment by rolandkofler** [comment]
BTW: sending from browser-solidity I get ALWAYS this error message... I learned to ignore it.

**Comment by flyswatter** [comment]
I wonder if this error message is related to the menu not being shown.  Usually we do show it:

<img width="383" alt="screen shot 2016-12-16 at 9 13 23 am" src="https://cloud.githubusercontent.com/assets/542863/21271492/097ed48c-c370-11e6-9649-0e8a41bb8796.png">

Thanks for that follow-up note, it may actually be related.

**Comment by flyswatter** [comment]
Hey @rolandkofler would you mind sending us or posting the Popup logs during this screen you have? https://github.com/MetaMask/faq/blob/master/LOGS.md#popup-logs-chrome

**Comment by rolandkofler** [comment]
Hey, I tried it with a fresh Chrome account, my old was in fact on Chromium.
No results. Console is silent 

![image](https://cloud.githubusercontent.com/assets/979444/21324472/1b95606e-c622-11e6-90cd-33f124528c99.png)

Fresh Ubuntu 16.04 / recent Chrome/ Chromium,  error is the same, Popup doesn't show the thing

![image](https://cloud.githubusercontent.com/assets/979444/21324509/5c07795c-c622-11e6-96bd-55b84457082b.png)

**Comment by rolandkofler** [comment]
here a gist of the popup: https://gist.github.com/rolandkofler/f55cae521011f1b341b9e578eed974e9

**Comment by flyswatter** [comment]
I was able to replicate the bug and [logged the state in this gist for debugging](https://gist.github.com/flyswatter/972d14ac13608e348431715467b288d3).

**Comment by Zanibas** [comment]
The popup has never shown the menu bar as far as I've known it. I've even pulled up a version from 2.13.2 and it has had this behavior. The menu bar shows up in the main app, but not in the popup windows.

![screenshot from 2016-12-21 15-17-19](https://cloud.githubusercontent.com/assets/1840057/21409744/c1c55e84-c790-11e6-8b67-a145a6e58163.png)

**Comment by flyswatter** [comment]
Huh, I guess I remember something like that.

The simple solution then is to just show the menu bar on the popups, too.  That should be very easy.

**Comment by Zanibas** [comment]
I'll leave this issue then to displaying the network on popups for transactions, and create a new issue for investigating the browser-solidity issue.
