### ISSUE TITLE
Handle case when user enters custom RPC url with no prefix

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#938]
If you just enter `0.0.0.0:8545`, metamask will silently fail, even though we know it's the lack of an http/https prefix.

Either we should try to find the right protocol, or we should warn the user.

**Comment by Zanibas** [comment]
Could I get some other test cases to compare against to ensure we're implementing this correctly? Should it be able to account for any IP?

**Comment by flyswatter** [comment]
Someone might point at any valid URI as their provider, so maybe [use a URI validator like this one](https://www.npmjs.com/package/valid-url).

One hard requirement is it needs successfully warn when a URI lacks http/https prefixes, and I see that module has special methods for that.
