### ISSUE TITLE
empty UI when importing a vault and not including "http://" in custom endpoint

### ISSUE THREAD

**Issue by jamesyoung** [MetaMask/metamask-plugin#941]
Chrome Version 55.0.2883.95 (64-bit)
macOS Sierra Version 10.12.3 Beta (16D12b)

I was able to reproduce this 3 times, below are repro steps
1. import key vault
2. change endpoint - do not prefix "http://"
3. click on metamask plugin icon

![metamask_bug](https://cloud.githubusercontent.com/assets/33074/21356866/fc179570-c687-11e6-9eda-e1a5decfe6d8.png)

**Comment by flyswatter** [comment]
Related to #938, but a worse expression of that issue.

**Comment by Zanibas** [comment]
The fix for this is currently in dev--may be fixed once we merge it into master.

**Comment by flyswatter** [comment]
@Zanibas oh whoops, we should've merged it into master, and pulled that out to `dev`, to allow for faster fixes.  Maybe Monday.
