### ISSUE TITLE
Coinbase purchase from existing user goes to existing user's account

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#966]
Instead of their metamask account.

I've been told.

**Comment by mardlin** [comment]
Sorry about this trouble. FYI, we're tracking this internally as API-159.

**Comment by flyswatter** [comment]
Oh, thanks for the update!

- Dan

**Comment by mardlin** [comment]
A fix for this was deployed last night.

**Comment by flyswatter** [comment]
Thanks!!
