### ISSUE TITLE
No account detected error after a game of Etherplay

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#975]
Something weird happened on our `dev` branch (does not concern production):

I played the new main-net version of [Etherplay][1], and after not winning, I still submitted my results for consideration (I believe a silly move), and then after it loaded a while, it took me to a new page, and I got an error that it couldn't detect my account.

I checked `web3.eth.accounts`, and it was an empty array.
I reloaded, it stayed an empty array.  
I logged out and in again, it stayed an empty array.

I want to make sure I've tracked this down and eliminated it before we merge `dev` to `master`.

[1]: http://etherplay.io/

**Comment by kumavis** [comment]
unrelated to the bug, I think "game over" is the only ending

**Comment by kumavis** [comment]
issue seems to come from here
we are not composing our stores together gracefully
https://github.com/MetaMask/metamask-plugin/blob/dev/app/scripts/metamask-controller.js#L238-L246
