### ISSUE TITLE
Remove Copy/Paste Permissions Requirement

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-plugin#978]
When installing the MetaMask chrome plugin, Chrome tells me that MetaMask wants direct access to my clipboard contents.  This creates a potential security hole for anyone that uses a password manager as passwords often flow through the clipboard.  If the MetaMask plugin was to be compromised, the attacker would gain direct access to all secure data passing through the clipboard, even for tabs where the MetaMask plugin is disabled.

I recognize that since MetaMask can already read/write all website data that it already has access to any password entered into a tab that has MetaMask active, a prudent user should be able to at *least* deactivate the plugin for that page and not be at risk.  By having complete clipboard access MetaMask can read any password managed by a password manager via the clipboard, even if the password never lands in Chrome.

How critical is the read access to the clipboard?  I'm not sure how it is used, but it seems like requiring users to paste a value isn't a big requirement as most users are quite comfortable with copy/paste semantics.  Is the problem that chrome permissions aren't granular enough and if you want to be able to *write* to the clipboard you must also be allowed to read from it (a quick glance suggests these are separate permissions)?

**Comment by Zanibas** [comment]
This has been brought up in #809, resolved in #965 by merging into our dev, and will be integrated as soon as we merge that branch into our production distribution ^^.

**Comment by Zanibas** [comment]
The permissions are still left in for Opera because that's required for submission into the store for some reason, but all other builds should have this permission stripped with the PR mentioned above.

**Comment by MicahZoltu** [comment]
Bleh.  I tried to search for this issue before posting, but apparently I didn't use the right search terms.  Will close, thanks!
