### ISSUE TITLE
Request: disable on this page

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/metamask-plugin#980]
Trying to use browser solidity and a friendly little fox keeps popping up =). Would be nice to be able to disable metamask on certain pages.

https://ethereum.github.io/browser-solidity/

**Comment by flyswatter** [comment]
Closing as duplicate of #714.

We know this is important, and we want to get to it soon.

**Comment by flyswatter** [comment]
Also though, in the mean while you can right click MetaMask, select manage extensions, and uncheck metamask's "enabled" box to disable it.

- Dan
