### ISSUE TITLE
Add a way to reliably detect metamask use

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-plugin#989]
It has been brought up at some point and the answer was to detect the use of the provider engine to detect the use of metamask or something like that.

I would like to have a reliable way to detect the use of metamask.

This is necessary to display help message for the player :

- How to switch network ?

- How can I point metamask to a local node ?

Currently if we do not know what client the players are using we cannot display specific message to help on these questions.

**Comment by kumavis** [comment]
you can use `web3.currentProvider.isMetaMask`

we can add an entry for these questions in our FAQ if we dont currently have them.
https://github.com/metamask/faq

**Comment by wighawag** [comment]
cool thanks
